import type { Track, GuidedProblem } from "@/content/types";

export const coreMlTrack: Track = {
  id: "ml-core",
  title: "Core Machine Learning",
  modules: [
    {
      id: "core-concepts",
      title: "Model concepts",
      lessons: [
        {
          id: "core-workflow",
          title: "The ML workflow",
          summary: "Frame, prepare, train, evaluate, deploy — the full loop.",
          blocks: [
            { kind: "prose", text: "Every ML project follows the same arc, no matter the algorithm. Internalize it once and you'll see it everywhere." },
            { kind: "heading", text: "The seven steps" },
            { kind: "code", lang: "text", code: "1. Frame the problem    (regression? classification? what is success?)\n2. Collect data         (Kaggle, APIs, your DB)\n3. Explore & clean      (df.info, .describe, missing values, outliers)\n4. Feature engineering  (encoding, scaling, derived columns)\n5. Train models         (fit on train, multiple candidates)\n6. Evaluate             (on test/validation, the right metric)\n7. Deploy & monitor     (serve as API, watch for drift)" },
            { kind: "heading", text: "What a 'model' actually is" },
            { kind: "prose", text: "A model is a function f(X) → y, with parameters learned from data. Linear regression's model is y = Xw + b; the parameters are w and b. Training = finding parameters that minimize error on training data." },
            { kind: "callout", tone: "tip", text: "80% of real ML time is on steps 2–4 (data work). Algorithm choice matters less than people think; data quality matters more." },
            { kind: "keypoints", points: ["Frame → collect → clean → engineer → train → evaluate → deploy", "A model is a parameterized function f(X) → y", "Training finds parameters that minimize error on training data", "Data work dominates real ML time, not algorithm tuning", "Define success and the metric BEFORE you train anything"] },
            { kind: "practice", text: "Walk a project through:", items: ["For 'predict house prices', list all 7 steps with concrete actions.", "Why must you define success before training?", "What separates training data from test data?", "Stretch: name a metric for regression and one for classification."] },
          ],
        },
        {
          id: "core-model-selection",
          title: "Model selection & cross-validation",
          summary: "Pick the right model — without fooling yourself.",
          blocks: [
            { kind: "prose", text: "How do you decide which model is best? Compare them on data they haven't seen. But a single train/test split is noisy. Cross-validation gives a more honest estimate." },
            { kind: "heading", text: "k-fold cross-validation" },
            { kind: "prose", text: "Split training data into k folds (commonly 5 or 10). Train on k-1 folds, evaluate on the held-out fold. Repeat k times so every fold has a turn. Average the scores." },
            { kind: "code", lang: "python", code: "from sklearn.model_selection import cross_val_score\nfrom sklearn.linear_model import LogisticRegression\n\nscores = cross_val_score(\n    LogisticRegression(),\n    X_train, y_train,\n    cv=5, scoring=\"accuracy\",\n)\nprint(scores.mean(), scores.std())" },
            { kind: "heading", text: "Stratified CV for classification" },
            { kind: "prose", text: "Use `StratifiedKFold` so each fold preserves class proportions. sklearn does this by default for classifiers." },
            { kind: "callout", tone: "warn", text: "Apply any preprocessing (scaling, encoding) INSIDE each fold, not before splitting. Otherwise the validation fold leaks into training. Use `Pipeline` to do this cleanly." },
            { kind: "keypoints", points: ["k-fold CV averages k held-out scores for a robust estimate", "Common k: 5 or 10", "Stratified CV preserves class balance for classification", "Scale and encode INSIDE the fold to avoid leakage", "Test set still stays untouched until the very end"] },
            { kind: "practice", text: "Cross-validate:", items: ["Run 5-fold CV for LogisticRegression on a dataset.", "Print the mean and std of the scores.", "Why is the std useful, not just the mean?", "Stretch: why is leakage worse than picking the slightly wrong model?"] },
          ],
        },
        {
          id: "core-overfitting",
          title: "Overfitting & underfitting",
          summary: "Two failure modes, and how to spot them.",
          blocks: [
            { kind: "prose", text: "Underfitting: model is too simple to capture the pattern. Overfitting: model memorizes the training data, including its noise, and fails to generalize." },
            { kind: "heading", text: "How to spot each" },
            { kind: "code", lang: "text", code: "Train acc  Test acc   Diagnosis\n  60%       58%       Underfit  (both low → need a richer model)\n  99%       62%       Overfit   (big gap → need to regularize)\n  91%       89%       Good      (high, close)" },
            { kind: "heading", text: "Fixes for overfitting" },
            { kind: "prose", text: "Get more data (best). Add regularization (L1, L2). Reduce model complexity (fewer features, smaller tree depth). Use cross-validation to detect it early. Add dropout in neural nets." },
            { kind: "heading", text: "Fixes for underfitting" },
            { kind: "prose", text: "Use a more flexible model (more features, deeper tree, more layers). Add useful features. Reduce regularization. Train longer." },
            { kind: "callout", tone: "tip", text: "The biggest tell of overfitting: training score keeps improving while validation score plateaus or worsens. Always plot both as you train." },
            { kind: "keypoints", points: ["Underfit: high error on BOTH train and test", "Overfit: low train error, much higher test error", "Fix overfitting with more data, regularization, simpler model", "Fix underfitting with richer model, better features, less regularization", "Track train AND validation scores during training"] },
            { kind: "practice", text: "Diagnose models:", items: ["Train 99% / test 70% — what is happening?", "Train 65% / test 64% — what is happening?", "Name three fixes for overfitting.", "Stretch: how does dropout in neural nets reduce overfitting?"] },
          ],
        },
        {
          id: "core-bias-variance",
          title: "Bias-variance tradeoff",
          summary: "The fundamental dial of ML model complexity.",
          blocks: [
            { kind: "prose", text: "Total error of a model decomposes into bias (how wrong its assumptions are) + variance (how much its predictions wobble with different training data) + irreducible noise." },
            { kind: "heading", text: "High bias, low variance" },
            { kind: "prose", text: "Underfit. Simple models like linear regression on a curvy relationship. The model is too rigid to capture the pattern." },
            { kind: "heading", text: "Low bias, high variance" },
            { kind: "prose", text: "Overfit. Deep decision trees, k-NN with k=1. The model wraps too tightly around the training data and shifts dramatically with small changes." },
            { kind: "heading", text: "The tradeoff" },
            { kind: "prose", text: "Increasing model complexity reduces bias but raises variance. The sweet spot minimizes total error. This is the dial every regularization parameter, every tree depth, every layer count is fundamentally turning." },
            { kind: "code", lang: "text", code: "Complexity →\nBias:       high ────────► low\nVariance:   low  ◄──────── high\nTotal err:  high ─→ LOW ◄─── high" },
            { kind: "keypoints", points: ["Error = bias² + variance + irreducible noise", "High bias = too simple = underfit", "High variance = too complex = overfit", "Increasing complexity trades bias for variance", "Best complexity minimizes total error"] },
            { kind: "practice", text: "Tradeoffs:", items: ["Is k-NN with k=1 high bias or high variance?", "What about a linear model fitting clearly nonlinear data?", "How does training-set size affect variance?", "Stretch: why is ensembling (e.g. random forests) good at reducing variance?"] },
          ],
        },
        {
          id: "core-loss",
          title: "Loss functions",
          summary: "What 'wrong' means to a model — the thing it minimizes.",
          blocks: [
            { kind: "prose", text: "A loss function turns predictions vs truth into a single number measuring 'how wrong'. The training loop adjusts parameters to minimize this number." },
            { kind: "heading", text: "Regression losses" },
            { kind: "prose", text: "MSE (mean squared error): mean of (y - ŷ)². Penalizes big errors heavily. MAE (mean absolute error): mean of |y - ŷ|. More robust to outliers." },
            { kind: "code", lang: "python", code: "import numpy as np\ny = np.array([1, 2, 3])\nyhat = np.array([1.5, 2.0, 2.5])\nmse = np.mean((y - yhat) ** 2)   # 0.0833\nmae = np.mean(np.abs(y - yhat))  # 0.333" },
            { kind: "heading", text: "Classification losses" },
            { kind: "prose", text: "Cross-entropy (log loss): penalizes confident wrong answers severely. The standard for logistic regression, softmax, and neural-net classifiers." },
            { kind: "code", lang: "python", code: "# Binary cross-entropy for one example\n# L = -[y · log(p) + (1-y) · log(1-p)]\nimport numpy as np\ny, p = 1, 0.9\nL = -(y * np.log(p) + (1 - y) * np.log(1 - p))\nprint(L)   # 0.105   (low: confident & correct)\n\ny, p = 1, 0.1\nL = -(y * np.log(p) + (1 - y) * np.log(1 - p))\nprint(L)   # 2.303   (high: confident & WRONG)" },
            { kind: "callout", tone: "tip", text: "The loss tells the optimizer what to chase. Picking the wrong loss (e.g. MSE for classification) typically gives worse results than choosing the wrong algorithm." },
            { kind: "keypoints", points: ["Loss = how wrong, as a number to minimize", "Regression: MSE penalizes large errors; MAE is robust to outliers", "Classification: cross-entropy (log loss) is standard", "Cross-entropy punishes confident wrong predictions hard", "Pick the loss to match the task"] },
            { kind: "practice", text: "Compute losses:", items: ["For y=[1,2,3], ŷ=[1,2,4], compute MSE and MAE.", "Why does MSE punish outliers more than MAE?", "For binary cross-entropy with y=0 and p=0.9, is the loss small or large?", "Stretch: why MSE is wrong for binary classification?"] },
          ],
        },
        {
          id: "core-metrics",
          title: "Evaluation metrics",
          summary: "Score a model honestly — accuracy, precision, recall, F1, AUC.",
          blocks: [
            { kind: "prose", text: "The metric you report is the metric that gets optimized. Picking it badly means optimizing the wrong thing." },
            { kind: "heading", text: "Classification metrics" },
            { kind: "prose", text: "Confusion matrix: TP, FP, FN, TN. From these come the others." },
            { kind: "code", lang: "text", code: "Accuracy  = (TP + TN) / total          overall correct\nPrecision = TP / (TP + FP)             of predicted positives, how many really are?\nRecall    = TP / (TP + FN)             of actual positives, how many did we catch?\nF1        = 2·P·R / (P + R)            harmonic mean — balanced score\nROC-AUC   = area under ROC curve       discrimination ability, threshold-free" },
            { kind: "code", lang: "python", code: "from sklearn.metrics import classification_report, roc_auc_score\nprint(classification_report(y_test, y_pred))\nprint(roc_auc_score(y_test, y_proba))" },
            { kind: "heading", text: "When to use which" },
            { kind: "prose", text: "Precision when false positives are costly (e.g. medical alerts that scare patients). Recall when false negatives are costly (e.g. catching fraud or cancer). F1 when both matter. ROC-AUC for general discrimination, especially with imbalance." },
            { kind: "heading", text: "Regression metrics" },
            { kind: "prose", text: "MAE, MSE, RMSE (=√MSE, same units as y), R² (variance explained, 1.0 = perfect, 0.0 = no better than mean)." },
            { kind: "callout", tone: "warn", text: "Never report only accuracy on imbalanced data. Always include precision, recall, F1, and a confusion matrix." },
            { kind: "keypoints", points: ["Confusion matrix is the source of most classification metrics", "Precision = correctness of positive predictions", "Recall = coverage of actual positives", "F1 balances precision and recall", "Regression: MAE, RMSE, R² are the standards"] },
            { kind: "practice", text: "Compute metrics:", items: ["TP=80, FP=20, FN=10, TN=890. Compute precision, recall, F1.", "When is recall more important than precision?", "What does R² = 0.85 mean?", "Stretch: why does the F1 formula use the harmonic mean?"] },
          ],
        },
        {
          id: "core-gd",
          title: "Gradient descent",
          summary: "How models actually learn — by following the slope downhill.",
          blocks: [
            { kind: "prose", text: "Gradient descent is the engine inside almost every modern ML model. To minimize a loss, repeatedly take a small step in the direction that decreases it fastest: the negative gradient." },
            { kind: "heading", text: "The update rule" },
            { kind: "code", lang: "text", code: "w ← w - η · ∇L(w)\n\n  w  = parameters\n  η  = learning rate (how big the step)\n  ∇L = gradient of the loss with respect to w" },
            { kind: "heading", text: "A concrete example" },
            { kind: "prose", text: "Minimize L(w) = (w - 3)². Gradient: dL/dw = 2(w - 3). Start at w=0, η=0.1." },
            { kind: "code", lang: "python", code: "w = 0\nfor _ in range(20):\n    grad = 2 * (w - 3)\n    w = w - 0.1 * grad\n    print(f\"w = {w:.3f}\")\n# w drifts smoothly toward 3" },
            { kind: "heading", text: "Learning rate" },
            { kind: "prose", text: "Too small: training crawls. Too large: it overshoots and may diverge. Tuning η is the single most impactful hyperparameter for neural nets." },
            { kind: "heading", text: "Variants" },
            { kind: "prose", text: "Batch GD: gradient on all data per step (slow, stable). SGD: gradient on one example per step (fast, noisy). Mini-batch GD: gradient on small batches (the practical sweet spot, what neural networks use)." },
            { kind: "callout", tone: "tip", text: "When training diverges (loss explodes), the first thing to try is lowering the learning rate by 10x." },
            { kind: "keypoints", points: ["Gradient descent minimizes a loss by stepping opposite the gradient", "Update: w ← w - η · ∇L(w)", "Learning rate η controls step size — too big diverges, too small crawls", "Batch GD = full data; SGD = one example; mini-batch = small chunk", "Mini-batch is the standard for neural networks"] },
            { kind: "practice", text: "Run gradient descent:", items: ["Minimize L(w) = (w - 5)² starting at w=0 with η=0.1 for 10 steps.", "What happens if η = 1.1 for L(w) = (w-3)²?", "Why is SGD noisier than batch GD?", "Stretch: connect this to how a neural net trains."] },
          ],
        },
      ],
    },
    {
      id: "core-algorithms",
      title: "Algorithms",
      lessons: [
        {
          id: "core-linreg",
          title: "Linear regression",
          summary: "Fit a line (or plane) by minimizing squared error.",
          blocks: [
            { kind: "prose", text: "Linear regression assumes the target is a linear combination of features: y ≈ Xw + b. It's the simplest useful regression model and the entry point to most ML theory." },
            { kind: "heading", text: "The model" },
            { kind: "prose", text: "For one feature: ŷ = wx + b. For d features: ŷ = w₁x₁ + ... + wdxd + b = x · w + b. Loss is MSE: (1/n) Σ (yᵢ - ŷᵢ)²." },
            { kind: "heading", text: "Two ways to solve" },
            { kind: "prose", text: "Closed-form (normal equation): w = (XᵀX)⁻¹ Xᵀy. Direct but O(d³) — bad for many features. Gradient descent: scales to huge data, neural networks use this." },
            { kind: "code", lang: "python", code: "from sklearn.linear_model import LinearRegression\nmodel = LinearRegression().fit(X_train, y_train)\nprint(model.coef_, model.intercept_)\npreds = model.predict(X_test)" },
            { kind: "heading", text: "Assumptions" },
            { kind: "prose", text: "Linearity, independent errors, constant error variance, no extreme multicollinearity. Violations don't break the model but they hurt its reliability." },
            { kind: "heading", text: "From scratch" },
            { kind: "code", lang: "python", code: "import numpy as np\n\nclass LinReg:\n    def __init__(self, lr=0.01, epochs=1000):\n        self.lr, self.epochs = lr, epochs\n    def fit(self, X, y):\n        n, d = X.shape\n        self.w, self.b = np.zeros(d), 0.0\n        for _ in range(self.epochs):\n            yhat = X @ self.w + self.b\n            dw = (2/n) * X.T @ (yhat - y)\n            db = (2/n) * (yhat - y).sum()\n            self.w -= self.lr * dw\n            self.b -= self.lr * db\n    def predict(self, X):\n        return X @ self.w + self.b" },
            { kind: "keypoints", points: ["Model: ŷ = Xw + b", "Loss: MSE", "Solved by normal equation or gradient descent", "Highly interpretable: coefficients = feature importance", "Foundation for many richer models (ridge, lasso, neural nets)"] },
            { kind: "practice", text: "Fit linear regression:", items: ["Use sklearn LinearRegression on a 1-feature dataset.", "Print the slope and intercept.", "Why does MSE punish outliers more than MAE here?", "Stretch: implement gradient descent for ŷ = wx for one feature."] },
          ],
        },
        {
          id: "core-logreg",
          title: "Logistic regression",
          summary: "Linear regression for classification, via the sigmoid.",
          blocks: [
            { kind: "prose", text: "Despite its name, logistic regression does classification. It uses a linear score, then squashes it into a probability via the sigmoid." },
            { kind: "heading", text: "The model" },
            { kind: "code", lang: "text", code: "score   z = x · w + b\nsigmoid σ(z) = 1 / (1 + e^(-z))\nP(y=1)  = σ(z)\npredict  ŷ = 1 if σ(z) > 0.5 else 0" },
            { kind: "heading", text: "Loss" },
            { kind: "prose", text: "Binary cross-entropy: L = -[y log(p) + (1-y) log(1-p)]. Convex in w — no local minima." },
            { kind: "code", lang: "python", code: "from sklearn.linear_model import LogisticRegression\nmodel = LogisticRegression(class_weight=\"balanced\", max_iter=1000)\nmodel.fit(X_train, y_train)\nprint(model.coef_, model.intercept_)\nproba = model.predict_proba(X_test)[:, 1]" },
            { kind: "heading", text: "Multi-class" },
            { kind: "prose", text: "For more than two classes, replace sigmoid with softmax: turns scores into a probability vector over k classes that sums to 1." },
            { kind: "callout", tone: "tip", text: "Logistic regression is fast, interpretable, and a great baseline. If a fancier model can't beat it by much, prefer it." },
            { kind: "keypoints", points: ["Linear score + sigmoid = probability of class 1", "Decision rule: predict class 1 if p > 0.5", "Loss = cross-entropy (log loss)", "Convex → reliable training", "Multi-class via softmax"] },
            { kind: "practice", text: "Logistic regression:", items: ["Train one and print `model.predict_proba(X)[:5]`.", "How is the decision boundary related to the linear score?", "Why is the threshold sometimes tuned away from 0.5?", "Stretch: connect softmax to sigmoid (binary is a special case)."] },
          ],
        },
        {
          id: "core-svm",
          title: "Support vector machines",
          summary: "Find the widest-margin separating boundary.",
          blocks: [
            { kind: "prose", text: "An SVM finds the hyperplane that separates classes with the maximum margin: the largest possible gap on both sides. Robust and effective, especially with the kernel trick for non-linear data." },
            { kind: "heading", text: "Hard vs soft margin" },
            { kind: "prose", text: "Hard margin: requires perfectly separable data — usually unrealistic. Soft margin allows some misclassifications, controlled by C: small C → wider margin, more mistakes allowed; large C → narrower margin, fewer mistakes." },
            { kind: "heading", text: "Kernel trick" },
            { kind: "prose", text: "When classes are not linearly separable, map them into a higher-dimensional space where they might be. The kernel computes the dot product in that space without explicitly constructing it. RBF (Gaussian) and polynomial kernels are common." },
            { kind: "code", lang: "python", code: "from sklearn.svm import SVC\nmodel = SVC(kernel=\"rbf\", C=1.0, gamma=\"scale\")\nmodel.fit(X_train, y_train)" },
            { kind: "heading", text: "Loss" },
            { kind: "prose", text: "Hinge loss: L = max(0, 1 - y · score). Zero loss when correctly classified with margin ≥ 1; linear penalty otherwise." },
            { kind: "callout", tone: "warn", text: "SVMs require feature scaling and don't scale well to huge datasets (the training is O(n²) to O(n³)). They shine on small-to-medium, high-dimensional data." },
            { kind: "keypoints", points: ["SVM maximizes the margin between classes", "Soft margin (C) tolerates some mistakes for a wider gap", "Kernel trick handles non-linear boundaries", "Hinge loss is the objective", "Sensitive to scaling; not great for huge datasets"] },
            { kind: "practice", text: "Use SVMs:", items: ["Train an RBF SVM on a small classification dataset.", "What does increasing C do?", "Why must you scale features before SVM?", "Stretch: what would a polynomial kernel of degree 2 represent?"] },
          ],
        },
        {
          id: "core-trees-rf",
          title: "Decision trees & random forests",
          summary: "Splits all the way down — and a forest beats one tree.",
          blocks: [
            { kind: "prose", text: "A decision tree splits the data on one feature at a time. Each split picks the feature and threshold that reduces impurity (Gini for classification, MSE for regression) the most. Easy to interpret, but a single deep tree overfits." },
            { kind: "heading", text: "Random forest" },
            { kind: "prose", text: "A random forest trains many trees, each on a bootstrap sample of rows and a random subset of features per split. Aggregate by majority vote (classification) or mean (regression). The randomness decorrelates the trees, dramatically reducing variance." },
            { kind: "code", lang: "python", code: "from sklearn.tree import DecisionTreeClassifier\nfrom sklearn.ensemble import RandomForestClassifier\n\ntree = DecisionTreeClassifier(max_depth=5).fit(X_train, y_train)\nrf = RandomForestClassifier(n_estimators=200, max_depth=None).fit(X_train, y_train)\n\nprint(rf.feature_importances_)" },
            { kind: "heading", text: "Pros & cons" },
            { kind: "prose", text: "Pros: handle non-linear relationships, no scaling needed, give feature importance, work on mixed data types. Cons: trees overfit; forests can be slow and large." },
            { kind: "callout", tone: "tip", text: "For most tabular data problems, a random forest or gradient-boosted trees (XGBoost / LightGBM) is the strongest off-the-shelf baseline. Try them first." },
            { kind: "keypoints", points: ["Tree = recursive splits on one feature at a time", "Gini / MSE measure impurity; splits maximize reduction", "Random forest = many trees, each on a bootstrap sample + random features", "Forests reduce variance via aggregation", "No scaling needed; feature importances out of the box"] },
            { kind: "practice", text: "Trees and forests:", items: ["Train a DecisionTree with max_depth=3 and visualize predictions.", "Train a RandomForest and print feature_importances_.", "Why does a forest reduce variance vs a single tree?", "Stretch: how is gradient boosting different from a random forest?"] },
          ],
        },
        {
          id: "core-knn-nb",
          title: "k-NN & Naive Bayes",
          summary: "Two simple but effective classical models.",
          blocks: [
            { kind: "prose", text: "Two more classical workhorses worth knowing. k-NN is lazy (no real training). Naive Bayes is fast and shockingly good on text." },
            { kind: "heading", text: "k-Nearest Neighbors" },
            { kind: "prose", text: "To predict, find the k closest training points and majority-vote their labels (or average their values for regression). Distance is usually Euclidean. Small k → noisy/overfit; large k → over-smooth." },
            { kind: "code", lang: "python", code: "from sklearn.neighbors import KNeighborsClassifier\nmodel = KNeighborsClassifier(n_neighbors=5).fit(X_train, y_train)" },
            { kind: "callout", tone: "warn", text: "k-NN MUST have scaled features — otherwise large-scale features dominate the distance. Also slow at prediction time for large datasets." },
            { kind: "heading", text: "Naive Bayes" },
            { kind: "prose", text: "Applies Bayes' theorem under the (naive) assumption that features are conditionally independent given the class. Fast to train and predict, gives calibrated probabilities, and remains a strong baseline for text classification." },
            { kind: "code", lang: "python", code: "from sklearn.naive_bayes import MultinomialNB\nmodel = MultinomialNB().fit(X_train_tfidf, y_train)" },
            { kind: "keypoints", points: ["k-NN: majority vote among k nearest neighbors", "k-NN needs scaled features; slow at prediction time", "Naive Bayes assumes features are conditionally independent", "Naive Bayes is fast and a strong baseline for text", "Both are simple, interpretable, and useful as baselines"] },
            { kind: "practice", text: "Try them:", items: ["Train k-NN with k=5 on scaled features.", "Train MultinomialNB on TF-IDF text features.", "Why does k-NN's prediction get slower with more data?", "Stretch: when does Naive Bayes' independence assumption hurt it?"] },
          ],
        },
        {
          id: "core-kmeans-pca",
          title: "k-Means & PCA",
          summary: "Unsupervised classics: clustering and dimensionality reduction.",
          blocks: [
            { kind: "prose", text: "Two unsupervised techniques you'll use constantly. k-Means groups data; PCA shrinks it." },
            { kind: "heading", text: "k-Means clustering" },
            { kind: "prose", text: "Pick k centers, assign each point to the nearest one, then move each center to the mean of its assigned points. Repeat until stable. Result: k clusters that minimize within-cluster squared distance." },
            { kind: "code", lang: "python", code: "from sklearn.cluster import KMeans\nkm = KMeans(n_clusters=4, n_init=10, random_state=42).fit(X)\nprint(km.labels_[:10])\nprint(km.cluster_centers_)" },
            { kind: "prose", text: "Choosing k: try multiple and use the elbow method (plot inertia vs k, look for the bend) or silhouette score." },
            { kind: "heading", text: "PCA: principal component analysis" },
            { kind: "prose", text: "Find the directions in feature space along which data varies most. Project onto the top k directions to compress the data while preserving as much variance as possible. Used for visualization (2D/3D), denoising, and speeding up other models." },
            { kind: "code", lang: "python", code: "from sklearn.decomposition import PCA\npca = PCA(n_components=2).fit(X_scaled)\nX2 = pca.transform(X_scaled)\nprint(pca.explained_variance_ratio_)   # how much each PC explains" },
            { kind: "callout", tone: "warn", text: "Always scale features before PCA. Otherwise PCA picks the directions of features with the biggest raw numerical scale, not the most informative ones." },
            { kind: "keypoints", points: ["k-Means: alternate assign-to-nearest-center / move-centers-to-mean", "Choose k via elbow or silhouette", "PCA finds directions of maximum variance", "Project onto top components to reduce dimensions", "Both require scaled numeric features"] },
            { kind: "practice", text: "Cluster and reduce:", items: ["Run KMeans with n_clusters=3 on a small dataset.", "Plot the inertia for k=1..10 and find the elbow.", "Project a high-dim dataset to 2D with PCA and scatter-plot it.", "Stretch: why does PCA require scaling?"] },
          ],
        },
      ],
    },
    {
      id: "core-workflow-mod",
      title: "Practical workflow & projects",
      lessons: [
        {
          id: "core-pipeline",
          title: "Pipelines & end-to-end workflow",
          summary: "Build one clean object that does cleaning + model + prediction.",
          blocks: [
            { kind: "prose", text: "A scikit-learn Pipeline chains preprocessing and a model into one object. Why bother? It prevents data leakage, makes cross-validation correct by construction, and ships easily." },
            { kind: "heading", text: "A typical pipeline" },
            { kind: "code", lang: "python", code: "from sklearn.pipeline import Pipeline\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.linear_model import LogisticRegression\n\npipe = Pipeline([\n    (\"scaler\", StandardScaler()),\n    (\"clf\", LogisticRegression()),\n])\npipe.fit(X_train, y_train)\nprint(pipe.score(X_test, y_test))" },
            { kind: "heading", text: "Column transformer" },
            { kind: "prose", text: "Different columns need different preprocessing. `ColumnTransformer` applies the right step to the right columns: scale numerics, one-hot encode categoricals, all inside the pipeline." },
            { kind: "code", lang: "python", code: "from sklearn.compose import ColumnTransformer\nfrom sklearn.preprocessing import OneHotEncoder\n\npre = ColumnTransformer([\n    (\"num\", StandardScaler(), num_cols),\n    (\"cat\", OneHotEncoder(handle_unknown=\"ignore\"), cat_cols),\n])\n\nfull = Pipeline([(\"pre\", pre), (\"clf\", LogisticRegression())])" },
            { kind: "heading", text: "Hyperparameter search" },
            { kind: "code", lang: "python", code: "from sklearn.model_selection import GridSearchCV\nparams = {\"clf__C\": [0.01, 0.1, 1, 10]}\ngrid = GridSearchCV(full, params, cv=5)\ngrid.fit(X_train, y_train)\nprint(grid.best_params_, grid.best_score_)" },
            { kind: "callout", tone: "tip", text: "If you remember one thing from this lesson: use Pipeline. It eliminates an entire category of data-leakage bugs." },
            { kind: "keypoints", points: ["Pipeline chains preprocessing + model into one object", "ColumnTransformer handles per-column preprocessing", "Prevents leakage inside cross-validation by construction", "GridSearchCV tunes hyperparameters across the whole pipeline", "One object to serialize and deploy"] },
            { kind: "practice", text: "Build a pipeline:", items: ["Make a Pipeline of StandardScaler + LogisticRegression and `.fit` it.", "Add GridSearchCV over `clf__C` in [0.01, 0.1, 1, 10].", "Why is leakage prevented automatically here?", "Stretch: use ColumnTransformer with numeric + categorical columns."] },
          ],
        },
        {
          id: "core-projects",
          title: "Project ideas to build",
          summary: "Apply everything to real datasets.",
          blocks: [
            { kind: "prose", text: "Theory clicks when you ship something. Here are stand-alone projects spanning regression, classification, clustering, and text — mirroring Siddhardhan's playlist projects." },
            { kind: "heading", text: "Suggested projects" },
            { kind: "code", lang: "text", code: "Regression\n  • House price prediction         (Kaggle housing data)\n  • Car price prediction\n  • Medical insurance cost\n\nClassification\n  • Diabetes prediction\n  • Heart disease prediction\n  • Spam mail classifier (with TF-IDF)\n  • Titanic survival\n  • Credit card fraud detection (imbalanced!)\n\nClustering / unsupervised\n  • Customer segmentation (k-Means)\n  • Mall customers grouping\n\nNLP\n  • Fake news classifier\n  • Movie recommendation (content-based)" },
            { kind: "heading", text: "How to structure a project" },
            { kind: "code", lang: "text", code: "1. README.md            problem, data, approach, results, how to run\n2. data/                raw + processed (don't commit huge files)\n3. notebooks/           exploration, EDA\n4. src/                 reusable code: load.py, preprocess.py, train.py, evaluate.py\n5. models/              saved model artefacts\n6. requirements.txt     pinned dependencies" },
            { kind: "callout", tone: "tip", text: "Aim for 2-3 polished projects on GitHub over 10 half-finished ones. Recruiters read the top one carefully; depth beats breadth." },
            { kind: "keypoints", points: ["Build at least one regression, one classification, one clustering project", "Practise text/NLP with a TF-IDF + classifier project", "Structure as data/notebooks/src/models with a README", "Document the problem, decisions, and results", "Depth > breadth: 2-3 polished projects beat 10 rough ones"] },
            { kind: "practice", text: "Plan your first projects:", items: ["Pick a regression project and write its README outline first.", "Pick a classification project that uses an imbalanced metric mindset.", "Plan one NLP project using TF-IDF + logistic regression.", "Stretch: decide a portfolio order that shows breadth across families."] },
          ],
        },
      ],
    },
  ],
};

export const coreMlGuided: GuidedProblem[] = [
  {
    id: "core-workflow-g1",
    lessonId: "core-workflow",
    title: "Frame an ML problem",
    prompt: "You're asked to 'predict customer churn'. Walk through steps 1-3 of the workflow: frame the problem, identify the data you'd need, and the first cleaning checks you'd run.",
    hints: ["What kind of task is churn? What is the label?", "Think customer table + behavior history."],
    solution: [
      { kind: "prose", text: "1) Frame: binary classification — predict churn (yes/no) for each customer over a fixed horizon (e.g. next 30 days). Success metric: recall on the churn class (you want to catch them), with precision/F1 for balance." },
      { kind: "prose", text: "2) Data: customer profile + activity history. Features like tenure, plan, support tickets, last-login age. Label: did this customer churn in the next 30 days (using historical data with a 30-day gap)." },
      { kind: "prose", text: "3) Cleaning: check missing rates per column, distributions of numeric columns, class balance (churn is usually imbalanced), and dedupe by customer id." },
    ],
  },
  {
    id: "core-model-selection-g1",
    lessonId: "core-model-selection",
    title: "Cross-validate without leakage",
    prompt: "Write a 5-fold cross-validation for LogisticRegression on (X, y), with feature scaling done inside each fold.",
    hints: ["Use Pipeline so scaling fits inside each fold.", "cross_val_score wraps the rest."],
    solution: [
      { kind: "code", lang: "python", code: "from sklearn.pipeline import Pipeline\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.model_selection import cross_val_score\n\npipe = Pipeline([\n    (\"scaler\", StandardScaler()),\n    (\"clf\", LogisticRegression()),\n])\nscores = cross_val_score(pipe, X, y, cv=5, scoring=\"accuracy\")\nprint(scores.mean(), scores.std())" },
      { kind: "prose", text: "Because the scaler sits inside the pipeline, it is refit on each training fold and never sees the validation fold, no leakage." },
    ],
  },
  {
    id: "core-overfitting-g1",
    lessonId: "core-overfitting",
    title: "Diagnose three models",
    prompt: "Three models give: A) train 98%, test 70%; B) train 65%, test 64%; C) train 90%, test 88%. Diagnose each and propose one fix.",
    hints: ["Compare gap and absolute level.", "Big gap = overfit; both low = underfit; both high & close = good."],
    solution: [
      { kind: "prose", text: "A: overfit (big gap). Fix: regularization (raise alpha/lower C), reduce model complexity, or get more data." },
      { kind: "prose", text: "B: underfit (both low). Fix: richer model (more features, deeper tree), better feature engineering, train longer." },
      { kind: "prose", text: "C: good. Keep it; maybe try a bit more capacity to see if you can lift both numbers." },
    ],
  },
  {
    id: "core-bias-variance-g1",
    lessonId: "core-bias-variance",
    title: "Bias vs variance",
    prompt: "Label each: (a) k-NN with k=1, (b) linear regression on highly non-linear data, (c) a very deep decision tree.",
    hints: ["Simple → high bias. Flexible → high variance.", "k=1 wraps the training set tightly."],
    solution: [
      { kind: "prose", text: "(a) Low bias, HIGH variance — perfectly fits training, wobbles wildly with new data." },
      { kind: "prose", text: "(b) HIGH bias, low variance — the model is too rigid for the underlying pattern." },
      { kind: "prose", text: "(c) Low bias, HIGH variance — deep trees overfit. Random forests mitigate this by averaging." },
    ],
  },
  {
    id: "core-loss-g1",
    lessonId: "core-loss",
    title: "Compute MSE and MAE",
    prompt: "For y = [1, 2, 3] and ŷ = [1, 2, 5], compute MSE and MAE by hand, then say which one is more affected by the outlier prediction.",
    hints: ["MSE squares; MAE doesn't.", "Mean of squared errors vs mean of absolute errors."],
    solution: [
      { kind: "prose", text: "Errors: 0, 0, 2. MAE = (0+0+2)/3 ≈ 0.67. MSE = (0+0+4)/3 ≈ 1.33." },
      { kind: "prose", text: "MSE is far more affected by the outlier because squaring magnifies the 2 into a 4. That's why MSE penalizes outliers more and MAE is more robust." },
    ],
  },
  {
    id: "core-metrics-g1",
    lessonId: "core-metrics",
    title: "Precision, recall, F1 by hand",
    prompt: "TP=80, FP=20, FN=10, TN=890. Compute accuracy, precision, recall, and F1. Then say which metric you'd optimize for fraud detection.",
    hints: ["Precision = TP/(TP+FP); Recall = TP/(TP+FN); F1 = 2PR/(P+R)."],
    solution: [
      { kind: "prose", text: "Accuracy = (80+890)/1000 = 97%. Precision = 80/100 = 0.80. Recall = 80/90 ≈ 0.889. F1 = 2·0.80·0.889/(0.80+0.889) ≈ 0.842." },
      { kind: "prose", text: "For fraud detection, recall is usually the priority: missing a fraud (false negative) is much costlier than investigating a false alarm. You'd tune the threshold to push recall up at the expense of some precision." },
    ],
  },
  {
    id: "core-gd-g1",
    lessonId: "core-gd",
    title: "Run gradient descent",
    prompt: "Minimize L(w) = (w - 5)² starting at w=0 with η=0.1 for 5 iterations. Show the value of w at each step.",
    hints: ["Gradient: dL/dw = 2(w - 5).", "Update: w ← w - η · grad."],
    solution: [
      { kind: "code", lang: "python", code: "w = 0\nfor _ in range(5):\n    grad = 2 * (w - 5)\n    w = w - 0.1 * grad\n    print(f\"{w:.3f}\")\n# 1.000, 1.800, 2.440, 2.952, 3.362" },
      { kind: "prose", text: "Each step nudges w toward 5. With more iterations it would converge close to 5." },
    ],
  },
  {
    id: "core-linreg-g1",
    lessonId: "core-linreg",
    title: "Fit and interpret a linear model",
    prompt: "Fit LinearRegression on a dataset with one feature. Print the slope and intercept, and describe how to interpret each in plain English.",
    hints: ["model.coef_ and model.intercept_ after fitting."],
    solution: [
      { kind: "code", lang: "python", code: "from sklearn.linear_model import LinearRegression\nmodel = LinearRegression().fit(X_train, y_train)\nprint(model.coef_[0], model.intercept_)" },
      { kind: "prose", text: "The slope is the average change in y when x increases by 1. The intercept is the predicted y when x = 0 (often not physically meaningful, but it sets the line's vertical position)." },
    ],
  },
  {
    id: "core-logreg-g1",
    lessonId: "core-logreg",
    title: "Probabilities, not just classes",
    prompt: "After fitting LogisticRegression, get the predicted probability of class 1 for the first 5 test examples and print them.",
    hints: ["`predict_proba(X)` returns a 2-column array; column index 1 is the prob of class 1."],
    solution: [
      { kind: "code", lang: "python", code: "proba = model.predict_proba(X_test)[:, 1]\nprint(proba[:5])" },
      { kind: "prose", text: "Working in probabilities lets you tune the decision threshold (e.g. classify as positive if p > 0.3 rather than 0.5) to trade off precision and recall." },
    ],
  },
  {
    id: "core-svm-g1",
    lessonId: "core-svm",
    title: "Why scale before SVM?",
    prompt: "Explain why an SVM trained on unscaled features (one in dollars, another in years) often does worse than the same SVM on scaled features.",
    hints: ["SVMs operate on distances in feature space.", "What happens if one feature has 1000x bigger numbers?"],
    solution: [
      { kind: "prose", text: "SVMs compare points via inner products / distances. If one feature ranges in the thousands and another in single digits, the bigger feature dominates the distance, and the smaller one is effectively ignored." },
      { kind: "prose", text: "Standardizing puts each feature on a comparable scale (mean 0, std 1), so all of them contribute fairly to the margin." },
    ],
  },
  {
    id: "core-trees-rf-g1",
    lessonId: "core-trees-rf",
    title: "Trees vs forests",
    prompt: "A single deep decision tree gets 100% train accuracy and 70% test. Switching to a random forest of 200 trees gives 95% train and 88% test. Why does the forest do better?",
    hints: ["Bias-variance tradeoff applies again.", "What does averaging many diverse models do?"],
    solution: [
      { kind: "prose", text: "A single deep tree has low bias but high variance: it memorizes training noise and generalizes poorly." },
      { kind: "prose", text: "A forest trains many trees on different bootstrap samples and feature subsets, then averages. The trees' errors partially cancel out, dramatically reducing variance while keeping bias low. Result: better generalization." },
    ],
  },
  {
    id: "core-knn-nb-g1",
    lessonId: "core-knn-nb",
    title: "Pick the right baseline",
    prompt: "For each task, recommend k-NN, Naive Bayes, or something else, with one-sentence justification: (a) spam classification with TF-IDF features, (b) classifying 10-D points where similar points clearly cluster, (c) high-dim image data.",
    hints: ["NB is fast and strong on text. k-NN works on small-d when distances are meaningful."],
    solution: [
      { kind: "prose", text: "(a) Naive Bayes (MultinomialNB) — it is fast and remarkably strong on TF-IDF text features." },
      { kind: "prose", text: "(b) k-NN — distances are meaningful and k-NN is a natural fit for clustered, low-dim data (with scaling)." },
      { kind: "prose", text: "(c) Neither — for high-dim images, distances become unreliable for k-NN and feature independence is laughable for NB. Use a CNN or classical model with carefully engineered features." },
    ],
  },
  {
    id: "core-kmeans-pca-g1",
    lessonId: "core-kmeans-pca",
    title: "Visualize with PCA",
    prompt: "You have data with 50 features and 3 known classes. Use PCA to project it into 2D so you can plot it and visually see whether the classes separate.",
    hints: ["Scale first. n_components=2.", "Scatter the 2D points, color by class."],
    solution: [
      { kind: "code", lang: "python", code: "from sklearn.preprocessing import StandardScaler\nfrom sklearn.decomposition import PCA\nimport matplotlib.pyplot as plt\n\nXs = StandardScaler().fit_transform(X)\nX2 = PCA(n_components=2).fit_transform(Xs)\nplt.scatter(X2[:, 0], X2[:, 1], c=y, cmap=\"tab10\")\nplt.show()" },
      { kind: "prose", text: "If the classes form visibly distinct clusters in 2D, almost any model will do well. Heavily overlapping clusters mean the task is genuinely hard." },
    ],
  },
  {
    id: "core-pipeline-g1",
    lessonId: "core-pipeline",
    title: "Pipeline + grid search",
    prompt: "Build a Pipeline of StandardScaler + LogisticRegression and grid-search the `C` hyperparameter over [0.01, 0.1, 1, 10] using 5-fold CV.",
    hints: ["Step name is `clf`, so param key is `clf__C`."],
    solution: [
      { kind: "code", lang: "python", code: "from sklearn.pipeline import Pipeline\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.model_selection import GridSearchCV\n\npipe = Pipeline([(\"scaler\", StandardScaler()), (\"clf\", LogisticRegression(max_iter=1000))])\ngrid = GridSearchCV(pipe, {\"clf__C\": [0.01, 0.1, 1, 10]}, cv=5)\ngrid.fit(X_train, y_train)\nprint(grid.best_params_, grid.best_score_)" },
      { kind: "prose", text: "The pipeline + grid CV is the standard, leakage-safe way to tune classical models." },
    ],
  },
  {
    id: "core-projects-g1",
    lessonId: "core-projects",
    title: "Plan one portfolio project",
    prompt: "Pick one project from the list (e.g. heart disease prediction) and write a one-page outline: problem, data, success metric, planned algorithms to compare, and how you'll evaluate.",
    hints: ["Define success up front.", "Plan 2-3 candidate algorithms, not 10."],
    solution: [
      { kind: "prose", text: "Heart disease prediction. Binary classification. Data: UCI heart disease dataset. Success metric: F1 + ROC-AUC (medical context, imbalance matters)." },
      { kind: "prose", text: "Candidates: LogisticRegression (baseline), RandomForest, gradient boosting. Evaluation: stratified 5-fold CV inside a Pipeline (scaling + model), then final test score on a held-out 20% split. Report confusion matrix and feature importances." },
    ],
  },
];
