import type { Track, GuidedProblem } from "@/content/types";

export const deepLearningTrack: Track = {
  id: "ml-deep",
  title: "Deep Learning",
  modules: [
    {
      id: "dl-nn",
      title: "Neural network foundations",
      lessons: [
        {
          id: "dl-neurons",
          title: "Neurons & layers",
          summary: "The building block — a weighted sum + activation.",
          blocks: [
            { kind: "prose", text: "A neural network is built from neurons. A single neuron computes a weighted sum of inputs, adds a bias, and applies a nonlinear activation function. Stack many neurons in layers, and you have a network that can represent extraordinarily complex functions." },
            { kind: "heading", text: "One neuron" },
            { kind: "code", lang: "text", code: "Inputs x₁, x₂, ..., xₙ\nWeights w₁, w₂, ..., wₙ + bias b\nScore z = w₁x₁ + w₂x₂ + ... + wₙxₙ + b\nOutput a = activation(z)" },
            { kind: "heading", text: "Activation functions" },
            { kind: "prose", text: "Without a nonlinearity, stacking layers collapses into a single linear function. Three common choices:" },
            { kind: "code", lang: "text", code: "Sigmoid: σ(z) = 1 / (1 + e^-z)   range (0, 1) — classic, saturates\nTanh:    tanh(z)                  range (-1, 1)\nReLU:    max(0, z)                 the default in modern networks" },
            { kind: "heading", text: "Layers" },
            { kind: "prose", text: "A fully-connected (dense) layer applies one matrix multiplication: z = Wx + b, then an activation. Input layer → hidden layers → output layer." },
            { kind: "code", lang: "python", code: "import numpy as np\nx = np.array([1.0, 2.0])\nW = np.array([[0.5, -0.2], [0.3, 0.1]])\nb = np.array([0.1, -0.1])\nz = W @ x + b\na = np.maximum(0, z)         # ReLU\nprint(a)                     # [0.2 0.4]" },
            { kind: "callout", tone: "tip", text: "Why ReLU? It's simple to compute, has no saturation for positive inputs, and gradients flow cleanly. It's the default for hidden layers; sigmoid/softmax are for outputs." },
            { kind: "keypoints", points: ["A neuron: z = w·x + b, then a = activation(z)", "Without nonlinearity, deep networks collapse to one linear layer", "ReLU is the default activation for hidden layers", "Sigmoid (binary) and softmax (multiclass) for the output", "A dense layer is one matrix multiply + activation"] },
            { kind: "practice", text: "Compute by hand:", items: ["For x=[2,3], W=[[1,0],[0,1]], b=[0,0], compute z and ReLU(z).", "Why does ReLU avoid the 'vanishing gradient' issue of sigmoid for positive z?", "What activation belongs on the output of a binary classifier?", "Stretch: what activation for a 5-class classifier?"] },
          ],
        },
        {
          id: "dl-forward-loss",
          title: "Forward pass & loss",
          summary: "Push inputs through the network, then score how wrong it was.",
          blocks: [
            { kind: "prose", text: "The forward pass runs an input through every layer to produce a prediction. The loss compares that prediction to the truth and produces a single number to minimize." },
            { kind: "heading", text: "A two-layer forward pass" },
            { kind: "code", lang: "python", code: "import numpy as np\n\ndef relu(x):\n    return np.maximum(0, x)\n\ndef softmax(x):\n    e = np.exp(x - x.max())\n    return e / e.sum()\n\n# Inputs\nx = np.array([1.0, 0.5])\n# Layer 1\nW1 = np.random.randn(4, 2) * 0.1\nb1 = np.zeros(4)\nh = relu(W1 @ x + b1)\n# Layer 2 (output, 3 classes)\nW2 = np.random.randn(3, 4) * 0.1\nb2 = np.zeros(3)\nlogits = W2 @ h + b2\nprobs = softmax(logits)\nprint(probs)" },
            { kind: "heading", text: "Loss choices" },
            { kind: "prose", text: "Binary classification: binary cross-entropy on a sigmoid output. Multi-class: categorical cross-entropy on a softmax output. Regression: MSE on a linear output." },
            { kind: "code", lang: "python", code: "# Categorical cross-entropy for one example\ndef ce_loss(probs, y_true_idx):\n    return -np.log(probs[y_true_idx] + 1e-12)\nprint(ce_loss(probs, 0))" },
            { kind: "keypoints", points: ["Forward pass: input → hidden layers → output", "Use softmax (multi-class) or sigmoid (binary) at the output", "Loss = single number to minimize", "Cross-entropy for classification, MSE for regression", "Add a tiny epsilon to avoid log(0)"] },
            { kind: "practice", text: "Forward + loss:", items: ["Write a forward pass for a 2-layer network with ReLU + softmax.", "Compute categorical cross-entropy for a 3-class softmax output [0.7, 0.2, 0.1] when the true class is 0.", "What loss for a binary classifier?", "Stretch: why subtract x.max() before exp in softmax?"] },
          ],
        },
        {
          id: "dl-backprop",
          title: "Backpropagation",
          summary: "The chain rule of calculus running in reverse through the network.",
          blocks: [
            { kind: "prose", text: "Backprop computes the gradient of the loss with respect to every weight by applying the chain rule from output back to input. It's the algorithm that makes deep learning possible." },
            { kind: "heading", text: "The intuition" },
            { kind: "prose", text: "For each weight w, you want ∂L/∂w. By the chain rule, this is a product of local derivatives along the path from w to the loss. Backprop computes all these gradients in one efficient backward pass." },
            { kind: "heading", text: "Forward → backward" },
            { kind: "code", lang: "text", code: "Forward (compute & cache):     x → z₁ → a₁ → z₂ → a₂ → L\nBackward (compute gradients):  ∂L/∂a₂ → ∂L/∂z₂ → ∂L/∂W₂\n                                 ∂L/∂a₁ → ∂L/∂z₁ → ∂L/∂W₁" },
            { kind: "heading", text: "Why we use autograd" },
            { kind: "prose", text: "Writing backprop by hand for every architecture is tedious and error-prone. PyTorch and TensorFlow do it automatically — you define the forward pass and the framework computes gradients via the computation graph." },
            { kind: "callout", tone: "warn", text: "Two common gradient issues: vanishing (gradients shrink to ~0 through many layers, training stalls) and exploding (gradients grow huge, weights diverge). ReLU + careful initialization + batch normalization tame both." },
            { kind: "keypoints", points: ["Backprop = chain rule applied backward through the network", "Computes ∂L/∂w for every parameter w", "Forward pass caches values; backward pass uses them for gradients", "Autograd (PyTorch/TF) automates backprop", "Watch for vanishing and exploding gradients in deep nets"] },
            { kind: "practice", text: "Understand backprop:", items: ["State the chain rule in one sentence.", "Why is forward-pass caching needed for the backward pass?", "Why do very deep networks suffer from vanishing gradients with sigmoid?", "Stretch: how does residual (skip) connections help?"] },
          ],
        },
        {
          id: "dl-optimizers",
          title: "Optimizers, epochs, batches",
          summary: "Tools and knobs that actually drive training.",
          blocks: [
            { kind: "prose", text: "Choosing the right optimizer and training schedule matters as much as the model itself. Here's the practical vocabulary." },
            { kind: "heading", text: "Optimizers" },
            { kind: "prose", text: "SGD: vanilla gradient descent on mini-batches. SGD with momentum: smooths updates by keeping a moving average — moves faster through flat regions. Adam: per-parameter adaptive learning rates with momentum — the default for deep learning." },
            { kind: "heading", text: "Epochs and batches" },
            { kind: "code", lang: "text", code: "Batch size  = how many examples per gradient step (32, 64, 256 typical)\nIteration   = one gradient step\nEpoch       = one full pass over the training set\n\nIf dataset has 50000 examples & batch=64:\n  iterations per epoch = 50000 / 64 ≈ 782" },
            { kind: "heading", text: "Learning rate" },
            { kind: "prose", text: "The single most impactful hyperparameter. Common values: 1e-3 for Adam, 1e-2 for SGD. Schedulers reduce it over time for cleaner convergence." },
            { kind: "code", lang: "python", code: "# PyTorch sketch\noptimizer = torch.optim.Adam(model.parameters(), lr=1e-3)\nfor epoch in range(epochs):\n    for batch in loader:\n        optimizer.zero_grad()\n        loss = loss_fn(model(batch.x), batch.y)\n        loss.backward()\n        optimizer.step()" },
            { kind: "callout", tone: "tip", text: "Default starting recipe: Adam, lr=1e-3, batch size 32-128, watch loss curves. If it diverges, lower lr 10x. If it crawls, raise lr or batch size." },
            { kind: "keypoints", points: ["SGD with momentum or Adam are the standard optimizers", "Adam with lr=1e-3 is the typical default", "Batch size: how many examples per gradient step", "Epoch: one full pass through training data", "Watch train + validation loss curves each epoch"] },
            { kind: "practice", text: "Plan a training run:", items: ["With 100k examples and batch=128, how many iterations per epoch?", "Why might Adam beat SGD on early experiments?", "What is the first thing to try if the loss explodes?", "Stretch: write out the standard PyTorch training-step pattern (5 lines)."] },
          ],
        },
      ],
    },
    {
      id: "dl-pytorch",
      title: "PyTorch & architectures",
      lessons: [
        {
          id: "dl-pytorch-basics",
          title: "PyTorch fundamentals",
          summary: "Tensors, autograd, and the standard training loop.",
          blocks: [
            { kind: "prose", text: "PyTorch is the dominant deep learning framework for research and increasingly production. Three core ideas: tensors, autograd, and modules." },
            { kind: "heading", text: "Tensors" },
            { kind: "prose", text: "PyTorch tensors are NumPy-like arrays that can live on a GPU and track gradients. The API mirrors NumPy almost one-to-one." },
            { kind: "code", lang: "python", code: "import torch\nx = torch.tensor([[1.0, 2.0], [3.0, 4.0]])\nprint(x.shape, x.dtype, x.device)\ny = x @ x.T\nprint(y)" },
            { kind: "heading", text: "Autograd" },
            { kind: "prose", text: "Tag a tensor with `requires_grad=True` and PyTorch builds a computation graph as you operate. Call `.backward()` and gradients are computed automatically." },
            { kind: "code", lang: "python", code: "w = torch.tensor(2.0, requires_grad=True)\nL = (w - 5) ** 2\nL.backward()\nprint(w.grad)   # 2*(w-5) = -6.0" },
            { kind: "heading", text: "A tiny model" },
            { kind: "code", lang: "python", code: "import torch.nn as nn\n\nclass Net(nn.Module):\n    def __init__(self):\n        super().__init__()\n        self.l1 = nn.Linear(2, 16)\n        self.l2 = nn.Linear(16, 1)\n    def forward(self, x):\n        return self.l2(torch.relu(self.l1(x)))" },
            { kind: "heading", text: "The training loop" },
            { kind: "code", lang: "python", code: "model = Net()\nopt = torch.optim.Adam(model.parameters(), lr=1e-3)\nloss_fn = nn.MSELoss()\n\nfor epoch in range(100):\n    opt.zero_grad()\n    yhat = model(X)\n    loss = loss_fn(yhat, y)\n    loss.backward()\n    opt.step()" },
            { kind: "callout", tone: "warn", text: "Always call `optimizer.zero_grad()` before `.backward()`. Otherwise PyTorch accumulates gradients across iterations, and your model misbehaves silently." },
            { kind: "keypoints", points: ["Tensors are GPU-capable, autograd-aware NumPy arrays", "Set requires_grad=True to track gradients", "`.backward()` computes gradients via autograd", "Build models by subclassing `nn.Module`", "Loop: zero_grad → forward → loss → backward → step"] },
            { kind: "practice", text: "Use PyTorch:", items: ["Create a tensor and compute its mean.", "Define a 2-layer MLP with nn.Linear.", "Write the 5-line training loop.", "Stretch: move tensors to a GPU with `.cuda()` (or `.to('cuda')`)."] },
          ],
        },
        {
          id: "dl-cnn",
          title: "Convolutional networks",
          summary: "The architecture for images: shared weights and local receptive fields.",
          blocks: [
            { kind: "prose", text: "CNNs revolutionized computer vision by encoding two priors directly into the architecture: (1) local features matter (a corner is a corner regardless of position), and (2) features detected anywhere should use the same weights." },
            { kind: "heading", text: "Convolution" },
            { kind: "prose", text: "A small filter (e.g. 3x3) slides over the image, computing a dot product at each position. The same filter is used everywhere, dramatically reducing parameters versus a dense layer." },
            { kind: "heading", text: "Pooling" },
            { kind: "prose", text: "Max-pooling shrinks spatial dimensions by taking the max in small windows. Reduces compute and adds slight translation invariance." },
            { kind: "heading", text: "Typical architecture" },
            { kind: "code", lang: "text", code: "Image (224x224x3)\n  → Conv(64) → ReLU → MaxPool\n  → Conv(128) → ReLU → MaxPool\n  → Conv(256) → ReLU → MaxPool\n  → Flatten → Dense(1024) → Dense(num_classes)\n\nEarly layers learn edges; middle layers learn parts; deep layers learn objects." },
            { kind: "code", lang: "python", code: "import torch.nn as nn\n\nclass SmallCNN(nn.Module):\n    def __init__(self, num_classes=10):\n        super().__init__()\n        self.features = nn.Sequential(\n            nn.Conv2d(3, 32, 3, padding=1), nn.ReLU(), nn.MaxPool2d(2),\n            nn.Conv2d(32, 64, 3, padding=1), nn.ReLU(), nn.MaxPool2d(2),\n        )\n        self.head = nn.Sequential(\n            nn.Flatten(),\n            nn.Linear(64 * 8 * 8, 128), nn.ReLU(),\n            nn.Linear(128, num_classes),\n        )\n    def forward(self, x):\n        return self.head(self.features(x))" },
            { kind: "callout", tone: "tip", text: "In real projects, you almost never train a CNN from scratch. Use a pretrained backbone (ResNet, EfficientNet) from torchvision and fine-tune the last layers. This is called transfer learning." },
            { kind: "keypoints", points: ["Convolutions share weights across positions — far fewer parameters than dense", "Filters detect local features; deeper layers compose them", "Pooling shrinks spatial size and adds translation tolerance", "Conv → pool → conv → pool → dense head is the classic recipe", "Transfer learning from pretrained models beats training from scratch"] },
            { kind: "practice", text: "CNN intuition:", items: ["Why does sharing weights cut parameter count dramatically?", "What does max-pool(2) do to a 32x32 image?", "Why are CNNs better than dense networks for images?", "Stretch: what is transfer learning and why does it work?"] },
          ],
        },
        {
          id: "dl-rnn-lstm",
          title: "RNNs & LSTMs",
          summary: "Sequences and the hidden state that remembers.",
          blocks: [
            { kind: "prose", text: "RNNs process sequences (sentences, time series, audio) one element at a time, maintaining a hidden state that carries information forward. LSTMs are RNNs with gating that handles long-range dependencies better." },
            { kind: "heading", text: "Vanilla RNN" },
            { kind: "code", lang: "text", code: "h_t = tanh(W_xh · x_t + W_hh · h_{t-1} + b)\ny_t = W_hy · h_t" },
            { kind: "prose", text: "Each step combines the new input with the previous hidden state. The hidden state is the network's memory." },
            { kind: "heading", text: "LSTM" },
            { kind: "prose", text: "Long Short-Term Memory adds three gates — input, forget, output — that learn what to write to memory, what to erase, and what to read. This solves vanilla RNNs' tendency to forget long-range context." },
            { kind: "code", lang: "python", code: "import torch.nn as nn\nlstm = nn.LSTM(input_size=64, hidden_size=128, num_layers=1, batch_first=True)\n# x shape: (batch, seq_len, input_size)\nout, (h, c) = lstm(x)" },
            { kind: "callout", tone: "note", text: "RNNs and LSTMs dominated NLP for a decade. Today, transformers (next lesson) have largely replaced them, but RNNs are still useful for small models and streaming inputs." },
            { kind: "keypoints", points: ["RNNs process sequences one step at a time using a hidden state", "Vanilla RNNs struggle with long-range dependencies", "LSTMs use gates (input/forget/output) to remember long-range info", "Modern NLP has largely shifted to transformers", "Still useful for small, streaming, or edge applications"] },
            { kind: "practice", text: "Sequence models:", items: ["Why can't a dense network handle variable-length sequences?", "What does an LSTM's 'forget gate' do conceptually?", "What is the role of the hidden state in an RNN?", "Stretch: why are transformers more parallelizable than RNNs?"] },
          ],
        },
        {
          id: "dl-transformers",
          title: "Transformers & attention",
          summary: "The architecture behind every modern LLM.",
          blocks: [
            { kind: "prose", text: "Transformers replaced RNNs as the dominant sequence architecture because they parallelize cleanly and capture long-range dependencies through attention. Every modern LLM (GPT, Claude, Llama) is a transformer." },
            { kind: "heading", text: "Self-attention" },
            { kind: "prose", text: "For each token, compute a query (Q), key (K), and value (V) vector. The token's new representation is a weighted sum of all tokens' values, where the weights come from how much each token's K matches this token's Q." },
            { kind: "code", lang: "text", code: "Attention(Q, K, V) = softmax(QKᵀ / √d_k) · V\n\nFor each token:\n  1. Compute similarity to every other token (QKᵀ)\n  2. Softmax → attention weights\n  3. Weighted sum of values" },
            { kind: "heading", text: "Multi-head attention" },
            { kind: "prose", text: "Run several attention heads in parallel, each learning different relationships (e.g. one tracks syntax, another tracks topic). Concatenate and project." },
            { kind: "heading", text: "Transformer block" },
            { kind: "code", lang: "text", code: "x → MultiHeadAttention → + residual → LayerNorm\n  → Feed-Forward (2 dense layers) → + residual → LayerNorm" },
            { kind: "prose", text: "Stack many of these blocks (12 for BERT, 96+ for big GPTs). Add positional encodings so the model knows token order, since attention is permutation-invariant." },
            { kind: "callout", tone: "tip", text: "Conceptually: each token asks 'which other tokens matter for me right now?' and gathers information from them. That's the whole magic." },
            { kind: "keypoints", points: ["Self-attention: each token gathers info from all others, weighted by relevance", "Multi-head attention runs several attention modules in parallel", "Transformer block: attention + feed-forward, both with residuals + LayerNorm", "Positional encoding tells the model the order of tokens", "Every modern LLM is a deep stack of transformer blocks"] },
            { kind: "practice", text: "Understand attention:", items: ["In the formula softmax(QKᵀ/√d_k)·V, what does softmax(QKᵀ/√d_k) represent?", "Why divide by √d_k inside the softmax?", "Why are positional encodings necessary?", "Stretch: why are transformers more parallelizable than RNNs in training?"] },
          ],
        },
      ],
    },
  ],
};

export const deepLearningGuided: GuidedProblem[] = [
  {
    id: "dl-neurons-g1",
    lessonId: "dl-neurons",
    title: "One neuron, one layer",
    prompt: "For input x = [1, 2], weight matrix W = [[0.5, -0.5], [1, 1]], bias b = [0, 0.5], compute z = Wx + b and then ReLU(z).",
    hints: ["Matrix-vector multiplication then add bias.", "ReLU clips negatives to 0."],
    solution: [
      { kind: "code", lang: "python", code: "import numpy as np\nW = np.array([[0.5, -0.5], [1, 1]])\nb = np.array([0, 0.5])\nx = np.array([1, 2])\nz = W @ x + b              # [-0.5, 3.5]\na = np.maximum(0, z)       # [0.0, 3.5]\nprint(z, a)" },
      { kind: "prose", text: "ReLU zeroed out the negative entry. That's the nonlinearity making the network non-trivial." },
    ],
  },
  {
    id: "dl-forward-loss-g1",
    lessonId: "dl-forward-loss",
    title: "Cross-entropy by hand",
    prompt: "A softmax produced probabilities [0.7, 0.2, 0.1] for classes [0, 1, 2]. The true class is 0. Compute the categorical cross-entropy loss.",
    hints: ["L = -log(p_true_class).", "Use np.log."],
    solution: [
      { kind: "code", lang: "python", code: "import numpy as np\np = np.array([0.7, 0.2, 0.1])\ny = 0\nprint(-np.log(p[y]))   # 0.357" },
      { kind: "prose", text: "A confident, correct prediction gives a small loss (~0.36). If p[0] had been 0.1, the loss would have been ~2.3." },
    ],
  },
  {
    id: "dl-backprop-g1",
    lessonId: "dl-backprop",
    title: "Chain-rule reasoning",
    prompt: "If L = (a - 5)² and a = 2x + 3, use the chain rule to compute dL/dx at x = 1.",
    hints: ["dL/da = 2(a-5). da/dx = 2.", "Multiply them."],
    solution: [
      { kind: "prose", text: "At x = 1: a = 2·1 + 3 = 5. dL/da = 2·(5-5) = 0. dL/dx = 0 · 2 = 0." },
      { kind: "prose", text: "x = 1 happens to be the minimum. The gradient correctly is 0 there." },
    ],
  },
  {
    id: "dl-optimizers-g1",
    lessonId: "dl-optimizers",
    title: "Iterations per epoch",
    prompt: "With 100,000 training examples and batch size 256, how many iterations per epoch? And if you train 10 epochs, how many gradient steps total?",
    hints: ["Iterations per epoch = examples / batch.", "Multiply by epoch count."],
    solution: [
      { kind: "prose", text: "Iterations per epoch = 100,000 / 256 ≈ 391 (the last batch may be smaller). Total over 10 epochs ≈ 3,910 gradient steps." },
    ],
  },
  {
    id: "dl-pytorch-basics-g1",
    lessonId: "dl-pytorch-basics",
    title: "A two-layer net in PyTorch",
    prompt: "Define a PyTorch model with two linear layers (input dim 4, hidden 16, output 3) and ReLU in between.",
    hints: ["Subclass nn.Module.", "nn.Linear(in, out)."],
    solution: [
      { kind: "code", lang: "python", code: "import torch.nn as nn, torch\nclass Net(nn.Module):\n    def __init__(self):\n        super().__init__()\n        self.l1 = nn.Linear(4, 16)\n        self.l2 = nn.Linear(16, 3)\n    def forward(self, x):\n        return self.l2(torch.relu(self.l1(x)))\n\nmodel = Net()\nprint(model(torch.randn(2, 4)).shape)   # torch.Size([2, 3])" },
    ],
  },
  {
    id: "dl-cnn-g1",
    lessonId: "dl-cnn",
    title: "Why CNN over dense for images",
    prompt: "A 224x224 RGB image has 150,528 input features. A dense layer with 1000 units would have ~150 million parameters just to start. Why does a CNN drastically reduce that, and why does it generalize better?",
    hints: ["Weight sharing.", "Local receptive fields."],
    solution: [
      { kind: "prose", text: "A convolution shares one small filter (e.g. 3x3x3 = 27 weights) across the entire image, so a 64-filter conv layer has only ~1,800 parameters regardless of image size, instead of 150M for dense." },
      { kind: "prose", text: "This also encodes a useful prior: a corner or edge detector should work the same way no matter where in the image the feature appears. Fewer parameters + the right inductive bias = better generalization." },
    ],
  },
  {
    id: "dl-rnn-lstm-g1",
    lessonId: "dl-rnn-lstm",
    title: "Where vanilla RNNs struggle",
    prompt: "Explain why a vanilla RNN often fails to learn 'the sentence ended with a question mark' for a long input sentence, and how LSTMs help.",
    hints: ["Think about gradients backpropagating through many time steps.", "LSTM gating."],
    solution: [
      { kind: "prose", text: "In a vanilla RNN, gradients have to propagate back through every time step, getting multiplied at each one. They tend to shrink toward zero (vanish), so the network never learns to associate distant tokens." },
      { kind: "prose", text: "LSTMs add a cell state with gates that decide what to keep and what to forget. The cell state has a near-linear path back through time, so gradients can flow further. Long-range dependencies become learnable." },
    ],
  },
  {
    id: "dl-transformers-g1",
    lessonId: "dl-transformers",
    title: "Attention weights",
    prompt: "In attention, softmax(QKᵀ / √d_k) yields a matrix. What does each row represent, and why do we divide by √d_k?",
    hints: ["Each row is one token's distribution.", "Without scaling, dot products grow with d_k."],
    solution: [
      { kind: "prose", text: "Each row is one token's attention distribution over all tokens: 'how much do I attend to each other token?'. Multiplying by V gives that token's new representation as a weighted sum of all values." },
      { kind: "prose", text: "Without dividing by √d_k, dot products grow as d_k grows, pushing softmax into saturation (one near-1, rest near-0), which kills gradients. Scaling by √d_k keeps the distribution moderate, gradients flow, training works." },
    ],
  },
];
