import type { Track, GuidedProblem } from "@/content/types";

export const mathTrack: Track = {
  id: "ml-math",
  title: "Mathematics for ML",
  modules: [
    {
      id: "math-linalg",
      title: "Linear algebra",
      lessons: [
        {
          id: "math-vectors",
          title: "Vectors",
          summary: "Ordered lists of numbers — the basic object of ML.",
          blocks: [
            { kind: "prose", text: "A vector is an ordered list of numbers. In ML, every example you feed a model is a vector: pixel intensities of an image, fields of a row in a table, or coordinates in some space the model invented." },
            { kind: "heading", text: "Notation" },
            { kind: "prose", text: "Write a vector as a bold lowercase letter: **v** = [v₁, v₂, ..., vₙ]. Its dimension is n. In NumPy it is just a 1D array." },
            { kind: "code", lang: "python", code: "import numpy as np\nv = np.array([3, 4])         # 2D vector\nw = np.array([1, 2, 3, 4])   # 4D vector\nprint(v.shape)               # (2,)" },
            { kind: "heading", text: "Magnitude (length)" },
            { kind: "prose", text: "The length of a vector is ||v|| = √(v₁² + v₂² + ... + vₙ²). For [3, 4] that's √(9 + 16) = 5. This is the Euclidean norm." },
            { kind: "code", lang: "python", code: "print(np.linalg.norm(v))   # 5.0" },
            { kind: "heading", text: "Unit vectors" },
            { kind: "prose", text: "Dividing a vector by its magnitude gives a unit vector (length 1) pointing the same direction. Normalization shows up everywhere: cosine similarity, gradient steps, embeddings." },
            { kind: "code", lang: "python", code: "u = v / np.linalg.norm(v)\nprint(u)                       # [0.6 0.8]\nprint(np.linalg.norm(u))       # 1.0" },
            { kind: "callout", tone: "tip", text: "Think of an n-dimensional vector geometrically as an arrow in n-D space from the origin to its coordinates. Most ML intuitions come from this picture." },
            { kind: "keypoints", points: ["A vector is an ordered list of n numbers", "Magnitude ||v|| = √(Σ vᵢ²), the Euclidean norm", "Unit vector = v / ||v||, same direction, length 1", "Every example fed to a model is a vector", "NumPy 1D arrays represent vectors"] },
            { kind: "practice", text: "Vector basics:", items: ["Compute the magnitude of [3, 4, 12] by hand, then verify with NumPy.", "Normalize [6, 8] to a unit vector.", "What is the dimension of [1, 2, 3, 4, 5]?", "Stretch: why is the unit vector of [0, 0] undefined?"] },
          ],
        },
        {
          id: "math-vector-ops",
          title: "Vector operations",
          summary: "Addition, scalar multiplication, dot and cross product.",
          blocks: [
            { kind: "prose", text: "Four operations come up constantly: addition, scalar multiplication, the dot product, and (for 3D) the cross product." },
            { kind: "heading", text: "Addition & scalar multiplication" },
            { kind: "prose", text: "Add vectors element-wise: [1,2] + [3,4] = [4,6]. Scalar × vector multiplies every element: 3 · [1,2] = [3,6]." },
            { kind: "code", lang: "python", code: "a = np.array([1, 2])\nb = np.array([3, 4])\nprint(a + b)     # [4 6]\nprint(3 * a)     # [3 6]" },
            { kind: "heading", text: "Dot product" },
            { kind: "prose", text: "The dot product is a · b = a₁b₁ + a₂b₂ + ... + aₙbₙ. It returns a single number. Geometrically a · b = ||a|| · ||b|| · cos(θ), where θ is the angle between them." },
            { kind: "code", lang: "python", code: "a = np.array([1, 2, 3])\nb = np.array([4, 5, 6])\nprint(a @ b)            # 32 = 1·4 + 2·5 + 3·6\nprint(np.dot(a, b))     # 32" },
            { kind: "prose", text: "Why it matters: the dot product appears in nearly every ML formula. It measures how aligned two vectors are. Zero means perpendicular; positive means same direction; negative means opposing." },
            { kind: "heading", text: "Cosine similarity" },
            { kind: "prose", text: "cos(θ) = (a · b) / (||a|| · ||b||). Used everywhere in semantic search and embeddings — how similar are two documents, or two word vectors?" },
            { kind: "code", lang: "python", code: "def cosine(a, b):\n    return (a @ b) / (np.linalg.norm(a) * np.linalg.norm(b))" },
            { kind: "heading", text: "Cross product (3D only)" },
            { kind: "prose", text: "For 3D vectors, a × b returns a vector perpendicular to both. Used in physics and 3D graphics, less common in ML." },
            { kind: "keypoints", points: ["Addition is element-wise; scalar × vector scales every element", "Dot product a · b = Σ aᵢbᵢ, returns a scalar", "a · b = ||a|| ||b|| cos(θ) — measures alignment", "Cosine similarity normalizes the dot product into [-1, 1]", "The dot product is the heart of nearly every ML formula"] },
            { kind: "practice", text: "Compute by hand and check:", items: ["[1, 2] + [3, 4] = ?", "[1, 2, 3] · [4, 5, 6] = ?", "Are [1, 0] and [0, 1] perpendicular? Show with the dot product.", "Stretch: cosine similarity between [1, 1] and [1, -1]?"] },
          ],
        },
        {
          id: "math-matrices",
          title: "Matrices",
          summary: "2D arrays of numbers — how ML models actually compute.",
          blocks: [
            { kind: "prose", text: "A matrix is a rectangular grid of numbers with rows and columns. Almost all ML computation is matrix multiplication: a batch of inputs (matrix) multiplied by the model's parameters (matrix) gives outputs." },
            { kind: "heading", text: "Notation & shape" },
            { kind: "prose", text: "An m×n matrix has m rows and n columns. Write A[i,j] for the entry in row i, column j." },
            { kind: "code", lang: "python", code: "A = np.array([\n    [1, 2, 3],\n    [4, 5, 6],\n])\nprint(A.shape)    # (2, 3)\nprint(A[0, 1])    # 2" },
            { kind: "heading", text: "Transpose" },
            { kind: "prose", text: "A.T swaps rows and columns. An m×n matrix becomes n×m." },
            { kind: "code", lang: "python", code: "print(A.T)\n# [[1 4]\n#  [2 5]\n#  [3 6]]" },
            { kind: "heading", text: "Special matrices" },
            { kind: "prose", text: "The identity matrix I has 1s on the diagonal, 0s elsewhere. AI = A for any A. The zero matrix has 0 everywhere." },
            { kind: "code", lang: "python", code: "I = np.eye(3)         # 3x3 identity\nZ = np.zeros((2, 4))  # 2x4 zeros" },
            { kind: "heading", text: "Inverse & determinant" },
            { kind: "prose", text: "If A is square and 'well-behaved', its inverse A⁻¹ satisfies A · A⁻¹ = I. The determinant is a single number that tells you if A is invertible (nonzero = invertible). These come up in linear regression's closed-form solution." },
            { kind: "code", lang: "python", code: "B = np.array([[2, 1], [1, 3]])\nprint(np.linalg.det(B))    # 5.0\nprint(np.linalg.inv(B))" },
            { kind: "keypoints", points: ["A matrix has m rows × n columns", "A.T (transpose) swaps rows and columns", "Identity I: 1s on diagonal, A · I = A", "A⁻¹ inverse exists if det(A) ≠ 0 (square matrix)", "ML computations are mostly matrix multiplications"] },
            { kind: "practice", text: "Matrix basics:", items: ["Build a 3x2 matrix and print its shape.", "Transpose it and confirm the new shape is 2x3.", "What does `np.eye(4)` produce?", "Stretch: compute the determinant of [[1, 2], [3, 4]] by hand (= 1·4 - 2·3 = -2)."] },
          ],
        },
        {
          id: "math-matrix-ops",
          title: "Matrix operations",
          summary: "Addition, scalar multiplication, and the all-important matmul.",
          blocks: [
            { kind: "prose", text: "Matrix multiplication is *the* operation in ML. A neural network forward pass is a sequence of matmuls interleaved with activations. Understand it, and the machinery clicks." },
            { kind: "heading", text: "Addition & scaling" },
            { kind: "prose", text: "Element-wise like vectors. A + B requires identical shapes; cA multiplies every entry by c." },
            { kind: "heading", text: "Matrix multiplication" },
            { kind: "prose", text: "For A of shape m×k and B of shape k×n, AB is m×n, where (AB)[i,j] = sum over r of A[i,r] · B[r,j]. Said simply: each entry of AB is the dot product of a row of A with a column of B." },
            { kind: "code", lang: "python", code: "A = np.array([[1, 2], [3, 4]])     # 2x2\nB = np.array([[5, 6], [7, 8]])     # 2x2\nprint(A @ B)\n# [[19 22]\n#  [43 50]]\n# (AB)[0,0] = 1·5 + 2·7 = 19" },
            { kind: "callout", tone: "warn", text: "Shape rule: the inner dimensions must match. A (m×k) @ B (k×n) works; A (m×k) @ B (n×k) does not. Matmul is NOT commutative: AB ≠ BA in general." },
            { kind: "heading", text: "Why it matters" },
            { kind: "prose", text: "A linear model y = Xw computes predictions for all rows in one matmul: X is n×d (n examples, d features), w is d×1 (weights), result is n×1 (predictions). The same shape rule is the backbone of every layer in a neural network." },
            { kind: "heading", text: "Element-wise vs matmul" },
            { kind: "prose", text: "`A * B` (element-wise) is not `A @ B` (matrix product). Confusing them is a constant source of bugs." },
            { kind: "code", lang: "python", code: "print(A * B)   # element-wise\nprint(A @ B)   # matrix multiplication" },
            { kind: "keypoints", points: ["(m×k) @ (k×n) = (m×n) — inner dims must match", "Each output entry = dot product of a row with a column", "Matmul is NOT commutative: AB ≠ BA in general", "A linear model `y = Xw` is one matmul", "`A * B` is element-wise; `A @ B` is matrix product"] },
            { kind: "practice", text: "Multiply matrices:", items: ["What shape results from a 4x3 matrix @ a 3x5 matrix?", "Compute [[1, 2], [3, 4]] @ [[5], [6]] by hand and check.", "Why does (2x3) @ (4x2) fail?", "Stretch: prove that A · I = A using a 2x2 example."] },
          ],
        },
      ],
    },
    {
      id: "math-stats",
      title: "Statistics",
      lessons: [
        {
          id: "math-desc-inf",
          title: "Descriptive vs inferential statistics",
          summary: "Summarize a dataset, or draw conclusions about a population.",
          blocks: [
            { kind: "prose", text: "Statistics splits into two jobs: describe the data you have, or use it to infer something about a larger population you cannot fully observe." },
            { kind: "heading", text: "Descriptive" },
            { kind: "prose", text: "Numerical summaries of your dataset: mean, median, mode, range, variance, standard deviation, percentiles. Plus visual summaries: histograms, boxplots." },
            { kind: "code", lang: "python", code: "import numpy as np\nx = np.array([2, 4, 4, 4, 5, 5, 7, 9])\nprint(np.mean(x), np.median(x), np.std(x))   # 5.0  4.5  2.0" },
            { kind: "heading", text: "Inferential" },
            { kind: "prose", text: "You measure a sample (say 1000 voters) and infer something about the population (a country of millions). Hypothesis tests, confidence intervals, and p-values are inferential tools." },
            { kind: "callout", tone: "tip", text: "ML evaluation is half inferential statistics: your test accuracy is a sample estimate of how the model would perform on the unseen population of all possible inputs." },
            { kind: "keypoints", points: ["Descriptive: summarize the data you have", "Inferential: draw conclusions about a larger population from a sample", "Mean, median, std are descriptive", "Hypothesis tests, p-values, confidence intervals are inferential", "ML evaluation is inferential at heart"] },
            { kind: "practice", text: "Practice:", items: ["Compute mean, median, and std of [1, 2, 3, 4, 5] by hand.", "Why is the median more robust to outliers than the mean?", "Is a 95% confidence interval descriptive or inferential?", "Stretch: when would median be preferred over mean?"] },
          ],
        },
        {
          id: "math-sampling",
          title: "Population & sampling",
          summary: "Why sampling matters, and how it goes wrong.",
          blocks: [
            { kind: "prose", text: "You almost never have all the data. A *population* is everyone/everything you care about; a *sample* is a subset you actually measure. Good sampling = honest inference; bad sampling = bias." },
            { kind: "heading", text: "Sampling techniques" },
            { kind: "prose", text: "Random sampling gives every member equal chance. Stratified sampling splits into groups and samples each in proportion. Systematic sampling takes every k-th item. Convenience sampling uses whoever's easy to reach (and is dangerous)." },
            { kind: "heading", text: "Bias" },
            { kind: "prose", text: "If your sample over- or under-represents a group, your inferences will be wrong. ML examples: training on US-only photos and deploying globally, or sampling only successful customers and missing churn signals." },
            { kind: "callout", tone: "warn", text: "The most expensive ML bugs come from biased samples, not bad models. The data you trained on must reflect the data you'll predict on." },
            { kind: "keypoints", points: ["Population = everything you care about; sample = what you measure", "Random sampling = equal chance for every member", "Stratified sampling preserves subgroup proportions", "Biased samples produce biased models", "Always ask: does my sample represent my deployment data?"] },
            { kind: "practice", text: "Think about samples:", items: ["You survey only Twitter users about voting. What bias does this introduce?", "When would you stratify rather than randomly sample?", "How does stratify=y in train_test_split relate to stratified sampling?", "Stretch: name a real ML failure caused by biased training data."] },
          ],
        },
        {
          id: "math-central",
          title: "Central tendency",
          summary: "Mean, median, mode — which to use when.",
          blocks: [
            { kind: "prose", text: "Three ways to summarize the 'middle' of a dataset, each useful in different situations." },
            { kind: "heading", text: "Mean" },
            { kind: "prose", text: "The arithmetic average: sum of values / count. Sensitive to outliers — one billionaire makes the average income wildly higher than typical." },
            { kind: "heading", text: "Median" },
            { kind: "prose", text: "The middle value when sorted. Robust to outliers. For [1, 2, 3, 100], median is 2.5; mean is 26.5." },
            { kind: "heading", text: "Mode" },
            { kind: "prose", text: "The most frequent value. The only one that works for categorical data ('what's the most common category?')." },
            { kind: "code", lang: "python", code: "import numpy as np\nfrom scipy import stats\nx = np.array([1, 2, 2, 3, 100])\nprint(np.mean(x))           # 21.6\nprint(np.median(x))         # 2.0\nprint(stats.mode(x).mode)   # 2" },
            { kind: "keypoints", points: ["Mean: arithmetic average, sensitive to outliers", "Median: middle value, robust to outliers", "Mode: most frequent value, works for categories", "For skewed data (income, house prices) report the median", "Imputing missing values: mean/median for numeric, mode for categorical"] },
            { kind: "practice", text: "Pick the right summary:", items: ["For US income, which is higher — mean or median? Why?", "Which is best for 'average house price'?", "What is the mode of ['a', 'b', 'a', 'c']?", "Stretch: a normal distribution has mean = median = mode. Why?"] },
          ],
        },
        {
          id: "math-variability",
          title: "Variability",
          summary: "Range, variance, and standard deviation.",
          blocks: [
            { kind: "prose", text: "Central tendency tells you where the data sits; variability tells you how spread out it is. Two datasets can share a mean but differ dramatically in spread." },
            { kind: "heading", text: "Range" },
            { kind: "prose", text: "max - min. Trivial to compute, easily ruined by a single outlier." },
            { kind: "heading", text: "Variance" },
            { kind: "prose", text: "The average squared distance from the mean: σ² = (1/n) Σ (xᵢ - μ)². Squaring penalizes points far from the mean more." },
            { kind: "heading", text: "Standard deviation" },
            { kind: "prose", text: "σ = √variance. Same units as the data, so much more interpretable than variance." },
            { kind: "code", lang: "python", code: "x = np.array([2, 4, 4, 4, 5, 5, 7, 9])\nprint(np.var(x))    # 4.0\nprint(np.std(x))    # 2.0" },
            { kind: "callout", tone: "note", text: "For a sample, the unbiased estimator divides by (n-1) instead of n. NumPy's default is n; pass `ddof=1` for the n-1 version. The difference matters most on tiny samples." },
            { kind: "keypoints", points: ["Variability = spread of the data", "Range = max - min (simple, fragile)", "Variance = mean squared deviation from the mean", "Std deviation = √variance, same units as the data", "Standardization (z-score) subtracts mean, divides by std"] },
            { kind: "practice", text: "Variability:", items: ["Compute the std of [2, 4, 4, 4, 5, 5, 7, 9] by hand.", "Two datasets share mean = 50. One has std = 1, the other std = 30. What does that say?", "Why is std preferred over variance for reporting?", "Stretch: relate this to StandardScaler from the preprocessing lesson."] },
          ],
        },
        {
          id: "math-correlation",
          title: "Correlation & causation",
          summary: "Measure linear relationship — without mistaking it for cause.",
          blocks: [
            { kind: "prose", text: "Correlation measures whether two variables move together. The Pearson correlation coefficient r ranges from -1 (perfectly opposite) to +1 (perfectly aligned), with 0 meaning no linear relationship." },
            { kind: "code", lang: "python", code: "import numpy as np\nx = np.array([1, 2, 3, 4, 5])\ny = np.array([2, 4, 5, 4, 5])\nprint(np.corrcoef(x, y)[0, 1])   # ~0.77" },
            { kind: "heading", text: "Correlation ≠ causation" },
            { kind: "prose", text: "Ice cream sales correlate with drowning deaths. Neither causes the other; summer (the lurking variable) drives both. Correlation alone never proves cause." },
            { kind: "callout", tone: "warn", text: "Correlation only catches LINEAR relationships. Two variables can be tightly related (e.g. y = x²) and have correlation near 0. Always plot the data." },
            { kind: "keypoints", points: ["Pearson r ∈ [-1, +1], measures linear relationship", "r = 0 doesn't mean no relationship, just no linear one", "Correlation never proves causation", "Lurking variables explain many spurious correlations", "Always plot before trusting the number"] },
            { kind: "practice", text: "Reason about correlation:", items: ["What does r = -0.95 mean?", "Why might 'shoe size' correlate with 'reading ability' in kids? (Hint: age)", "What kind of relationship does correlation miss?", "Stretch: give an example of two strongly causally linked variables AND a correlation that fooled people."] },
          ],
        },
        {
          id: "math-hypothesis",
          title: "Hypothesis testing",
          summary: "A framework for deciding if an effect is real.",
          blocks: [
            { kind: "prose", text: "Did treatment A actually beat treatment B, or could the difference be chance? Hypothesis testing answers that with a structured procedure." },
            { kind: "heading", text: "The setup" },
            { kind: "prose", text: "Null hypothesis H₀: no effect (e.g. A and B are the same). Alternative H₁: there is an effect. You assume H₀, then ask: how likely is the data we observed, if H₀ were true?" },
            { kind: "heading", text: "p-value" },
            { kind: "prose", text: "The probability of seeing data at least this extreme, assuming H₀. Small p (commonly < 0.05) means the data is unlikely under H₀, so reject H₀." },
            { kind: "code", lang: "python", code: "from scipy import stats\na = [12, 15, 14, 10, 13]\nb = [22, 20, 21, 19, 23]\nt, p = stats.ttest_ind(a, b)\nprint(f\"t={t:.2f}, p={p:.4f}\")" },
            { kind: "callout", tone: "warn", text: "A small p-value does NOT mean the effect is large or important. It means the effect is unlikely to be pure noise. Always look at effect size too." },
            { kind: "heading", text: "Errors" },
            { kind: "prose", text: "Type I error: reject H₀ when it's actually true (false positive). Type II error: fail to reject H₀ when it's actually false (false negative). The 0.05 threshold caps Type I at 5%." },
            { kind: "keypoints", points: ["H₀ = no effect; H₁ = there is an effect", "p-value = probability of this data assuming H₀", "p < 0.05 typically means reject H₀", "Type I = false positive; Type II = false negative", "Small p ≠ big effect — check effect size too"] },
            { kind: "practice", text: "Apply the framework:", items: ["State H₀ for: 'a new drug lowers blood pressure'.", "If p = 0.001, do you reject H₀?", "What does Type I error mean here?", "Stretch: why is the choice of 0.05 partly conventional?"] },
          ],
        },
      ],
    },
    {
      id: "math-prob",
      title: "Probability",
      lessons: [
        {
          id: "math-prob-basics",
          title: "Probability basics",
          summary: "Sample spaces, events, and the rules that govern them.",
          blocks: [
            { kind: "prose", text: "Probability is the math of uncertainty. ML predicts probabilities for a living: spam vs ham, click vs no click, next word in a sentence." },
            { kind: "heading", text: "Sample space & events" },
            { kind: "prose", text: "Sample space Ω = all possible outcomes (rolling a die: {1,2,3,4,5,6}). An event is a subset of Ω (rolling even = {2,4,6})." },
            { kind: "heading", text: "Probability axioms" },
            { kind: "prose", text: "P(A) ∈ [0, 1] for any event A. P(Ω) = 1. For disjoint A, B: P(A ∪ B) = P(A) + P(B)." },
            { kind: "heading", text: "Independence & conditional probability" },
            { kind: "prose", text: "P(A | B) = P(A ∩ B) / P(B) is the probability of A given B happened. Independent events: P(A ∩ B) = P(A) · P(B)." },
            { kind: "heading", text: "Bayes' theorem" },
            { kind: "prose", text: "P(A | B) = P(B | A) · P(A) / P(B). The basis of naive Bayes classifiers and the Bayesian way of updating belief with evidence." },
            { kind: "code", lang: "text", code: "# Disease test example:\n# P(disease) = 0.01           prior\n# P(positive | disease) = 0.99\n# P(positive | healthy)  = 0.05\n# P(disease | positive) = ?\n# = (0.99 · 0.01) / (0.99 · 0.01 + 0.05 · 0.99) ≈ 0.167\n# Even with a positive test, only 16.7% chance of disease!" },
            { kind: "callout", tone: "tip", text: "That disease example is the classic 'base rate fallacy'. When the disease is rare, a positive test is mostly false. Train your intuition on it." },
            { kind: "keypoints", points: ["Sample space Ω = all outcomes; event A ⊆ Ω", "P(A) ∈ [0,1], P(Ω) = 1", "Conditional: P(A|B) = P(A ∩ B) / P(B)", "Independence: P(A ∩ B) = P(A) · P(B)", "Bayes: P(A|B) = P(B|A) · P(A) / P(B)"] },
            { kind: "practice", text: "Apply the rules:", items: ["Roll a fair die. What is P(even)?", "Two coin flips. P(both heads) if independent?", "If P(spam) = 0.2 and P(word 'free' | spam) = 0.4, P('free' | spam) is what?", "Stretch: redo the disease example with prior 0.5 instead of 0.01. What changes?"] },
          ],
        },
        {
          id: "math-random-vars",
          title: "Random variables",
          summary: "Discrete vs continuous variables of chance.",
          blocks: [
            { kind: "prose", text: "A random variable assigns a number to each outcome. Discrete RVs take countable values (die roll, click count). Continuous RVs take any real value in a range (height, time)." },
            { kind: "heading", text: "Expectation (mean)" },
            { kind: "prose", text: "E[X] = Σ x · P(X=x) for discrete (or an integral for continuous). The long-run average if you repeated the experiment forever." },
            { kind: "heading", text: "Variance" },
            { kind: "prose", text: "Var(X) = E[(X - E[X])²]. How much X typically wobbles around its mean." },
            { kind: "code", lang: "python", code: "# Fair die: X is the number rolled\n# E[X] = (1+2+3+4+5+6)/6 = 3.5\n# Var(X) = ((1-3.5)² + ... + (6-3.5)²)/6 ≈ 2.92" },
            { kind: "keypoints", points: ["Random variable X maps outcomes to numbers", "Discrete: countable values (die, counts)", "Continuous: any value in a range (height, time)", "E[X] = expected value, the long-run mean", "Var(X) = expected squared deviation from E[X]"] },
            { kind: "practice", text: "Compute expectations:", items: ["X = number on a fair die. E[X] = ?", "Y = 0 or 1 with P(Y=1) = 0.3. E[Y] = ?", "Is 'time to next bus' discrete or continuous?", "Stretch: E[2X + 3] for the die. (Hint: E[aX+b] = aE[X]+b.)"] },
          ],
        },
        {
          id: "math-distributions",
          title: "Probability distributions",
          summary: "PDFs, PMFs, and CDFs — the full shape of a random variable.",
          blocks: [
            { kind: "prose", text: "A distribution describes how probability is spread across possible values. Discrete RVs have a probability mass function (PMF); continuous RVs have a probability density function (PDF)." },
            { kind: "heading", text: "PMF / PDF" },
            { kind: "prose", text: "PMF: P(X = x) directly. PDF: the value f(x) is *not* a probability; you integrate (or take area under the curve) to get a probability. For continuous X, P(X = exactly x) = 0." },
            { kind: "heading", text: "CDF" },
            { kind: "prose", text: "Cumulative distribution: F(x) = P(X ≤ x). Always non-decreasing, runs from 0 to 1." },
            { kind: "heading", text: "Common discrete distributions" },
            { kind: "prose", text: "Bernoulli (single yes/no), Binomial (k yeses in n trials), Poisson (rare counts in a time window — next lesson)." },
            { kind: "heading", text: "Common continuous distributions" },
            { kind: "prose", text: "Normal (Gaussian, bell curve), Uniform (every value equally likely in a range), Exponential (waiting times)." },
            { kind: "code", lang: "python", code: "from scipy import stats\n# Bernoulli with p=0.3\nprint(stats.bernoulli.pmf(1, 0.3))   # 0.3\n# Normal CDF at 0 (standard normal)\nprint(stats.norm.cdf(0))             # 0.5" },
            { kind: "keypoints", points: ["Discrete: PMF — direct probabilities", "Continuous: PDF — densities; probabilities come from areas", "CDF F(x) = P(X ≤ x), always non-decreasing 0 → 1", "Discrete examples: Bernoulli, Binomial, Poisson", "Continuous examples: Normal, Uniform, Exponential"] },
            { kind: "practice", text: "Identify and apply:", items: ["Is a die-roll PMF or PDF?", "Is human height PMF or PDF?", "For Bernoulli(0.7), what is the PMF at 0?", "Stretch: why does P(X = exactly 1.5) = 0 for continuous X?"] },
          ],
        },
        {
          id: "math-normal",
          title: "The normal distribution",
          summary: "The bell curve — the most important distribution in ML.",
          blocks: [
            { kind: "prose", text: "The normal (Gaussian) distribution shows up everywhere: measurement errors, exam scores, neural network initializations, residuals in regression. Two parameters: mean μ (center) and std σ (spread)." },
            { kind: "heading", text: "Density" },
            { kind: "prose", text: "f(x) = (1 / (σ√(2π))) · exp(-(x - μ)² / (2σ²)). You won't compute it by hand often; what matters is the shape." },
            { kind: "heading", text: "The 68-95-99.7 rule" },
            { kind: "prose", text: "For any normal distribution: about 68% of values fall within 1 std of the mean, 95% within 2 stds, 99.7% within 3. This is why z-scores beyond 3 are flagged as outliers." },
            { kind: "code", lang: "python", code: "from scipy import stats\nimport numpy as np\nsamples = np.random.normal(0, 1, 10000)\nprint(np.mean(np.abs(samples) < 1))    # ~0.68\nprint(np.mean(np.abs(samples) < 2))    # ~0.95" },
            { kind: "heading", text: "Why so common?" },
            { kind: "prose", text: "The Central Limit Theorem: the sum of many small independent random effects tends to be normal, regardless of the original distributions. That's why so many real-world quantities look normal." },
            { kind: "callout", tone: "note", text: "Skewness measures asymmetry: positive skew has a long right tail (income), negative skew has a long left tail. Real data is often skewed; assuming normality blindly is dangerous." },
            { kind: "keypoints", points: ["Normal(μ, σ): bell curve centered at μ, spread σ", "68-95-99.7 rule: 1σ, 2σ, 3σ contain those % of values", "Central Limit Theorem explains why normals appear everywhere", "z-score = (x - μ) / σ standardizes any value", "Skewness measures departure from symmetry"] },
            { kind: "practice", text: "Use the bell curve:", items: ["Exam scores are normal with μ=70, σ=10. What % score above 80?", "What range covers 95% of values?", "Compute the z-score for 85 in that distribution.", "Stretch: state the CLT in one sentence."] },
          ],
        },
        {
          id: "math-poisson",
          title: "Poisson distribution",
          summary: "Counting rare events in a fixed window.",
          blocks: [
            { kind: "prose", text: "Poisson(λ) models the number of independent rare events in a fixed time/space window, given an average rate λ. Site visits per minute, calls per hour, defects per meter." },
            { kind: "heading", text: "PMF" },
            { kind: "prose", text: "P(X = k) = e^(-λ) · λ^k / k!. The mean and variance both equal λ — a useful shortcut." },
            { kind: "code", lang: "python", code: "from scipy import stats\n# Average 3 calls per hour. P(exactly 5 calls)?\nprint(stats.poisson.pmf(5, mu=3))     # ≈ 0.10\n# P(at most 2 calls)?\nprint(stats.poisson.cdf(2, mu=3))     # ≈ 0.42" },
            { kind: "callout", tone: "note", text: "Poisson assumes events are independent and the rate is constant in the window. If events cluster or the rate varies, you need richer models (negative binomial, point processes)." },
            { kind: "keypoints", points: ["Poisson(λ): count of rare independent events in a fixed window", "Mean = variance = λ", "P(X = k) = e^(-λ) · λ^k / k!", "Independence and constant rate required", "Common in queuing, web traffic, and rare-event modelling"] },
            { kind: "practice", text: "Apply Poisson:", items: ["Average 2 emails per minute. Expected emails in a 10-minute window?", "Use scipy to compute P(X = 4) when λ = 2.", "When would Poisson NOT fit (e.g. heavy event clustering)?", "Stretch: how does Poisson relate to the exponential distribution?"] },
          ],
        },
      ],
    },
  ],
};

export const mathGuided: GuidedProblem[] = [
  {
    id: "math-vectors-g1",
    lessonId: "math-vectors",
    title: "Normalize a vector",
    prompt: "Compute the magnitude of v = [3, 4, 12], then produce the unit vector pointing in the same direction.",
    hints: ["Magnitude = sqrt(sum of squares).", "Unit vector = v / magnitude."],
    solution: [
      { kind: "prose", text: "||v|| = √(9 + 16 + 144) = √169 = 13." },
      { kind: "code", lang: "python", code: "import numpy as np\nv = np.array([3, 4, 12])\nmag = np.linalg.norm(v)\nu = v / mag\nprint(mag, u)   # 13.0 [0.231 0.308 0.923]" },
    ],
  },
  {
    id: "math-vector-ops-g1",
    lessonId: "math-vector-ops",
    title: "Dot product and angle",
    prompt: "Compute the dot product of [1, 0] and [1, 1], then use it to find the angle (in degrees) between them.",
    hints: ["a · b = ||a|| ||b|| cos(θ).", "Rearrange: θ = arccos((a·b) / (||a|| ||b||))."],
    solution: [
      { kind: "code", lang: "python", code: "import numpy as np\na = np.array([1, 0])\nb = np.array([1, 1])\ndot = a @ b              # 1\ncos_t = dot / (np.linalg.norm(a) * np.linalg.norm(b))\nprint(np.degrees(np.arccos(cos_t)))   # 45.0" },
      { kind: "prose", text: "The dot product gives 1; divided by the magnitudes (1 and √2) gives cos(θ) = 1/√2, so θ = 45°." },
    ],
  },
  {
    id: "math-matrices-g1",
    lessonId: "math-matrices",
    title: "Transpose and identity",
    prompt: "Build a 2x3 matrix A. Print A.T's shape, and verify that A @ np.eye(3) equals A.",
    hints: ["Transpose swaps the shape.", "Multiplying by the identity gives the same matrix back."],
    solution: [
      { kind: "code", lang: "python", code: "import numpy as np\nA = np.array([[1, 2, 3], [4, 5, 6]])\nprint(A.T.shape)             # (3, 2)\nprint(np.allclose(A @ np.eye(3), A))   # True" },
    ],
  },
  {
    id: "math-matrix-ops-g1",
    lessonId: "math-matrix-ops",
    title: "Predict shape, then compute",
    prompt: "If A is shape (4, 3) and B is shape (3, 5), what is the shape of A @ B? Then compute one example by hand: [[1, 2], [3, 4]] @ [[5], [6]].",
    hints: ["Inner dimensions must match; outer dimensions become the result shape.", "Each output entry is a row · column dot product."],
    solution: [
      { kind: "prose", text: "Shape: (4, 5). Inner 3s cancel, outer 4 and 5 survive." },
      { kind: "prose", text: "Hand calc: [[1·5 + 2·6], [3·5 + 4·6]] = [[17], [39]]." },
    ],
  },
  {
    id: "math-desc-inf-g1",
    lessonId: "math-desc-inf",
    title: "Descriptive or inferential?",
    prompt: "Label each: (a) average exam score of this class, (b) estimated approval rating of a president from a 1000-person poll, (c) std deviation of monthly sales.",
    hints: ["Are you summarizing data you have, or generalizing to a bigger group?"],
    solution: [
      { kind: "prose", text: "(a) Descriptive (this class is the entire population of interest)." },
      { kind: "prose", text: "(b) Inferential (the 1000 is a sample, the population is all citizens)." },
      { kind: "prose", text: "(c) Descriptive (summarizing observed sales)." },
    ],
  },
  {
    id: "math-sampling-g1",
    lessonId: "math-sampling",
    title: "Spot the sampling bias",
    prompt: "A health app surveys its users about exercise habits. It concludes that '60% of people exercise daily'. What's wrong, and how would you fix the sampling?",
    hints: ["Who installs a health app?", "Is the sample representative of the population the claim is about?"],
    solution: [
      { kind: "prose", text: "Health-app users are self-selected and likely more health-conscious than average. The 60% generalizes to app users, not 'people'." },
      { kind: "prose", text: "Fix: draw a stratified random sample of the general population (age, gender, region) and survey them directly." },
    ],
  },
  {
    id: "math-central-g1",
    lessonId: "math-central",
    title: "Mean, median, mode",
    prompt: "For the dataset [1, 2, 2, 3, 100], compute the mean, median, and mode. Which one best represents 'typical'?",
    hints: ["Sort, then find the middle for the median.", "Outliers pull the mean far from typical."],
    solution: [
      { kind: "prose", text: "Mean = 108/5 = 21.6. Median = 2. Mode = 2." },
      { kind: "prose", text: "Median (and mode) best represent the typical value here; the 100 is an outlier dragging the mean way up." },
    ],
  },
  {
    id: "math-variability-g1",
    lessonId: "math-variability",
    title: "Compute std deviation",
    prompt: "Compute the (population) standard deviation of [2, 4, 4, 4, 5, 5, 7, 9] by hand, then verify with NumPy.",
    hints: ["Mean is 5.", "Variance = mean of squared deviations from the mean."],
    solution: [
      { kind: "prose", text: "Mean = 5. Squared deviations: 9,1,1,1,0,0,4,16 → sum 32, mean 4. Std = √4 = 2." },
      { kind: "code", lang: "python", code: "import numpy as np\nx = np.array([2,4,4,4,5,5,7,9])\nprint(np.std(x))   # 2.0" },
    ],
  },
  {
    id: "math-correlation-g1",
    lessonId: "math-correlation",
    title: "Correlation ≠ causation",
    prompt: "Ice cream sales correlate strongly with drowning deaths. Does ice cream cause drownings? If not, what does?",
    hints: ["What time of year do both happen?", "Look for a third variable."],
    solution: [
      { kind: "prose", text: "No. Both are driven by summer: hot weather increases ice cream sales AND swimming, which leads to more drownings. The third 'lurking' variable creates the correlation without a causal link between the two." },
    ],
  },
  {
    id: "math-hypothesis-g1",
    lessonId: "math-hypothesis",
    title: "Interpret a p-value",
    prompt: "A clinical trial reports p = 0.03 for the effect of a new drug vs placebo. Explain what this means in plain English, and what it does NOT say.",
    hints: ["p is the probability of the data assuming H₀ is true.", "A small p says nothing about effect size."],
    solution: [
      { kind: "prose", text: "There's a 3% chance of observing data this extreme if the drug actually had no effect. Below the conventional 5% threshold, we reject H₀ (no effect) and conclude there's likely a real effect." },
      { kind: "prose", text: "It does NOT say: the drug effect is large, the drug is useful in practice, or there is a 97% chance the drug works. Always report effect size alongside the p-value." },
    ],
  },
  {
    id: "math-prob-basics-g1",
    lessonId: "math-prob-basics",
    title: "Bayes on a disease test",
    prompt: "1 in 1000 people has a disease. A test is 99% accurate (P(pos|disease) = 0.99) but has a 5% false positive rate (P(pos|healthy) = 0.05). A random person tests positive. What is the probability they actually have the disease?",
    hints: ["P(disease|pos) = P(pos|disease) · P(disease) / P(pos).", "P(pos) = P(pos|disease)·P(disease) + P(pos|healthy)·P(healthy)."],
    solution: [
      { kind: "prose", text: "P(pos) = 0.99·0.001 + 0.05·0.999 = 0.00099 + 0.04995 = 0.05094." },
      { kind: "prose", text: "P(disease | pos) = 0.99·0.001 / 0.05094 ≈ 0.0194, about 1.9%. Even with a positive test, the disease is still rare. This is the base-rate fallacy in action." },
    ],
  },
  {
    id: "math-random-vars-g1",
    lessonId: "math-random-vars",
    title: "Expectation of a die",
    prompt: "X is the result of a fair 6-sided die. Compute E[X] and Var(X).",
    hints: ["E[X] = Σ x · P(X=x).", "Var(X) = E[(X - E[X])²]."],
    solution: [
      { kind: "prose", text: "E[X] = (1+2+3+4+5+6)/6 = 3.5." },
      { kind: "prose", text: "Squared deviations from 3.5: 6.25, 2.25, 0.25, 0.25, 2.25, 6.25. Sum 17.5, divide by 6: Var(X) ≈ 2.92." },
    ],
  },
  {
    id: "math-distributions-g1",
    lessonId: "math-distributions",
    title: "Pick the distribution",
    prompt: "Choose the most fitting distribution for: (a) flipping one biased coin, (b) heights of adult women, (c) number of emails per hour, (d) waiting time at a bus stop.",
    hints: ["Bernoulli for single yes/no. Normal for measurements. Poisson for counts in a window. Exponential for waiting times."],
    solution: [
      { kind: "prose", text: "(a) Bernoulli (one trial, two outcomes)." },
      { kind: "prose", text: "(b) Normal (continuous, bell-shaped from many small influences)." },
      { kind: "prose", text: "(c) Poisson (count of rare-ish events per fixed window)." },
      { kind: "prose", text: "(d) Exponential (continuous waiting time between events)." },
    ],
  },
  {
    id: "math-normal-g1",
    lessonId: "math-normal",
    title: "68-95-99.7 in practice",
    prompt: "IQ is normal with μ=100, σ=15. Roughly what percent of people have IQ between 85 and 115? Between 70 and 130?",
    hints: ["85 and 115 are one std away from the mean.", "Use 68-95-99.7."],
    solution: [
      { kind: "prose", text: "85 to 115 = μ ± 1σ → about 68%." },
      { kind: "prose", text: "70 to 130 = μ ± 2σ → about 95%." },
    ],
  },
  {
    id: "math-poisson-g1",
    lessonId: "math-poisson",
    title: "Poisson expected count",
    prompt: "A website averages 12 visitors per hour. (a) Expected visitors in a 15-minute window? (b) Use scipy to find P(exactly 4 visitors in 15 min).",
    hints: ["Scale λ to the new window: 15 minutes is 1/4 of an hour.", "stats.poisson.pmf(k, mu=λ)."],
    solution: [
      { kind: "prose", text: "(a) λ for 15 min = 12 · 0.25 = 3 visitors expected." },
      { kind: "code", lang: "python", code: "from scipy import stats\nprint(stats.poisson.pmf(4, mu=3))   # ≈ 0.168" },
    ],
  },
];
