import type { Track, GuidedProblem } from "@/content/types";

export const mlopsTrack: Track = {
  id: "ml-mlops",
  title: "MLOps & Job Readiness",
  modules: [
    {
      id: "mlops-prod",
      title: "MLOps & deployment",
      lessons: [
        {
          id: "mlops-tracking",
          title: "Experiment tracking & versioning",
          summary: "Know which run produced which result, every time.",
          blocks: [
            { kind: "prose", text: "After a few weeks of experimenting, 'which config produced that 0.87 score?' becomes a real question. Experiment tracking saves every run's code, data, hyperparameters, and metrics." },
            { kind: "heading", text: "What to track" },
            { kind: "code", lang: "text", code: "Code commit (git sha)         data version / hash\nHyperparameters               metric history per epoch\nFinal metrics on val + test   model artifact path\nEnvironment (Python, pkgs)    notes / tags" },
            { kind: "heading", text: "Tools" },
            { kind: "prose", text: "MLflow (open source, self-host or use Databricks managed), Weights & Biases (popular cloud), Neptune. For tiny projects, even a structured CSV beats nothing." },
            { kind: "code", lang: "python", code: "import mlflow\n\nwith mlflow.start_run():\n    mlflow.log_params({\"lr\": 0.001, \"batch\": 64})\n    for epoch in range(epochs):\n        # train ...\n        mlflow.log_metric(\"val_acc\", val_acc, step=epoch)\n    mlflow.sklearn.log_model(model, \"model\")" },
            { kind: "heading", text: "Model versioning" },
            { kind: "prose", text: "A model is code + weights + data. Version all three. Use a model registry (MLflow, W&B, or a simple S3 prefix structure like /models/v3/model.pkl)." },
            { kind: "callout", tone: "tip", text: "The minute you have two models that disagree, you'll wish you'd tagged them with a version. Start tracking from day one." },
            { kind: "keypoints", points: ["Track code, data, hyperparameters, and metrics together", "MLflow / W&B are the standard tools", "Model = code + weights + data — version all three", "A registry lets you stage versions: dev → staging → prod", "Even a CSV is better than nothing"] },
            { kind: "practice", text: "Set up tracking:", items: ["List 5 things you'd log for every training run.", "Why version the data, not just the code?", "What's a model registry?", "Stretch: how would you reproduce a 2-month-old experiment?"] },
          ],
        },
        {
          id: "mlops-serving",
          title: "Serving models as APIs",
          summary: "Wrap a trained model in an HTTP endpoint.",
          blocks: [
            { kind: "prose", text: "A model that lives in a notebook is invisible to the rest of the world. Serving turns it into an HTTP endpoint other apps can call." },
            { kind: "heading", text: "A minimal FastAPI server" },
            { kind: "code", lang: "python", code: "from fastapi import FastAPI\nfrom pydantic import BaseModel\nimport joblib\n\nmodel = joblib.load(\"model.pkl\")\napp = FastAPI()\n\nclass Input(BaseModel):\n    features: list[float]\n\n@app.post(\"/predict\")\ndef predict(inp: Input):\n    pred = model.predict([inp.features])[0]\n    return {\"prediction\": float(pred)}" },
            { kind: "heading", text: "Containerizing" },
            { kind: "prose", text: "Ship in Docker so 'works on my machine' is no longer an excuse. A 10-line Dockerfile is enough for most ML services." },
            { kind: "code", lang: "text", code: "FROM python:3.11-slim\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install -r requirements.txt\nCOPY . .\nCMD [\"uvicorn\", \"main:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\"]" },
            { kind: "heading", text: "Where to deploy" },
            { kind: "prose", text: "Cloud Run / Fly.io / Render for simple containers. SageMaker / Vertex AI for managed serving with autoscaling. For LLMs at scale: vLLM behind a load balancer, or a managed inference provider." },
            { kind: "heading", text: "Batch vs real-time" },
            { kind: "prose", text: "Real-time: per-request, low latency, online API. Batch: score millions of rows on a schedule. Pick based on use case — batch is far cheaper and simpler when latency doesn't matter." },
            { kind: "keypoints", points: ["FastAPI + uvicorn is the standard Python serving stack", "Docker is non-negotiable for reproducible deploys", "Cloud Run / Fly are easiest; SageMaker for managed scale", "Decide real-time vs batch up front", "Batch is cheaper if you can afford latency"] },
            { kind: "practice", text: "Ship a model:", items: ["Sketch a /predict route that loads model.pkl and returns JSON.", "Write the Dockerfile (5-10 lines).", "When would you choose batch over real-time?", "Stretch: how would you handle a model that's 2GB and slow to load?"] },
          ],
        },
        {
          id: "mlops-monitoring",
          title: "Monitoring & data drift",
          summary: "Catch silent failures after the model goes live.",
          blocks: [
            { kind: "prose", text: "ML models can degrade silently as the world changes. Inputs drift (new categories, shifted distributions), outputs drift, and accuracy quietly collapses. Monitoring catches it before users do." },
            { kind: "heading", text: "What to monitor" },
            { kind: "code", lang: "text", code: "System metrics:    latency, error rate, throughput\nData drift:        distributions of input features vs training\nPrediction drift:  distributions of model outputs vs baseline\nGround truth:      accuracy/F1 once labels come in (often delayed)\nBusiness metric:   the thing the model is actually supposed to move" },
            { kind: "heading", text: "Detecting drift" },
            { kind: "prose", text: "Compare current input distributions to the training set: PSI (population stability index), KS test, simple histograms. Set thresholds; alert when crossed. Libraries like Evidently or whylogs automate this." },
            { kind: "callout", tone: "warn", text: "Accuracy alone is a lagging metric — you might only get labels weeks later. Pair it with leading indicators (input drift, prediction distribution shifts) so you find out fast." },
            { kind: "heading", text: "Retraining" },
            { kind: "prose", text: "When drift exceeds thresholds or performance falls, retrain. Decide: scheduled (daily/weekly), triggered (on drift alarm), or continuous learning (rare and harder to get right)." },
            { kind: "keypoints", points: ["Monitor system, data, prediction, and ground-truth metrics", "Detect drift with PSI, KS test, distribution histograms", "Labels often arrive late; lean on input/output drift in the meantime", "Set thresholds and alert before users feel the problem", "Plan a retraining cadence: scheduled or triggered"] },
            { kind: "practice", text: "Plan monitoring:", items: ["Name 3 things you'd alert on for a deployed fraud model.", "Why are prediction-distribution shifts useful even without ground truth?", "Pick a retraining cadence for a recommender; justify.", "Stretch: how would you A/B test a new model version safely?"] },
          ],
        },
        {
          id: "mlops-pipelines",
          title: "Data & training pipelines",
          summary: "Automate the path from raw data to a deployed model.",
          blocks: [
            { kind: "prose", text: "Hand-running notebooks doesn't scale. Pipelines turn the workflow into code that runs end-to-end on a schedule or trigger, with proper logging and reproducibility." },
            { kind: "heading", text: "Anatomy" },
            { kind: "code", lang: "text", code: "ingest → validate → preprocess → train → evaluate → register → deploy\n           ↓             ↓            ↓        ↓\n         alerts       feature store  metrics  CI gates" },
            { kind: "heading", text: "Tools" },
            { kind: "prose", text: "Airflow / Prefect / Dagster for general orchestration. Kubeflow Pipelines or Vertex AI Pipelines for ML-specific workflows on Kubernetes. dbt for SQL-side data transforms upstream." },
            { kind: "heading", text: "CI/CD for ML" },
            { kind: "prose", text: "Run the pipeline in CI on every PR: lint, unit tests, a small training run, and a model-quality gate (refuse to merge if val accuracy falls)." },
            { kind: "callout", tone: "tip", text: "Build the smallest possible pipeline first — even a Python script triggered by cron is a step up from manual notebooks. Add tooling as needs grow." },
            { kind: "keypoints", points: ["Pipelines codify the data → model → deploy workflow", "Airflow / Prefect / Dagster orchestrate steps", "Kubeflow / Vertex Pipelines for ML on k8s", "CI gates prevent regressions in model quality", "Start tiny; grow as the project demands"] },
            { kind: "practice", text: "Sketch a pipeline:", items: ["List the steps for a daily-retrained recommender pipeline.", "What would you put in a 'model quality gate' for CI?", "Why have a separate 'validate' step after ingest?", "Stretch: how do you keep the training and serving feature transforms in sync?"] },
          ],
        },
      ],
    },
    {
      id: "mlops-career",
      title: "Portfolio & interviews",
      lessons: [
        {
          id: "mlops-portfolio",
          title: "Building a portfolio",
          summary: "What to ship, and how to present it.",
          blocks: [
            { kind: "prose", text: "Your portfolio is how a stranger decides whether you can do the job. Three polished projects beat ten half-baked ones. Each should tell a clear story." },
            { kind: "heading", text: "The portfolio shape" },
            { kind: "code", lang: "text", code: "Project 1 — Classical ML end-to-end\n  e.g. churn prediction with EDA, model comparison, deployed API\n\nProject 2 — Deep learning\n  e.g. image classifier (transfer learning) or NLP with transformers\n\nProject 3 — AI/LLM app\n  e.g. RAG over a real corpus, deployed full-stack (uses your web skills!)\n\nBonus — the OG: Launchpad itself" },
            { kind: "heading", text: "Anatomy of a good project README" },
            { kind: "code", lang: "text", code: "1. One-line description + screenshot or demo gif\n2. Problem statement and why it matters\n3. Data: source, size, license\n4. Approach: alternatives considered, choice and trade-offs\n5. Results: key metric vs baseline, plots\n6. Lessons learned (honest, not buzzwords)\n7. How to run locally + a live demo link" },
            { kind: "heading", text: "What hiring managers look for" },
            { kind: "prose", text: "Can you frame a problem? Did you understand the data? Did you make defensible choices? Can you ship? A messy notebook says one thing; a clean repo with tests, a README, and a deployed demo says another." },
            { kind: "callout", tone: "tip", text: "Your existing Launchpad project IS a portfolio piece. It shows initiative, full-stack ability, and discipline. Lead with it." },
            { kind: "keypoints", points: ["Aim for 3 polished projects across families", "Each README tells the problem → approach → results → reflection story", "Show ability to ship: live demo, deployed API, or clean reproducible code", "Honest 'lessons learned' beats buzzwords", "Launchpad itself is a strong portfolio piece"] },
            { kind: "practice", text: "Plan your portfolio:", items: ["Decide your three portfolio projects.", "Sketch the README outline for one.", "Pick one to deploy live within a month.", "Stretch: which project shows off the most range across the curriculum?"] },
          ],
        },
        {
          id: "mlops-interviews",
          title: "ML interview prep",
          summary: "The four rounds and how to prepare for each.",
          blocks: [
            { kind: "prose", text: "Most ML interviews have a similar shape. Knowing the structure cuts anxiety in half." },
            { kind: "heading", text: "Round 1: Coding (DSA)" },
            { kind: "prose", text: "Yes, even for ML roles. Standard data-structures and algorithms problems. Your DSA phases were not a detour: this is where they pay off. Aim for fluent in arrays, hashing, two-pointers, sliding window, binary search, trees, graphs, and 1-D DP." },
            { kind: "heading", text: "Round 2: ML fundamentals" },
            { kind: "prose", text: "Conceptual: bias-variance, overfitting, regularization, when to use which model, train/test methodology. Loss functions and metrics for the right problem. Bayes, naive Bayes, decision trees, ensembles. Be ready to derive logistic regression's loss." },
            { kind: "heading", text: "Round 3: ML coding" },
            { kind: "prose", text: "Implement an algorithm from scratch in NumPy (linear/logistic regression, k-means, simple neural net forward pass), or do an end-to-end workflow on a small dataset under time pressure (load → clean → split → train → evaluate)." },
            { kind: "heading", text: "Round 4: ML system design" },
            { kind: "prose", text: "'Design Netflix's recommender' or 'How would you build a fraud-detection system?'. Frame the problem, propose data + features + model + training + eval + deployment + monitoring. Trade-offs out loud." },
            { kind: "callout", tone: "tip", text: "Speak through your reasoning constantly. Interviewers grade decision-making as much as the answer itself." },
            { kind: "keypoints", points: ["Coding (DSA): arrays, hashing, two pointers, trees, graphs, basic DP", "ML fundamentals: concepts, model trade-offs, methodology", "ML coding: implement from scratch or end-to-end workflow", "ML system design: problem → data → model → eval → deploy → monitor", "Always speak your reasoning aloud"] },
            { kind: "practice", text: "Get interview-ready:", items: ["Implement logistic regression from scratch in 20 minutes (gradient descent).", "Explain bias-variance in 3 sentences as if to a non-ML engineer.", "Design 'a system to recommend movies' in 5 minutes, narrating trade-offs.", "Stretch: practice a behavioural STAR story for 'a time I shipped under uncertainty'."] },
          ],
        },
        {
          id: "mlops-system-design",
          title: "ML system design — a framework",
          summary: "How to whiteboard 'design X' under pressure.",
          blocks: [
            { kind: "prose", text: "ML system design questions feel open-ended, but the strongest answers follow a structure. Use this skeleton out loud, even if the interviewer doesn't prompt you." },
            { kind: "heading", text: "1. Clarify" },
            { kind: "prose", text: "What does the system do, for whom, at what scale? What's the success metric? Real-time or batch? Constraints (latency, cost, privacy)? Use 1-2 minutes to pin this down." },
            { kind: "heading", text: "2. Data" },
            { kind: "prose", text: "What data do we have or could collect? Where does the label come from? Volume, freshness, biases. Cold-start strategy if no data yet." },
            { kind: "heading", text: "3. Features" },
            { kind: "prose", text: "What does each example look like? How are features extracted/engineered, and where does that code live (training and serving must match)?" },
            { kind: "heading", text: "4. Model" },
            { kind: "prose", text: "Baseline first (logistic regression, a rule). Then a stronger candidate (gradient boosting, neural net, transformer fine-tune). Justify the jump." },
            { kind: "heading", text: "5. Training & evaluation" },
            { kind: "prose", text: "Splits (be careful with time-based ones for production data!). Metrics aligned with the business goal. Offline evaluation, then online A/B test." },
            { kind: "heading", text: "6. Serving" },
            { kind: "prose", text: "Real-time vs batch. Latency budget. Cache and pre-compute when possible. Fallback when the model is unavailable." },
            { kind: "heading", text: "7. Monitoring & feedback" },
            { kind: "prose", text: "Metrics, drift detection, labelling pipeline, retraining cadence. Close the loop." },
            { kind: "callout", tone: "tip", text: "Spend the first 90 seconds asking clarifying questions, even if you think you understand. It demonstrates senior-level thinking and prevents going in the wrong direction." },
            { kind: "keypoints", points: ["Clarify → Data → Features → Model → Train/Eval → Serve → Monitor", "Always propose a baseline first, then improve", "Highlight trade-offs (cost vs latency vs accuracy)", "Watch for data leakage in your training split", "Close the loop: how does the system improve over time?"] },
            { kind: "practice", text: "Practice the framework:", items: ["Design 'recommend videos for YouTube' in 15 minutes using the framework.", "Design 'detect credit card fraud' — what's the metric? What about cost asymmetry?", "Design 'spam filter' — what's your baseline, and what's the upgrade?", "Stretch: design 'image search by photo' (multi-modal)."] },
          ],
        },
      ],
    },
  ],
};

export const mlopsGuided: GuidedProblem[] = [
  {
    id: "mlops-tracking-g1",
    lessonId: "mlops-tracking",
    title: "Design a run-log row",
    prompt: "Design the column schema for a CSV/DB that logs every training run. List 8-10 columns and what each captures.",
    hints: ["Code, data, hyperparameters, metrics, artefacts, environment."],
    solution: [
      { kind: "prose", text: "run_id, timestamp, git_sha, dataset_version, model_type, hyperparams_json, train_metric, val_metric, test_metric, model_artifact_path, python_version, notes." },
      { kind: "prose", text: "These let you reproduce, compare, and audit any run later. The artefact path lets you load the actual model trained in that run." },
    ],
  },
  {
    id: "mlops-serving-g1",
    lessonId: "mlops-serving",
    title: "Ship a model via FastAPI",
    prompt: "Write a FastAPI endpoint /predict that accepts a JSON body {features: [..]}, loads model.pkl (once at startup), and returns {prediction}.",
    hints: ["Load the model at import time so each request is fast.", "Use pydantic for typed input."],
    solution: [
      { kind: "code", lang: "python", code: "from fastapi import FastAPI\nfrom pydantic import BaseModel\nimport joblib\n\nmodel = joblib.load(\"model.pkl\")\napp = FastAPI()\n\nclass Input(BaseModel):\n    features: list[float]\n\n@app.post(\"/predict\")\ndef predict(inp: Input):\n    pred = model.predict([inp.features])[0]\n    return {\"prediction\": float(pred)}" },
      { kind: "prose", text: "Loading the model at import time amortizes the cost across all requests, instead of paying it every call." },
    ],
  },
  {
    id: "mlops-monitoring-g1",
    lessonId: "mlops-monitoring",
    title: "Detect silent failure",
    prompt: "A loan-default model has had stable accuracy for 6 months. Suddenly its predicted default rate doubles, but you won't know if it's right for another 90 days (default labels are slow). What do you do?",
    hints: ["Investigate input drift.", "Don't wait — act on leading indicators."],
    solution: [
      { kind: "prose", text: "Compare input feature distributions to training: large drift in any feature explains the shift. Compare model output distribution to its long-term baseline — a doubling is a red flag. Inspect a handful of borderline predictions with humans." },
      { kind: "prose", text: "If drift is severe, fall back to a simpler model or human review. Don't wait 90 days for labels to confirm what leading indicators already suggest." },
    ],
  },
  {
    id: "mlops-pipelines-g1",
    lessonId: "mlops-pipelines",
    title: "Sketch a CI quality gate",
    prompt: "You want CI to refuse a PR that hurts model quality. Sketch the gate: what does it run, what does it compare against, and when does it fail?",
    hints: ["Train on a small fixed sample.", "Compare to a stored baseline metric."],
    solution: [
      { kind: "prose", text: "On every PR: run the pipeline on a fixed small dataset with fixed seed, measure validation F1, compare to a baseline number stored in the repo. Fail if F1 drops by more than a threshold (e.g. 1% absolute)." },
      { kind: "prose", text: "Bonus: also fail if the model fails a 'unit test' set of held-out hard examples it must always classify correctly." },
    ],
  },
  {
    id: "mlops-portfolio-g1",
    lessonId: "mlops-portfolio",
    title: "Outline your top project's README",
    prompt: "Pick the strongest project you'll have built by the end of this curriculum and outline its README headers + one sentence per section.",
    hints: ["Follow the standard shape from the lesson.", "Include problem → approach → results → reflection."],
    solution: [
      { kind: "prose", text: "Sample for an RAG docs assistant: 1) What it does (chat with the Python docs). 2) Problem and why it's useful. 3) Data (Python docs, 200MB). 4) Approach (chunk+embed → pgvector → RAG with citations). 5) Results (response quality eval set, latency). 6) Lessons (chunk size matters more than model). 7) Run locally + live demo URL." },
    ],
  },
  {
    id: "mlops-interviews-g1",
    lessonId: "mlops-interviews",
    title: "Explain bias-variance to a manager",
    prompt: "In an interview, explain the bias-variance tradeoff to a non-technical hiring manager in 3 sentences. Use one concrete example.",
    hints: ["Avoid jargon.", "Anchor on a memorable example."],
    solution: [
      { kind: "prose", text: "A model can be too simple (it misses the pattern) or too complex (it memorizes noise). Too simple is high bias: a straight line trying to fit a curve. Too complex is high variance: a wiggly curve that fits training data perfectly but flops on new examples. Good ML finds the sweet spot in the middle." },
    ],
  },
  {
    id: "mlops-system-design-g1",
    lessonId: "mlops-system-design",
    title: "Design a spam filter",
    prompt: "Walk through designing a production spam filter in 8 minutes using the 7-step framework. List the key points you'd hit per step.",
    hints: ["Clarify metric and cost asymmetry up front.", "Start with a logistic regression baseline."],
    solution: [
      { kind: "prose", text: "1) Clarify: email or SMS? real-time? metric: precision-heavy (don't lose real mail). 2) Data: historical emails labelled spam/ham; user reports as future signal. 3) Features: TF-IDF, sender reputation, URL counts, header signals. 4) Model: logistic regression baseline; gradient boosting upgrade; transformer for hard cases. 5) Train: time-based split (no future leak), tune on validation, evaluate precision @ high recall threshold. 6) Serve: real-time API at SMTP gateway; <50ms latency; cache features. 7) Monitor: false-positive complaints, drift in features, retrain weekly + on alert." },
    ],
  },
];
