import type { Module, GuidedProblem } from "@/content/types";

export const preprocessingModule: Module = {
  id: "ml-preprocessing",
  title: "Data collection & preprocessing",
  lessons: [
    {
      id: "ml-collect",
      title: "Collecting & loading data",
      summary: "Where data comes from, and how to load it (incl. Kaggle).",
      blocks: [
        { kind: "prose", text: "Real ML starts with finding the right data. The usual sources: open datasets (Kaggle, UCI, government portals), APIs, web scraping, and your own database." },
        { kind: "heading", text: "Kaggle: the practitioner's library" },
        { kind: "prose", text: "Kaggle hosts thousands of curated datasets and competitions. The API lets you download a dataset from the command line straight into your project." },
        { kind: "code", lang: "text", code: "# one-time setup\npip install kaggle\n# put kaggle.json (API key) in ~/.kaggle/\n\n# download a dataset\nkaggle datasets download -d <owner/dataset-name>" },
        { kind: "heading", text: "Loading common formats" },
        { kind: "code", lang: "python", code: "import pandas as pd\n\ndf = pd.read_csv(\"data.csv\")\ndf = pd.read_excel(\"data.xlsx\")\ndf = pd.read_json(\"data.json\")\ndf = pd.read_parquet(\"data.parquet\")   # columnar, very fast" },
        { kind: "callout", tone: "tip", text: "When working with large data, prefer parquet over CSV: it loads several times faster and preserves data types." },
        { kind: "keypoints", points: ["Sources: open datasets, APIs, scraping, your own DB", "Kaggle API downloads datasets in one command", "`pd.read_csv/excel/json/parquet` load the common formats", "Parquet is much faster than CSV at scale"] },
        { kind: "practice", text: "Get some data:", items: ["Find a small Kaggle dataset that interests you and download it.", "Load it with `pd.read_csv` and check `.shape` and `.dtypes`.", "Run `.head()` and `.describe()` to get a first feel.", "Stretch: save the DataFrame to parquet and time both loads."] },
      ],
    },
    {
      id: "ml-missing",
      title: "Handling missing values",
      summary: "Detect, drop, or impute — and know when each is right.",
      blocks: [
        { kind: "prose", text: "Missing data is the rule, not the exception. You have two real choices: drop the rows/columns, or fill them in (impute). The right call depends on how much is missing and why." },
        { kind: "heading", text: "Detect" },
        { kind: "code", lang: "python", code: "df.isna().sum()                  # missing per column\ndf.isna().mean() * 100           # percent missing per column" },
        { kind: "heading", text: "Drop" },
        { kind: "code", lang: "python", code: "df = df.dropna()                  # drop any row with a missing value\ndf = df.dropna(subset=[\"age\"])    # only when age is missing\ndf = df.dropna(axis=1, thresh=int(0.7 * len(df)))  # drop very sparse columns" },
        { kind: "heading", text: "Impute" },
        { kind: "code", lang: "python", code: "df[\"age\"] = df[\"age\"].fillna(df[\"age\"].mean())          # numeric -> mean/median\ndf[\"city\"] = df[\"city\"].fillna(df[\"city\"].mode()[0])   # categorical -> mode\n\nfrom sklearn.impute import SimpleImputer\nimputer = SimpleImputer(strategy=\"median\")\ndf[num_cols] = imputer.fit_transform(df[num_cols])" },
        { kind: "callout", tone: "warn", text: "Compute imputation statistics on the TRAINING set only, then apply them to test data. Computing them on the full data leaks information from test into train." },
        { kind: "keypoints", points: ["`isna()` finds missing values; sum/mean summarize them", "Drop rows when missingness is small and random", "Drop columns when too much is missing to recover", "Impute with mean/median for numeric, mode for categorical", "Fit imputation on training data only"] },
        { kind: "practice", text: "Handle missing data:", items: ["Print the percent of missing values per column of a DataFrame.", "Drop rows where a specific column is missing.", "Fill a numeric column's missing values with its median.", "Stretch: why is using `dropna()` on a 30%-missing column usually a bad idea?"] },
      ],
    },
    {
      id: "ml-scaling",
      title: "Feature scaling",
      summary: "Standardize or normalize so features compare fairly.",
      blocks: [
        { kind: "prose", text: "Distance-based and gradient-based models (k-NN, SVM, logistic regression, neural nets) suffer when features are on wildly different scales. Scaling puts them on comparable footing." },
        { kind: "heading", text: "Standardization (z-score)" },
        { kind: "prose", text: "Subtract the mean and divide by the standard deviation, so each feature has mean 0 and std 1. The default choice." },
        { kind: "code", lang: "python", code: "from sklearn.preprocessing import StandardScaler\n\nscaler = StandardScaler()\nX_train_s = scaler.fit_transform(X_train)\nX_test_s = scaler.transform(X_test)   # use stats learned from train" },
        { kind: "heading", text: "Normalization (min-max)" },
        { kind: "prose", text: "Squashes values into [0, 1]. Good when you need a bounded range (e.g. image pixels)." },
        { kind: "code", lang: "python", code: "from sklearn.preprocessing import MinMaxScaler\nscaler = MinMaxScaler()\nX = scaler.fit_transform(X)" },
        { kind: "callout", tone: "warn", text: "Always `fit` the scaler on training data only, then `transform` both train and test. Fitting on the full data leaks information from test into train." },
        { kind: "callout", tone: "note", text: "Tree-based models (decision tree, random forest, gradient boosting) do NOT need scaling. Distance- and gradient-based models do." },
        { kind: "keypoints", points: ["`StandardScaler`: mean 0, std 1 — the default", "`MinMaxScaler`: scales into [0, 1] — when you need a fixed range", "Fit on train; transform train AND test", "Tree models do not need scaling; most others do"] },
        { kind: "practice", text: "Scale features:", items: ["Standardize a 2-column numeric array with `StandardScaler`.", "Print the mean and std of the result (should be ~0 and 1).", "Min-max scale the same data into [0, 1].", "Stretch: explain why you fit on train but not test."] },
      ],
    },
    {
      id: "ml-encoding",
      title: "Encoding categorical features",
      summary: "Label encoding vs one-hot — and when to use each.",
      blocks: [
        { kind: "prose", text: "Most models only accept numbers, so categorical columns (`city = London/Paris/Berlin`) must be turned into numeric form. Two main approaches." },
        { kind: "heading", text: "Label encoding" },
        { kind: "prose", text: "Map each category to an integer. Fine for the target of a classifier or for ordinal categories where order matters (`small=0, medium=1, large=2`)." },
        { kind: "code", lang: "python", code: "from sklearn.preprocessing import LabelEncoder\nle = LabelEncoder()\ny_enc = le.fit_transform([\"spam\", \"ham\", \"spam\"])  # [1, 0, 1]" },
        { kind: "callout", tone: "warn", text: "Do NOT label-encode unordered features (like city) and feed them into a linear model. The model will read the integers as a number line and assume Paris (2) is 'bigger' than London (1)." },
        { kind: "heading", text: "One-hot encoding" },
        { kind: "prose", text: "Create one new 0/1 column per category. The right default for unordered categorical features." },
        { kind: "code", lang: "python", code: "df = pd.get_dummies(df, columns=[\"city\"], drop_first=True)" },
        { kind: "heading", text: "When categories are many" },
        { kind: "prose", text: "If a column has hundreds of categories (e.g. zip code), one-hot blows up the column count. Use frequency encoding or target encoding instead." },
        { kind: "keypoints", points: ["Models need numbers; categoricals must be encoded", "Label encoding: integers — use for targets or ordinal features", "One-hot encoding: a 0/1 column per category — for unordered features", "`pd.get_dummies` or `OneHotEncoder` does it in one call", "High-cardinality columns need smarter encoding"] },
        { kind: "practice", text: "Encode categoricals:", items: ["Label-encode the target `['spam', 'ham', 'spam']`.", "One-hot encode a `city` column with three values.", "Why is label-encoding `city` wrong for a linear model?", "Stretch: when would you choose target encoding over one-hot?"] },
      ],
    },
    {
      id: "ml-split",
      title: "Train/test split",
      summary: "Hold out unseen data so your evaluation means something.",
      blocks: [
        { kind: "prose", text: "If you score a model on the data it learned from, you are measuring memorization, not learning. The first rule of ML evaluation is: keep a chunk of data the model has never seen." },
        { kind: "heading", text: "The split" },
        { kind: "code", lang: "python", code: "from sklearn.model_selection import train_test_split\n\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y,\n    test_size=0.2,        # 20% test\n    random_state=42,      # reproducible split\n    stratify=y,           # preserve class balance\n)" },
        { kind: "heading", text: "Why `stratify=y`?" },
        { kind: "prose", text: "For classification with imbalanced classes, a random split can leave the rare class barely represented in test. `stratify=y` keeps the class ratio the same in both sets." },
        { kind: "heading", text: "Validation set" },
        { kind: "prose", text: "For serious tuning, split again: train / validation / test. Train on train, tune choices on validation, and only touch test once, at the very end, for the final score." },
        { kind: "callout", tone: "warn", text: "Never tune hyperparameters by peeking at the test set. The score stops being honest the moment you use test to make decisions." },
        { kind: "keypoints", points: ["Evaluation requires data the model has never seen", "`train_test_split` is the standard tool; 80/20 is a common ratio", "Set `random_state` for reproducibility", "Use `stratify=y` to preserve class balance in classification", "Test set is for the final score only — tune on a separate validation set"] },
        { kind: "practice", text: "Split data:", items: ["Split X, y into 80% train and 20% test with `random_state=42`.", "Add `stratify=y` and check the class ratios match.", "Why is using the test set to choose hyperparameters cheating?", "Stretch: why not train on all data and skip the split?"] },
      ],
    },
    {
      id: "ml-imbalance",
      title: "Imbalanced datasets",
      summary: "When one class dominates — and what to do about it.",
      blocks: [
        { kind: "prose", text: "If 99% of your transactions are legitimate, a model that always says 'not fraud' is 99% accurate and completely useless. Imbalanced classes need both better metrics and better strategies." },
        { kind: "heading", text: "Stop using accuracy alone" },
        { kind: "prose", text: "On imbalanced data, accuracy lies. Use precision, recall, F1, ROC-AUC, and a confusion matrix to see what the model is actually doing on the rare class." },
        { kind: "heading", text: "Resample the data" },
        { kind: "code", lang: "python", code: "# Oversample the minority\nfrom imblearn.over_sampling import SMOTE\nX_res, y_res = SMOTE(random_state=42).fit_resample(X_train, y_train)\n\n# Or undersample the majority\nfrom imblearn.under_sampling import RandomUnderSampler\nX_res, y_res = RandomUnderSampler(random_state=42).fit_resample(X_train, y_train)" },
        { kind: "heading", text: "Tell the model to care" },
        { kind: "prose", text: "Most sklearn classifiers accept `class_weight=\"balanced\"`, which makes the loss penalize errors on the rare class more heavily." },
        { kind: "code", lang: "python", code: "from sklearn.linear_model import LogisticRegression\nmodel = LogisticRegression(class_weight=\"balanced\")" },
        { kind: "callout", tone: "warn", text: "Only resample the training set, never the test set. Test data must reflect the true real-world class balance, or your score is fiction." },
        { kind: "keypoints", points: ["Accuracy is misleading when classes are imbalanced", "Use precision, recall, F1, and ROC-AUC instead", "Oversample the minority (SMOTE) or undersample the majority", "Or use `class_weight=\"balanced\"`", "Resample TRAIN only, never test"] },
        { kind: "practice", text: "Handle imbalance:", items: ["Given y where 95% are class 0, what accuracy does an always-0 model achieve?", "Name two metrics that would expose how poor it is.", "When would you prefer SMOTE over undersampling?", "Stretch: why must you never resample the test set?"] },
      ],
    },
    {
      id: "ml-tfidf",
      title: "Text features with TF-IDF",
      summary: "Turn documents into numeric vectors models can learn from.",
      blocks: [
        { kind: "prose", text: "Text is not numeric, so it cannot go straight into a model. TF-IDF (Term Frequency, Inverse Document Frequency) is the classical way to vectorize it." },
        { kind: "heading", text: "The idea" },
        { kind: "prose", text: "A word matters in a document if it appears often there (TF) but rarely across the whole corpus (IDF). Common filler words like 'the' get low weight; distinctive words get high weight." },
        { kind: "heading", text: "In sklearn" },
        { kind: "code", lang: "python", code: "from sklearn.feature_extraction.text import TfidfVectorizer\n\ndocs = [\"the cat sat on the mat\", \"the dog sat on the log\", \"cats and dogs\"]\nvec = TfidfVectorizer(stop_words=\"english\", max_features=1000)\nX = vec.fit_transform(docs)\n\nprint(X.shape)               # (3 docs, n features)\nprint(vec.get_feature_names_out())" },
        { kind: "heading", text: "Where it shines" },
        { kind: "prose", text: "TF-IDF + logistic regression is a strong baseline for spam, sentiment, and topic classification. Modern NLP uses embeddings (covered in the LLM phase), but TF-IDF is fast, interpretable, and still hard to beat on small text datasets." },
        { kind: "callout", tone: "tip", text: "Fit the TfidfVectorizer on training text only, then transform train AND test. Same rule as scaling: no peeking at test data when learning the vocabulary." },
        { kind: "keypoints", points: ["Text must be vectorized before training", "TF-IDF weights words by per-document frequency and corpus rarity", "`TfidfVectorizer` does it; `stop_words=\"english\"` removes filler", "TF-IDF + logistic regression is a strong text-classification baseline", "Fit on train only, transform both"] },
        { kind: "practice", text: "Vectorize text:", items: ["Fit `TfidfVectorizer` on three short documents and print the feature names.", "What does TF-IDF give 'the' a low weight?", "Why must you `fit_transform` on train but only `transform` test?", "Stretch: try `ngram_range=(1, 2)` and see how the vocabulary grows."] },
      ],
    },
  ],
};

export const preprocessingGuided: GuidedProblem[] = [
  {
    id: "ml-collect-g1",
    lessonId: "ml-collect",
    title: "Inspect a fresh dataset",
    prompt: "You just loaded a CSV. What three commands should you run first, and what does each tell you?",
    hints: ["Think shape, types, and values.", "`head`, `info`, `describe`."],
    solution: [
      { kind: "prose", text: "1) `df.head()` — peek at the first rows to sanity-check the load." },
      { kind: "prose", text: "2) `df.info()` — column names, dtypes, and non-null counts. Reveals missing data and wrong types." },
      { kind: "prose", text: "3) `df.describe()` — min/max/mean/std for numeric columns. Spot outliers and impossible values." },
    ],
  },
  {
    id: "ml-missing-g1",
    lessonId: "ml-missing",
    title: "Triage missing data",
    prompt: "A DataFrame has 1000 rows. Column A is missing 1% of values; column B is missing 60%. Recommend a handling strategy for each.",
    hints: ["Drop, impute, or remove the column?", "Decide based on how much is missing."],
    solution: [
      { kind: "prose", text: "Column A (1%): impute. Mean/median for numeric, mode for categorical. Dropping 10 rows out of 1000 also works." },
      { kind: "prose", text: "Column B (60%): drop the column. Imputing 60% of values invents far too much data, and any signal in the remaining 40% is likely confounded by the missingness itself." },
    ],
  },
  {
    id: "ml-scaling-g1",
    lessonId: "ml-scaling",
    title: "Scale features the right way",
    prompt: "Write the four lines that standardize features for a train/test split using StandardScaler.",
    hints: ["Fit on train; transform both.", "Never call `.fit()` on test data."],
    solution: [
      { kind: "code", lang: "python", code: "from sklearn.preprocessing import StandardScaler\nscaler = StandardScaler()\nX_train_s = scaler.fit_transform(X_train)\nX_test_s = scaler.transform(X_test)" },
      { kind: "prose", text: "Fitting on test would let the test distribution leak into training. The score would be inflated and dishonest." },
    ],
  },
  {
    id: "ml-encoding-g1",
    lessonId: "ml-encoding",
    title: "Pick the encoding",
    prompt: "For each feature, pick label encoding or one-hot: (a) target column 'spam'/'ham', (b) 'size' in {small, medium, large}, (c) 'city' with 50 values, (d) 'zipcode' with 5000 values.",
    hints: ["Ordered means label encoding can be fine. Unordered means one-hot.", "High cardinality breaks one-hot."],
    solution: [
      { kind: "prose", text: "(a) Label encoding. It's the target, integers are fine." },
      { kind: "prose", text: "(b) Label encoding (ordinal). size has a natural order: small < medium < large." },
      { kind: "prose", text: "(c) One-hot. City is unordered." },
      { kind: "prose", text: "(d) Neither cleanly. 5000 one-hot columns is too many; integers imply false ordering. Reach for target encoding or frequency encoding." },
    ],
  },
  {
    id: "ml-split-g1",
    lessonId: "ml-split",
    title: "A reproducible stratified split",
    prompt: "Split `X, y` 80/20 with a fixed random_state of 42 and preserve class proportions.",
    hints: ["`stratify=y` keeps class ratios identical in both sets.", "`random_state` makes the split reproducible."],
    solution: [
      { kind: "code", lang: "python", code: "from sklearn.model_selection import train_test_split\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.2, random_state=42, stratify=y,\n)" },
      { kind: "prose", text: "Without stratify, a rare class could end up barely represented in test, making the score noisy and unreliable." },
    ],
  },
  {
    id: "ml-imbalance-g1",
    lessonId: "ml-imbalance",
    title: "The 99% accuracy trap",
    prompt: "A fraud-detection dataset is 99% legitimate. A model achieves 99% accuracy. Should you ship it?",
    hints: ["What does an always-non-fraud baseline achieve?", "Which metrics actually measure detection?"],
    solution: [
      { kind: "prose", text: "No. A model that always predicts non-fraud also hits 99% accuracy and catches zero fraud. Accuracy is the wrong metric on imbalanced data." },
      { kind: "prose", text: "Use precision (of flagged transactions, how many were truly fraud?) and recall (of actual fraud, how many did we catch?). F1 and ROC-AUC combine them. Then consider SMOTE, class_weight='balanced', or threshold tuning to improve recall." },
    ],
  },
  {
    id: "ml-tfidf-g1",
    lessonId: "ml-tfidf",
    title: "Vectorize three documents",
    prompt: "Fit a TfidfVectorizer on `['the cat sat', 'the dog sat', 'cats and dogs']` with English stop words removed, then print the feature names and the matrix shape.",
    hints: ["`stop_words='english'` strips filler words.", "`.get_feature_names_out()` lists the vocabulary."],
    solution: [
      { kind: "code", lang: "python", code: "from sklearn.feature_extraction.text import TfidfVectorizer\ndocs = [\"the cat sat\", \"the dog sat\", \"cats and dogs\"]\nvec = TfidfVectorizer(stop_words=\"english\")\nX = vec.fit_transform(docs)\nprint(vec.get_feature_names_out())\nprint(X.shape)" },
      { kind: "prose", text: "Stop words like 'the' and 'and' are dropped, so the vocabulary focuses on content words." },
    ],
  },
];
