import type { Module, GuidedProblem } from "@/content/types";

export const toolkitModule: Module = {
  id: "ml-toolkit",
  title: "Data toolkit",
  lessons: [
    {
      id: "ml-numpy",
      title: "NumPy: arrays for ML",
      summary: "Fast numeric arrays — the foundation of every Python ML library.",
      blocks: [
        { kind: "prose", text: "Every ML library in Python sits on top of NumPy. Its `ndarray` stores numbers in a tight contiguous block, so math on a million values is far faster than a Python list, and the syntax is cleaner too." },
        { kind: "heading", text: "Creating arrays" },
        { kind: "code", lang: "python", code: "import numpy as np\n\na = np.array([1, 2, 3])           # from a list\nz = np.zeros((2, 3))              # 2x3 of zeros\no = np.ones(5)                    # 5 ones\nr = np.arange(0, 10, 2)           # [0 2 4 6 8]\nls = np.linspace(0, 1, 5)         # [0. 0.25 0.5 0.75 1.]" },
        { kind: "heading", text: "Shape, dtype, axes" },
        { kind: "prose", text: "Every array has a `.shape` (its size along each axis) and a `.dtype` (the kind of number stored). A 2D array's first axis is rows, second is columns." },
        { kind: "code", lang: "python", code: "m = np.array([[1, 2, 3], [4, 5, 6]])\nprint(m.shape)   # (2, 3)\nprint(m.dtype)   # int64" },
        { kind: "heading", text: "Vectorized math" },
        { kind: "prose", text: "Operations apply element-wise across the whole array, no Python loop needed. This is the speed secret." },
        { kind: "code", lang: "python", code: "a = np.array([1, 2, 3])\nprint(a * 2)        # [2 4 6]\nprint(a + a)        # [2 4 6]\nprint(a ** 2)       # [1 4 9]\nprint(np.sqrt(a))   # [1.   1.414 1.732]" },
        { kind: "heading", text: "Broadcasting" },
        { kind: "prose", text: "When shapes differ, NumPy broadcasts the smaller one to fit, with no copy. A scalar acts on every element; a row vector acts on every row of a matrix." },
        { kind: "code", lang: "python", code: "m = np.array([[1, 2, 3], [4, 5, 6]])\nprint(m + 10)            # adds 10 to every element\nprint(m + np.array([1, 2, 3]))  # adds row-wise" },
        { kind: "heading", text: "Indexing & slicing" },
        { kind: "code", lang: "python", code: "m = np.array([[1, 2, 3], [4, 5, 6]])\nprint(m[0, 1])      # 2     row 0, col 1\nprint(m[:, 0])      # [1 4] all rows, col 0\nprint(m[1, :])      # [4 5 6]\nprint(m[m > 3])     # [4 5 6] boolean mask" },
        { kind: "callout", tone: "tip", text: "Reach for NumPy whenever you'd otherwise write a `for` over numbers. A vectorized one-liner is usually 10-100x faster." },
        { kind: "keypoints", points: ["NumPy `ndarray` is contiguous, typed, and fast", "`.shape` and `.dtype` describe every array", "Math is element-wise (vectorized), no Python loop", "Broadcasting fits shapes together without copying", "Boolean masks filter values: `arr[arr > 3]`"] },
        { kind: "practice", text: "Use NumPy:", items: ["Create a 3x3 array of zeros, then add 5 to every element.", "Make an array `[1, 2, 3, 4, 5]` and print only the values greater than 2.", "Given `a = np.arange(10)`, slice out indexes 2 to 5.", "Stretch: compute `a * 2 + 1` for `a = np.arange(5)` in one expression."] },
      ],
    },
    {
      id: "ml-pandas",
      title: "pandas: DataFrames",
      summary: "Tabular data with labels — the daily driver for data work.",
      blocks: [
        { kind: "prose", text: "pandas adds labels to NumPy. A `DataFrame` is a table with named columns and an index, like a spreadsheet you can program. Almost all real ML starts by loading data into a DataFrame and cleaning it up." },
        { kind: "heading", text: "Series & DataFrame" },
        { kind: "code", lang: "python", code: "import pandas as pd\n\ns = pd.Series([10, 20, 30], name=\"age\")\n\ndf = pd.DataFrame({\n    \"name\": [\"Ada\", \"Linus\", \"Alan\"],\n    \"age\": [36, 54, 41],\n    \"role\": [\"eng\", \"eng\", \"sci\"],\n})\nprint(df)" },
        { kind: "heading", text: "Loading data" },
        { kind: "code", lang: "python", code: "df = pd.read_csv(\"data.csv\")\nprint(df.head())       # first 5 rows\nprint(df.shape)        # (rows, cols)\nprint(df.info())       # types and null counts\nprint(df.describe())   # summary stats for numerics" },
        { kind: "heading", text: "Selecting" },
        { kind: "code", lang: "python", code: "df[\"age\"]                    # one column -> Series\ndf[[\"name\", \"age\"]]          # two columns -> DataFrame\ndf.iloc[0]                   # row by position\ndf.loc[df[\"age\"] > 40]       # rows by condition" },
        { kind: "heading", text: "Cleaning & transforming" },
        { kind: "code", lang: "python", code: "df[\"age_decade\"] = df[\"age\"] // 10        # new column\ndf = df.dropna()                          # drop missing\ndf[\"age\"] = df[\"age\"].fillna(df[\"age\"].mean())  # fill missing\ndf = df.rename(columns={\"role\": \"team\"})" },
        { kind: "heading", text: "Grouping" },
        { kind: "code", lang: "python", code: "df.groupby(\"team\")[\"age\"].mean()" },
        { kind: "callout", tone: "tip", text: "`.head()`, `.info()`, and `.describe()` are the first three things to run on any new dataset. They tell you size, types, missing data, and ranges in seconds." },
        { kind: "keypoints", points: ["`DataFrame` is a labelled 2D table; `Series` is one column", "`read_csv` loads files; `head/info/describe` explore them", "Select columns by name, rows by position (`iloc`) or condition (`loc`)", "Clean with `dropna`, `fillna`, and column assignments", "`groupby` aggregates by category"] },
        { kind: "practice", text: "Try with a tiny DataFrame:", items: ["Build a DataFrame of 3 people with name, age, score columns.", "Print only the rows where score > 80.", "Add a new column `passed` = score >= 60.", "Stretch: group by `passed` and get the mean age per group."] },
      ],
    },
    {
      id: "ml-matplotlib",
      title: "matplotlib: plotting",
      summary: "The base plotting library — line, bar, scatter, histogram.",
      blocks: [
        { kind: "prose", text: "You cannot understand a dataset just by reading numbers. matplotlib lets you draw the essential plots in two or three lines." },
        { kind: "heading", text: "Basic plots" },
        { kind: "code", lang: "python", code: "import matplotlib.pyplot as plt\nimport numpy as np\n\nx = np.arange(10)\ny = x ** 2\n\nplt.plot(x, y)               # line\nplt.title(\"x squared\")\nplt.xlabel(\"x\")\nplt.ylabel(\"y\")\nplt.show()" },
        { kind: "heading", text: "The chart for each job" },
        { kind: "code", lang: "python", code: "plt.scatter(x, y)           # relationships between two numbers\nplt.bar([\"a\", \"b\", \"c\"], [1, 4, 2])   # categories\nplt.hist(data, bins=20)     # distribution of one variable" },
        { kind: "heading", text: "Subplots" },
        { kind: "code", lang: "python", code: "fig, ax = plt.subplots(1, 2, figsize=(8, 3))\nax[0].plot(x, y)\nax[1].hist(y)\nplt.show()" },
        { kind: "callout", tone: "note", text: "Use matplotlib when you want fine control. For prettier defaults and statistical plots, the next lesson covers seaborn, which sits on top." },
        { kind: "keypoints", points: ["`plt.plot` line, `plt.scatter` points, `plt.bar` categories, `plt.hist` distribution", "Always label axes and add a title", "`plt.subplots` arranges multiple plots in one figure", "Call `plt.show()` to render"] },
        { kind: "practice", text: "Plot something:", items: ["Plot `y = x ** 2` for x from 0 to 10.", "Make a histogram of 1000 random numbers from `np.random.randn(1000)`.", "Bar chart the counts of categories ['a','b','c'] with values [3, 7, 2].", "Stretch: put a line plot and a histogram side by side using subplots."] },
      ],
    },
    {
      id: "ml-seaborn",
      title: "seaborn: statistical plots",
      summary: "Pretty defaults and one-liners for the plots ML actually needs.",
      blocks: [
        { kind: "prose", text: "seaborn is matplotlib with better defaults and ready-made statistical plots. For exploring an ML dataset, it is the fastest way to see what is happening." },
        { kind: "heading", text: "Essential plots" },
        { kind: "code", lang: "python", code: "import seaborn as sns\nimport matplotlib.pyplot as plt\n\nsns.histplot(df[\"age\"])                    # distribution of one column\nsns.boxplot(x=\"team\", y=\"age\", data=df)    # spread per category\nsns.scatterplot(x=\"age\", y=\"score\", hue=\"team\", data=df)\nsns.heatmap(df.corr(numeric_only=True), annot=True)   # correlation matrix\nplt.show()" },
        { kind: "heading", text: "Pairplot: see everything at once" },
        { kind: "prose", text: "`sns.pairplot(df)` draws a scatter of every numeric column against every other, with histograms on the diagonal. One line, instant overview." },
        { kind: "callout", tone: "tip", text: "Before you train a model, run `sns.pairplot(df, hue=label_col)` to see how features relate to each other and to the target. It often reveals the right approach." },
        { kind: "keypoints", points: ["seaborn = prettier matplotlib + statistical plots", "`histplot`, `boxplot`, `scatterplot`, `heatmap` cover most exploration", "`pairplot` gives a fast overview of every pair of numeric columns", "Pass `hue=` to colour by a category"] },
        { kind: "practice", text: "Explore data with seaborn:", items: ["Plot a histogram of one numeric column from a DataFrame.", "Make a boxplot of a numeric column grouped by a category column.", "Draw the correlation heatmap of a DataFrame's numeric columns.", "Stretch: use `pairplot` with `hue=` to colour by a class label."] },
      ],
    },
  ],
};

export const toolkitGuided: GuidedProblem[] = [
  {
    id: "ml-numpy-g1",
    lessonId: "ml-numpy",
    title: "Vectorize a calculation",
    prompt: "Given `a = np.array([1, 2, 3, 4, 5])`, compute `2 * a + 1` without using a Python loop, then keep only the values greater than 5.",
    hints: ["Arithmetic on NumPy arrays is element-wise.", "Boolean masks filter: `arr[arr > 5]`."],
    solution: [
      { kind: "code", lang: "python", code: "import numpy as np\na = np.array([1, 2, 3, 4, 5])\nb = 2 * a + 1          # [ 3  5  7  9 11]\nprint(b[b > 5])        # [ 7  9 11]" },
      { kind: "prose", text: "Vectorized math runs in C under the hood, far faster than the equivalent Python loop." },
    ],
  },
  {
    id: "ml-pandas-g1",
    lessonId: "ml-pandas",
    title: "Filter, derive, group",
    prompt: "From a DataFrame with name, age, score columns: keep rows where score >= 60, add a column `decade = age // 10`, then print the mean score per decade.",
    hints: ["Boolean indexing with `df[df['score'] >= 60]` filters rows.", "`groupby` aggregates by category."],
    solution: [
      { kind: "code", lang: "python", code: "import pandas as pd\ndf = pd.DataFrame({\n    \"name\": [\"A\", \"B\", \"C\", \"D\"],\n    \"age\": [22, 35, 47, 29],\n    \"score\": [75, 55, 88, 91],\n})\n\npassed = df[df[\"score\"] >= 60].copy()\npassed[\"decade\"] = passed[\"age\"] // 10\nprint(passed.groupby(\"decade\")[\"score\"].mean())" },
      { kind: "prose", text: "Filter → derive → group is the staple pipeline for tabular data exploration." },
    ],
  },
  {
    id: "ml-matplotlib-g1",
    lessonId: "ml-matplotlib",
    title: "Plot and label",
    prompt: "Plot `y = x ** 2` for x from 0 to 10 with a title and axis labels.",
    hints: ["Generate x with `np.arange(11)` and compute y from it.", "`plt.title`, `plt.xlabel`, `plt.ylabel`, then `plt.show()`."],
    solution: [
      { kind: "code", lang: "python", code: "import numpy as np\nimport matplotlib.pyplot as plt\n\nx = np.arange(11)\ny = x ** 2\nplt.plot(x, y)\nplt.title(\"y = x^2\")\nplt.xlabel(\"x\")\nplt.ylabel(\"y\")\nplt.show()" },
      { kind: "prose", text: "Axis labels and a title turn a plot from a doodle into a chart someone else can read." },
    ],
  },
  {
    id: "ml-seaborn-g1",
    lessonId: "ml-seaborn",
    title: "Correlation heatmap",
    prompt: "Given a DataFrame `df` with several numeric columns, draw the correlation heatmap with values annotated on the cells.",
    hints: ["`df.corr(numeric_only=True)` produces the correlation matrix.", "`sns.heatmap(..., annot=True)` adds the values."],
    solution: [
      { kind: "code", lang: "python", code: "import seaborn as sns\nimport matplotlib.pyplot as plt\n\nsns.heatmap(df.corr(numeric_only=True), annot=True, cmap=\"coolwarm\")\nplt.show()" },
      { kind: "prose", text: "Strong positive or negative correlations near +/- 1 hint at features that may be redundant or predictive of the target." },
    ],
  },
];
