import type { Track, Flashcard, PredictOutput } from "@/content/types";

export const foundationsTrack: Track = {
  id: "cs-foundations",
  title: "Big-O & Data Structures",
  modules: [
    {
      id: "cs-complexity",
      title: "Algorithmic complexity",
      lessons: [
        {
          id: "bigo-intro",
          title: "Big-O notation",
          summary: "Describe how an algorithm scales as the input grows.",
          blocks: [
            { kind: "prose", text: "You wrote a function that works fine on 10 items. Will it still be fast on 10 million? That is the question Big-O answers. It describes how the *amount of work* an algorithm does grows as its input grows, so you can predict behaviour at scale before you ever run the code." },
            { kind: "heading", text: "Count steps, not seconds" },
            { kind: "prose", text: "Seconds depend on your laptop, the language, and what else is running. So we ignore all of that and count *steps* relative to the input size, which we always call `n`. Big-O is a statement about that growth, written like `O(n)` and read aloud as \"order n\"." },
            { kind: "heading", text: "A tale of two searches" },
            { kind: "prose", text: "Suppose you are looking for a name in a phone book. The clumsy way is to read every entry from the top until you hit the one you want." },
            { kind: "code", lang: "python", code: 'names = ["Ada", "Bob", "Cy", "Dee"]\nfor name in names:        # check them one at a time\n    if name == "Cy":\n        print("found it")' },
            { kind: "prose", text: "If the phone book doubles in size, you do roughly twice the work. The work grows in step with `n`: that is `O(n)`, linear time." },
            { kind: "prose", text: "The clever way uses the fact that a phone book is sorted: open the middle, decide which half your name is in, throw the other half away, and repeat." },
            { kind: "code", lang: "python", code: "# 1,000,000 sorted names, opening the middle each time:\n# step 1 -> 500,000 left\n# step 2 -> 250,000 left\n# step 3 -> 125,000 left\n# ... only about 20 steps to find ANY name" },
            { kind: "prose", text: "Halving the data each step is `O(log n)`. It barely grows even when `n` explodes. That is binary search, and it is the difference between 20 steps and a million." },
            { kind: "heading", text: "The growth classes to know" },
            { kind: "prose", text: "From slowest-growing (best) to fastest-growing (worst), these are the ones you will meet again and again:" },
            { kind: "code", lang: "python", code: "# O(1)        constant     one step, no matter how big n is\n# O(log n)    logarithmic   halve the work each step\n# O(n)        linear        one pass over the data\n# O(n log n)  log-linear    the good sorting algorithms\n# O(n^2)      quadratic     a loop inside a loop over the data" },
            { kind: "heading", text: "Why it actually matters" },
            { kind: "prose", text: "These differences are not academic. Picture an input of one million items and count the rough number of steps:" },
            { kind: "code", lang: "python", code: "# n = 1,000,000\n# O(1)      ~ 1 step\n# O(log n)  ~ 20 steps\n# O(n)      ~ 1,000,000 steps\n# O(n^2)    ~ 1,000,000,000,000 steps  (a trillion)" },
            { kind: "prose", text: "An `O(n^2)` algorithm that feels instant on 100 items can freeze your program on a million. Dropping to a lower Big-O class is often the single biggest speed-up available to you." },
            { kind: "callout", tone: "tip", text: "When an engineer says one approach is faster, they usually mean a lower Big-O class, even if it loses on tiny inputs. Growth wins as n gets large." },
            { kind: "callout", tone: "note", text: "Unless stated otherwise, Big-O describes the worst case. You will also hear best-case and average-case used for the same algorithm." },
            { kind: "keypoints", points: ["Big-O measures how work grows with input size `n`, ignoring constants and hardware", "We count steps relative to `n`, not seconds", "Best to worst: `O(1)` < `O(log n)` < `O(n)` < `O(n log n)` < `O(n^2)`", "Halving the data each step is `O(log n)`; a single pass is `O(n)`", "Nested loops over the data are usually `O(n^2)`", "A lower Big-O class beats faster hardware once `n` is large"] },
            { kind: "practice", text: "Name the Big-O for each. Assume `n` is the length of the list.", items: ["Printing only the first item of a list.", "Printing every item once, using a single loop.", "Printing every possible pair of items (a loop inside a loop).", "Looking up a key in a Python `dict`.", "Stretch: if an `O(n)` task takes 1 second at n = 1000, roughly how long at n = 2000? What about an `O(n^2)` task?"] },
          ],
        },
        {
          id: "bigo-analyze",
          title: "Analyzing your code",
          summary: "Look at code and name its Big-O class.",
          blocks: [
            { kind: "prose", text: "Knowing the Big-O classes is one thing; looking at a chunk of code and naming its class is the skill that actually shows up in interviews and in real work. Here is the recipe." },
            { kind: "heading", text: "Count the steps as a function of n" },
            { kind: "prose", text: "Walk through the code and ask how many operations run for an input of size `n`. A single loop over `n` items does `n` steps, so it is `O(n)`." },
            { kind: "code", lang: "python", code: "def print_all(items):\n    for x in items:   # runs n times\n        print(x)\n# n steps -> O(n)" },
            { kind: "heading", text: "Drop constants and smaller terms" },
            { kind: "prose", text: "Big-O cares about growth, not exact counts. A function that does a fixed number of steps regardless of `n` is `O(1)`, even if that fixed number is 2 or 200." },
            { kind: "code", lang: "python", code: "def first_and_last(items):\n    print(items[0])    # 1 step\n    print(items[-1])   # 1 step\n# 2 steps, but it never grows with n -> O(1), not O(2)" },
            { kind: "heading", text: "Loops: add or multiply?" },
            { kind: "prose", text: "Two loops one after another *add* (`O(n) + O(n) = O(n)`). A loop *inside* another loop *multiplies* (`O(n) x O(n) = O(n^2)`)." },
            { kind: "code", lang: "python", code: "# sequential -> O(n) + O(n) = O(n)\nfor x in items:\n    print(x)\nfor x in items:\n    print(x)\n\n# nested -> O(n) x O(n) = O(n^2)\nfor a in items:\n    for b in items:\n        print(a, b)" },
            { kind: "callout", tone: "tip", text: "A loop that halves its range each step (like binary search) is O(log n), not O(n). Watch for the data shrinking by a factor, not by one." },
            { kind: "keypoints", points: ["Count operations as a function of `n`", "A fixed number of steps is `O(1)`, whatever the constant", "Drop constants: `O(2n)` is `O(n)`", "Keep only the dominant term: `O(n^2 + n)` is `O(n^2)`", "Sequential loops add; nested loops multiply", "Halving each step is `O(log n)`"] },
            { kind: "practice", text: "Name the Big-O of each:", items: ["A single `for` loop over `n` items.", "Two separate `for` loops, one after the other.", "A `for` loop with another `for` loop inside it.", "A function that only reads `items[0]` and `items[-1]`.", "Stretch: a loop that does `n = n // 2` until n reaches 1."] },
          ],
        },
      ],
    },
    {
      id: "cs-linear",
      title: "Linear structures",
      lessons: [
        {
          id: "arrays",
          title: "Arrays & dynamic arrays",
          summary: "Why list operations cost what they cost.",
          blocks: [
            { kind: "prose", text: "The list is the data structure you will use most. Understanding how it stores data explains why some operations are nearly free and others quietly cost `O(n)`." },
            { kind: "heading", text: "Contiguous storage means instant access" },
            { kind: "prose", text: "An array keeps its items back-to-back in memory. Because the computer knows where the block starts, it can jump straight to `arr[i]` by doing a little arithmetic. That is why index access is `O(1)`." },
            { kind: "code", lang: "python", code: "nums = [10, 20, 30]\nprint(nums[0])    # 10  -> O(1)\nprint(nums[-1])   # 30  -> O(1)" },
            { kind: "heading", text: "Growing the list" },
            { kind: "prose", text: "A Python `list` is a *dynamic* array: it quietly reserves spare capacity, so most appends are instant. Once in a while it runs out and copies everything to a bigger block, but averaged out, append is `O(1)` (we call this amortized)." },
            { kind: "code", lang: "python", code: "nums = [10, 20, 30]\nnums.append(40)   # O(1) amortized\nnums.pop()        # O(1)  remove from the end" },
            { kind: "heading", text: "The cost of the front" },
            { kind: "prose", text: "Inserting or deleting near the front is `O(n)`, because every later item has to shift over by one to make room or close the gap." },
            { kind: "code", lang: "python", code: "nums = [10, 20, 30]\nnums.insert(0, 5)   # [5, 10, 20, 30] -> O(n), everything shifted right" },
            { kind: "code", lang: "python", code: "# operation costs at a glance\n# nums[i]            O(1)   read/write by index\n# nums.append(x)     O(1)   amortized, add to end\n# nums.pop()         O(1)   remove from end\n# nums.insert(0, x)  O(n)   shift everything right\n# x in nums          O(n)   scan until found" },
            { kind: "callout", tone: "tip", text: "Adding and removing at the END of a list is cheap; doing it at the FRONT is O(n). If you need fast front operations, use collections.deque." },
            { kind: "keypoints", points: ["Items are stored contiguously, so `arr[i]` is `O(1)`", "`append` and `pop` (at the end) are `O(1)` amortized", "Insert/delete at the front is `O(n)` (everything shifts)", "`x in list` scans the whole list: `O(n)`", "Python `list` is a dynamic array"] },
            { kind: "practice", text: "Reason about cost:", items: ["Append one item and insert one at the front. Which is more expensive, and why?", "Why is reading `nums[500]` no slower than reading `nums[0]`?", "How would you check if a value is in a list, and what is its Big-O?", "Stretch: why is `append` called O(1) *amortized* rather than just O(1)?"] },
          ],
        },
        {
          id: "linked-lists",
          title: "Linked lists",
          summary: "Nodes chained by pointers — cheap inserts, slow lookups.",
          blocks: [
            { kind: "prose", text: "A linked list trades the array's instant lookup for cheap edits. It is also the gateway to trees and graphs, so building one by hand pays off later." },
            { kind: "heading", text: "Nodes and pointers" },
            { kind: "prose", text: "Each node holds a value and a pointer to the `next` node. There is no contiguous block and no index; the chain only knows where it starts (the head)." },
            { kind: "code", lang: "python", code: "class Node:\n    def __init__(self, value):\n        self.value = value\n        self.next = None\n\n# build 1 -> 2 -> 3\nhead = Node(1)\nhead.next = Node(2)\nhead.next.next = Node(3)" },
            { kind: "heading", text: "Walking the list" },
            { kind: "prose", text: "Because there is no index, you reach an item by starting at the head and following `next` until you arrive. Reaching the k-th item is therefore `O(n)`." },
            { kind: "code", lang: "python", code: "node = head\nwhile node:\n    print(node.value)\n    node = node.next" },
            { kind: "heading", text: "Why use one?" },
            { kind: "prose", text: "The payoff is inserting or removing at the head in `O(1)`: you just repoint a pointer, with no shifting. An array would have to shift every element." },
            { kind: "code", lang: "python", code: "# add a new value at the front in O(1)\nnew = Node(0)\nnew.next = head\nhead = new        # 0 -> 1 -> 2 -> 3" },
            { kind: "callout", tone: "note", text: "Array vs linked list: arrays win on lookup (O(1) by index) and memory locality; linked lists win on insert/remove at the ends (O(1), no shifting). Pick based on which you do more." },
            { kind: "keypoints", points: ["Each node holds a value plus a `next` pointer", "No index math: reaching the k-th node is `O(n)`", "Insert/remove at the head is `O(1)` (just repoint)", "You traverse from the head following `next`", "Trades fast lookups for cheap edits at the ends"] },
            { kind: "practice", text: "Work with the Node class:", items: ["Extend the chain to add a 4th node (value 4) at the end, then print all values.", "Write a loop that counts the nodes in the list.", "Insert a new node with value 99 at the front in O(1).", "Stretch: write a function `find(head, target)` that returns True if a value is in the list."] },
          ],
        },
        {
          id: "stacks-queues",
          title: "Stacks & queues",
          summary: "LIFO and FIFO — the two everyday orderings.",
          blocks: [
            { kind: "prose", text: "Two of the most useful patterns in programming are just rules about which end you add to and remove from." },
            { kind: "heading", text: "Stack: last in, first out" },
            { kind: "prose", text: "A stack is LIFO, like a stack of plates: you add and remove from the same end (the top). A Python list does this perfectly with `append` and `pop`." },
            { kind: "code", lang: "python", code: 'stack = []\nstack.append("a")     # push\nstack.append("b")\nprint(stack.pop())    # "b"  (the last one in comes out first)' },
            { kind: "heading", text: "Queue: first in, first out" },
            { kind: "prose", text: "A queue is FIFO, like a line at a shop: you add at the back and remove from the front. Use `collections.deque` for this." },
            { kind: "code", lang: "python", code: 'from collections import deque\n\nqueue = deque()\nqueue.append("a")       # enqueue at the back\nqueue.append("b")\nprint(queue.popleft())  # "a"  (the first one in comes out first)' },
            { kind: "heading", text: "Why not a list for a queue?" },
            { kind: "prose", text: "You *could* use `list.pop(0)` to remove from the front, but that is `O(n)` because every other item shifts down. `deque.popleft()` is `O(1)`." },
            { kind: "callout", tone: "warn", text: "For a queue, always use collections.deque, not list.pop(0). The list version looks fine on small inputs and silently becomes a bottleneck on big ones." },
            { kind: "prose", text: "Where they show up: stacks model undo history, the browser back button, and how function calls nest. Queues model task schedulers and breadth-first search, which you will meet in the graphs lesson." },
            { kind: "keypoints", points: ["Stack = LIFO; a `list` with `append` / `pop`", "Queue = FIFO; `collections.deque` with `append` / `popleft`", "`deque.popleft()` is `O(1)`; `list.pop(0)` is `O(n)`", "Both push and pop in `O(1)` when used correctly", "Stacks: undo, back button, recursion. Queues: scheduling, BFS"] },
            { kind: "practice", text: "Build each:", items: ["Use a list as a stack to reverse the word 'cat': push each letter, then pop them all.", "Use a deque as a queue: enqueue three names, then dequeue them in order.", "Explain why `list.pop(0)` is a poor choice for a queue.", "Stretch: use a stack to check if the string '(())' has balanced parentheses."] },
          ],
        },
      ],
    },
    {
      id: "cs-hashing",
      title: "Hashing",
      lessons: [
        {
          id: "hash-tables",
          title: "Hash tables",
          summary: "Key-to-value maps with O(1) average lookup — dict and set.",
          blocks: [
            { kind: "prose", text: "If you remember one data structure for interviews, make it the hash table. It turns 'search through everything' into 'jump straight there', and it is the secret behind a huge number of fast solutions." },
            { kind: "heading", text: "Lookup by key in O(1)" },
            { kind: "prose", text: "A hash table runs the key through a hash function that points to the slot where its value lives. No scanning, so lookup, insert, and update are `O(1)` on average. Python's `dict` is a hash table." },
            { kind: "code", lang: "python", code: 'ages = {"ada": 36, "linus": 54}\nprint(ages["ada"])   # 36   -> O(1) average\nages["alan"] = 41    # insert -> O(1) average' },
            { kind: "heading", text: "Sets: membership and de-duping" },
            { kind: "prose", text: "A `set` is a hash table with keys but no values. It answers \"have I seen this?\" in `O(1)` and removes duplicates for free." },
            { kind: "code", lang: "python", code: "seen = {1, 2, 2, 3}   # {1, 2, 3}  duplicates dropped\nprint(3 in seen)      # True       O(1) membership\nprint(set([1, 1, 2])) # {1, 2}     de-dupe a list" },
            { kind: "heading", text: "Collisions, the honest caveat" },
            { kind: "prose", text: "Sometimes two keys hash to the same slot, a collision. Python resolves these internally, so you rarely think about it. Lookups degrade to `O(n)` only in a contrived worst case, not in normal use." },
            { kind: "heading", text: "Keys must be hashable" },
            { kind: "prose", text: "Only immutable values can be keys, because the hash must not change. Strings, numbers, and tuples work; lists do not." },
            { kind: "code", lang: "python", code: 'ok = {(0, 0): "origin"}   # a tuple key is fine\n# bad = {[0, 0]: "x"}     # TypeError: list is unhashable' },
            { kind: "callout", tone: "tip", text: "When a problem says 'have I seen this before?', 'count how many times', or 'find the pair that adds to X', reach for a set or dict first. It usually turns an O(n^2) scan into O(n)." },
            { kind: "keypoints", points: ["`dict`/`set` give `O(1)` average lookup, insert, and membership", "A hash function maps the key straight to its slot", "Collisions are handled internally; worst case is rare", "Keys must be hashable (immutable): `str`, `int`, `tuple`", "Reach for a hash table on 'seen before?' and 'count' problems"] },
            { kind: "practice", text: "Use dicts and sets:", items: ["Count how many times each letter appears in 'banana' using a dict.", "Given a list with duplicates, produce the unique values using a set.", "Check whether two words are anagrams using letter counts.", "Stretch: given a list of numbers and a target, find if any two add up to it using a set (in O(n))."] },
          ],
        },
      ],
    },
  ],
};

export const foundationsFlashcards: Flashcard[] = [
  { id: "bigo-intro-fc-1", lessonId: "bigo-intro", front: "What does Big-O notation describe?", back: "How an algorithm's amount of work grows as the input size `n` grows, ignoring constants and hardware." },
  { id: "bigo-intro-fc-2", lessonId: "bigo-intro", front: "Order fastest to slowest: O(n), O(1), O(n^2), O(log n)", back: "`O(1)` < `O(log n)` < `O(n)` < `O(n^2)`." },
  { id: "bigo-intro-fc-3", lessonId: "bigo-intro", front: "Halving the search space each step is which complexity?", back: "`O(log n)` — like binary search. About 20 steps for a million items." },
  { id: "bigo-analyze-fc-1", lessonId: "bigo-analyze", front: "When finding Big-O, what happens to constants and lower-order terms?", back: "Drop them. Keep only the dominant term, so `O(2n + 5)` is just `O(n)`." },
  { id: "bigo-analyze-fc-2", lessonId: "bigo-analyze", front: "Two loops nested over `n` items is what complexity?", back: "`O(n^2)` — for each of n items you do n more steps. Sequential loops would only add." },
  { id: "arrays-fc-1", lessonId: "arrays", front: "Time to read `arr[i]` by index?", back: "`O(1)`, constant. Items are stored contiguously, so the address is computed directly." },
  { id: "arrays-fc-2", lessonId: "arrays", front: "Why is appending to a Python `list` O(1) amortized?", back: "The list over-allocates capacity, so most appends are instant; the occasional resize averages out." },
  { id: "linked-lists-fc-1", lessonId: "linked-lists", front: "Cost to reach the k-th node of a linked list?", back: "`O(n)` — you must follow `next` pointers from the head." },
  { id: "linked-lists-fc-2", lessonId: "linked-lists", front: "One thing a linked list does better than an array?", back: "Insert or remove at the head in `O(1)`, with no shifting of other elements." },
  { id: "stacks-queues-fc-1", lessonId: "stacks-queues", front: "Stack order vs queue order?", back: "Stack is LIFO (last in, first out); queue is FIFO (first in, first out)." },
  { id: "stacks-queues-fc-2", lessonId: "stacks-queues", front: "Which Python type gives O(1) removal from both ends?", back: "`collections.deque`. Using `list.pop(0)` for a queue is `O(n)`." },
  { id: "hash-tables-fc-1", lessonId: "hash-tables", front: "Average lookup time in a hash table (dict/set)?", back: "`O(1)` on average. A hash function maps the key straight to its slot." },
  { id: "hash-tables-fc-2", lessonId: "hash-tables", front: "What must be true of a `dict` key?", back: "It must be hashable, usually meaning immutable: `str`, `int`, `tuple` work; a `list` does not." },
];

export const foundationsPredict: PredictOutput[] = [
  { id: "bigo-analyze-po-1", lessonId: "bigo-analyze", code: "count = 0\nfor i in range(3):\n    for j in range(3):\n        count += 1\nprint(count)", options: ["9", "6", "3", "27"], answer: 0, explanation: "The inner loop runs 3 times for each of the 3 outer iterations: 3 x 3 = 9. That multiplication is why nested loops are O(n^2)." },
  { id: "arrays-po-1", lessonId: "arrays", code: "xs = [1, 2, 3]\nxs.insert(0, 0)\nprint(xs)", options: ["[0, 1, 2, 3]", "[1, 2, 3, 0]", "[0, 1, 2]", "Error"], answer: 0, explanation: "insert(0, 0) puts 0 at the front and shifts the rest right — an O(n) operation." },
  { id: "linked-lists-po-1", lessonId: "linked-lists", code: "class Node:\n    def __init__(self, v):\n        self.v = v\n        self.next = None\n\na = Node(1)\na.next = Node(2)\nprint(a.next.v)", options: ["2", "1", "None", "Error"], answer: 0, explanation: "a.next points to the second node, whose value v is 2." },
  { id: "stacks-queues-po-1", lessonId: "stacks-queues", code: "s = [1, 2, 3]\ns.append(4)\nprint(s.pop())", options: ["4", "1", "3", "[1, 2, 3]"], answer: 0, explanation: "pop() removes and returns the last item (LIFO), which is the 4 just appended." },
  { id: "hash-tables-po-1", lessonId: "hash-tables", code: 'd = {}\nd["x"] = 1\nd["x"] = 2\nprint(len(d))', options: ["1", "2", "0", "Error"], answer: 0, explanation: "Assigning the same key again overwrites the value, so the dict still has just one key." },
];