import type { Track } from "@/content/types";

export const pythonTrack: Track = {
  id: "python",
  title: "Python Foundations",
  modules: [
    {
      id: "py-getting-started",
      title: "Getting started",
      lessons: [
        {
          id: "py-vars",
          title: "Variables & data types",
          summary: "Store data in named variables and know Python's core types.",
          blocks: [
            { kind: "prose", text: "Every program needs to remember things: a username, a score, whether someone is logged in. A variable is how Python holds a value and gives it a name you can reuse." },
            { kind: "heading", text: "Making a variable" },
            { kind: "prose", text: "You create a variable with `=`: the name on the left, the value on the right. Unlike many languages you do not declare a type first, Python reads the value and works out the type for you." },
            { kind: "code", lang: "python", code: 'name = "Ada"        # str   text in quotes\nage = 36            # int   whole number\nheight = 1.7        # float has a decimal point\nis_student = True   # bool  True or False' },
            { kind: "prose", text: "Read `=` as 'gets', not 'equals': `age = 36` means age gets the value 36. The name now points to that value, and you can use it anywhere." },
            { kind: "code", lang: "python", code: 'print(f"{name} is {age} years old")   # Ada is 36 years old' },
            { kind: "heading", text: "The four core types" },
            { kind: "prose", text: "Almost everything you store early on is one of four basic types. A `str` is text wrapped in quotes, an `int` is a whole number, a `float` has a decimal point, and a `bool` is either `True` or `False` (note the capital letters)." },
            { kind: "heading", text: "Names follow the value" },
            { kind: "prose", text: "Python is dynamically typed: a name is just a label, so the same name can later point to a value of a different type. Use `type()` to check what a value is right now." },
            { kind: "code", lang: "python", code: "x = 5\nprint(type(x))   # <class 'int'>\nx = \"now text\"\nprint(type(x))   # <class 'str'>" },
            { kind: "callout", tone: "note", text: "Variable names use lowercase_with_underscores, must start with a letter or underscore, and are case-sensitive (`age` and `Age` are different names). Avoid Python keywords like `class` or `if`." },
            { kind: "callout", tone: "warn", text: "`=` assigns, `==` compares. `age = 36` stores 36; `age == 36` asks a True/False question. Swapping the two is a classic early bug." },
            { kind: "keypoints", points: ["Create a variable with `=`: `name = value`", "No type declarations, Python infers the type from the value", "Four core types: `str`, `int`, `float`, `bool`", "`True` and `False` are capitalised", "A name can be reassigned to a different type later", "`type(x)` checks a value; `=` assigns, `==` compares"] },
            { kind: "practice", text: "Open a Python file or the REPL and try these:", items: ["Create `name`, `age`, and `favourite_number`, then print all three in one f-string.", "Print the `type()` of each of your three variables.", "Reassign `age` to the text 'thirty' and print its type again. What changed?", "Predict before running: what type is `7 / 2`? Check with `type(7 / 2)`."] },
          ],
        },
        {
          id: "py-ops",
          title: "Operators",
          summary: "Do math, compare values, and combine conditions.",
          blocks: [
            { kind: "prose", text: "Once you can store values, you want to do things with them: arithmetic, comparisons, and combining yes/no conditions. Those tools are called operators." },
            { kind: "heading", text: "Arithmetic" },
            { kind: "prose", text: "The basics work as you would expect, but three operators surprise beginners: `/`, `//`, and `%`." },
            { kind: "code", lang: "python", code: "print(7 + 2)    # 9\nprint(7 / 2)    # 3.5   division always gives a float\nprint(7 // 2)   # 3     floor division, drops the remainder\nprint(7 % 2)    # 1     remainder (modulo)\nprint(2 ** 3)   # 8     power (2 to the 3rd)" },
            { kind: "prose", text: "`%` (remainder) and `//` (whole groups) are more useful than they first look: `%` tells you even vs odd, and `//` tells you how many full groups fit." },
            { kind: "code", lang: "python", code: "print(17 % 5)    # 2   what is left over\nprint(17 // 5)   # 3   how many whole groups of 5 fit\nprint(10 % 2)    # 0   even numbers leave no remainder" },
            { kind: "heading", text: "Comparisons" },
            { kind: "prose", text: "A comparison asks a question and answers with a `bool` (`True` or `False`)." },
            { kind: "code", lang: "python", code: "print(5 == 5)   # True   equal?\nprint(5 != 3)   # True   not equal?\nprint(2 > 7)    # False  greater than?\nprint(8 >= 8)   # True   greater than or equal?" },
            { kind: "heading", text: "Combining conditions" },
            { kind: "prose", text: "Use `and`, `or`, `not` to join conditions. `and` needs both sides true, `or` needs at least one, and `not` flips the answer." },
            { kind: "code", lang: "python", code: "age = 20\nprint(age >= 18 and age < 65)   # True   (both hold)\nprint(age < 13 or age > 65)     # False  (neither holds)\nprint(not age == 20)            # False  (flips True)" },
            { kind: "callout", tone: "warn", text: "`==` compares, `=` assigns. Writing `if age = 18:` is an error; you want `if age == 18:`." },
            { kind: "keypoints", points: ["`+ - * /` plus `//` (floor), `%` (remainder), `**` (power)", "`/` always gives a `float`; `//` drops the fraction", "`%` gives the remainder, great for even/odd and grouping", "Comparisons (`==`, `!=`, `<`, `>=`) return `True`/`False`", "Combine conditions with `and`, `or`, `not`", "`==` compares values; `=` assigns"] },
            { kind: "practice", text: "Try each in the REPL:", items: ["Check whether a number is even using `%` (even numbers give `0`).", "Given an `age`, print whether the person is a teenager (13 to 19) using `and`.", "Use `//` to find how many whole weeks are in 100 days.", "Predict then check: what does `2 ** 3 + 1` give, and why does the power happen first?"] },
          ],
        },
        {
          id: "py-io",
          title: "Input & output",
          summary: "Read input from the user and print results cleanly.",
          blocks: [
            { kind: "prose", text: "A program that cannot talk to you is no fun. `print()` sends text out to the screen, and `input()` reads a line of text back in." },
            { kind: "heading", text: "Printing" },
            { kind: "prose", text: "`print()` can take several values and puts a space between them. For clean output that mixes text and values, reach for an f-string: put an `f` before the quotes and `{}` around any value." },
            { kind: "code", lang: "python", code: 'print("Hello", "world")            # Hello world  (space between args)\n\nname, score = "Ada", 95\nprint(f"{name} scored {score}%")   # Ada scored 95%' },
            { kind: "heading", text: "Reading input" },
            { kind: "prose", text: "`input()` shows an optional prompt and returns whatever the user typed, always as a `str`." },
            { kind: "code", lang: "python", code: 'name = input("Your name: ")\nprint("Hi,", name)' },
            { kind: "heading", text: "Converting input to numbers" },
            { kind: "prose", text: "Because `input()` gives you text, you must convert it before doing math. Use `int()` for whole numbers and `float()` for decimals." },
            { kind: "code", lang: "python", code: 'age = int(input("Your age: "))   # text -> int\nprint("Next year you will be", age + 1)' },
            { kind: "callout", tone: "warn", text: "Forgetting to convert `input()` is the number one beginner bug. `\"5\" + 1` raises an error, but `int(\"5\") + 1` gives 6." },
            { kind: "code", lang: "python", code: 'print(int("42") + 1)        # 43\nprint(float("3.5") * 2)     # 7.0\nprint("Score: " + str(95))  # Score: 95' },
            { kind: "keypoints", points: ["`print(a, b)` prints arguments separated by spaces", "f-strings put values into text: an `f` before the quotes, `{value}` inside", "`input()` always returns a `str`", "Convert with `int()`, `float()`, `str()` before doing math", "Forgetting to convert input is the most common early bug"] },
            { kind: "practice", text: "Build these tiny programs:", items: ["Ask the user for two numbers and print their sum (convert first).", "Ask for a name, then greet them with an f-string.", "Ask for an age and print how old they will be in 10 years.", "Predict then check: what does `'5' + '5'` print, and how does it differ from `5 + 5`?"] },
          ],
        },
        {
          id: "py-cond",
          title: "Conditionals",
          summary: "Make decisions with if / elif / else.",
          blocks: [
            { kind: "prose", text: "Programs get interesting when they make decisions: do this when a condition holds, otherwise do that. That is what `if` / `elif` / `else` are for." },
            { kind: "heading", text: "if / elif / else" },
            { kind: "prose", text: "`if` runs its indented block when a condition is `True`. `elif` (else-if) offers another condition to try, and `else` is the catch-all when nothing above matched." },
            { kind: "code", lang: "python", code: 'score = 72\nif score >= 90:\n    print("A")\nelif score >= 60:\n    print("Pass")\nelse:\n    print("Try again")' },
            { kind: "heading", text: "Only the first match runs" },
            { kind: "prose", text: "Python checks the conditions top to bottom and runs the block of the first one that is `True`, then skips the rest. Order matters." },
            { kind: "code", lang: "python", code: 'x = 5\nif x > 3:\n    print("big")\nelif x > 4:          # never runs: x > 3 already matched\n    print("bigger")' },
            { kind: "heading", text: "Indentation is the syntax" },
            { kind: "callout", tone: "warn", text: "The indented lines under `if` are the block that runs. Python uses 4 spaces, and mixing tabs with spaces or indenting inconsistently is an error, not just bad style." },
            { kind: "prose", text: "Conditions are really just `bool` values, and Python treats some values as falsy: `0`, an empty string, and an empty list all act like `False`." },
            { kind: "code", lang: "python", code: 'name = ""\nif name:\n    print("got a name")\nelse:\n    print("name is empty")   # this runs: empty string is falsy' },
            { kind: "keypoints", points: ["`if` runs its block when the condition is `True`", "`elif` is checked only if earlier conditions were `False`", "`else` runs when nothing above matched", "Only the first matching branch runs", "Indent blocks with 4 spaces, it is part of the syntax", "Empty values like `0`, an empty string, or `[]` are falsy"] },
            { kind: "practice", text: "Write and run each:", items: ["A grader: given a score 0 to 100, print A, B, C, or Fail.", "Print whether a number is `Even` or `Odd`.", "Given a number, print `positive`, `negative`, or `zero`.", "Predict then check: for `x = 5`, why does the `elif x > 4` branch never run?"] },
          ],
        },
      ],
    },
    {
      id: "py-flow",
      title: "Control flow & functions",
      lessons: [
        {
          id: "py-loops",
          title: "Loops",
          summary: "Repeat work with for and while loops.",
          blocks: [
            { kind: "prose", text: "Computers are brilliant at doing the same thing over and over without getting bored. A loop is how you tell Python to repeat work." },
            { kind: "heading", text: "for: once per item" },
            { kind: "prose", text: "A `for` loop runs its block once for each item in a sequence, like a list or a string. The loop variable takes each value in turn." },
            { kind: "code", lang: "python", code: 'for fruit in ["apple", "pear", "fig"]:\n    print(fruit)\n\nfor letter in "hi":\n    print(letter)   # h, then i' },
            { kind: "heading", text: "range: counting" },
            { kind: "prose", text: "When you just need numbers, `range` generates them. `range(n)` is 0 up to but not including n; `range(start, stop)` lets you choose where to begin." },
            { kind: "code", lang: "python", code: "for i in range(3):\n    print(i)        # 0, 1, 2\n\nfor i in range(2, 5):\n    print(i)        # 2, 3, 4" },
            { kind: "heading", text: "while: repeat until done" },
            { kind: "prose", text: "A `while` loop repeats as long as its condition stays `True`. Something inside must move toward making it `False`, or the loop never ends." },
            { kind: "code", lang: "python", code: 'count = 3\nwhile count > 0:\n    print(count)\n    count = count - 1   # this is what eventually stops the loop\nprint("Liftoff!")' },
            { kind: "heading", text: "break and continue" },
            { kind: "prose", text: "`break` exits the loop immediately. `continue` skips the rest of this round and jumps to the next item." },
            { kind: "code", lang: "python", code: "for i in range(5):\n    if i == 3:\n        break       # stop the loop entirely\n    print(i)        # 0, 1, 2\n\nfor i in range(5):\n    if i % 2 == 0:\n        continue    # skip even numbers\n    print(i)        # 1, 3" },
            { kind: "callout", tone: "warn", text: "An infinite loop happens when a `while` condition never becomes False. If your program hangs, check that something inside the loop actually changes the condition." },
            { kind: "keypoints", points: ["`for x in seq:` runs once per item", "`range(n)` is 0…n-1; `range(a, b)` starts at a", "`while cond:` repeats while the condition is `True`", "`break` exits the loop; `continue` skips to the next round", "A `while` must change something or it loops forever"] },
            { kind: "practice", text: "Write each with a loop:", items: ["Print the 7 times-table (7x1 through 7x10) using `range`.", "Add up the numbers 1 to 100 and print the total.", "Print only the odd numbers from 1 to 20 using `continue`.", "Walk a list of numbers and `break` at the first one greater than 50."] },
          ],
        },
        {
          id: "py-funcs",
          title: "Functions",
          summary: "Package reusable logic into named functions.",
          blocks: [
            { kind: "prose", text: "When you catch yourself writing the same lines again, wrap them in a function. Name the logic once, then reuse it as many times as you like." },
            { kind: "heading", text: "Defining and calling" },
            { kind: "prose", text: "Define a function with `def`, list its inputs (parameters) in the parentheses, and send a result back with `return`. Call it by name with arguments." },
            { kind: "code", lang: "python", code: 'def greet(name):\n    return f"Hello, {name}!"\n\nmessage = greet("Ada")\nprint(message)   # Hello, Ada!' },
            { kind: "heading", text: "Parameters and arguments" },
            { kind: "prose", text: "Parameters are the placeholder names in the definition; arguments are the actual values you pass in. By default they match up by position." },
            { kind: "code", lang: "python", code: "def add(a, b):\n    return a + b\n\nprint(add(2, 3))   # 5   (a=2, b=3)" },
            { kind: "heading", text: "Default values" },
            { kind: "prose", text: "Give a parameter a default and it becomes optional: callers can leave it out." },
            { kind: "code", lang: "python", code: "def power(base, exp=2):\n    return base ** exp\n\nprint(power(5))      # 25    (uses default exp=2)\nprint(power(2, 10))  # 1024" },
            { kind: "heading", text: "return vs print" },
            { kind: "prose", text: "This trips up beginners: `return` hands a value back to the caller so you can use it later; `print` only shows text on screen. A function with no `return` gives back `None`." },
            { kind: "code", lang: "python", code: 'def double(n):\n    return n * 2\n\ndef shout(text):\n    print(text.upper())   # shows text, returns nothing\n\nx = double(5)      # x is 10, ready to use\ny = shout("hi")    # prints HI, but y is None' },
            { kind: "callout", tone: "tip", text: "Use `return` for values your program will keep working with. Use `print` only when the point is to show something to the user." },
            { kind: "keypoints", points: ["`def name(params):` defines a function", "`return` sends a value back; no `return` means `None`", "Call it with `name(args)`", "Arguments match parameters by position", "Parameters can have default values", "`return` gives a value back; `print` only displays text"] },
            { kind: "practice", text: "Write these functions:", items: ["`is_even(n)` that returns `True`/`False`, then use it in a loop over 1 to 10.", "`greet(name, greeting=\"Hello\")` with a default greeting.", "`bigger(a, b)` that returns the larger of two numbers.", "In one sentence, explain the difference between `return` and `print`."] },
          ],
        },
      ],
    },
    {
      id: "py-data",
      title: "Data structures",
      lessons: [
        {
          id: "py-lists",
          title: "Lists",
          summary: "Store ordered collections you can change.",
          blocks: [
            { kind: "prose", text: "A list holds an ordered sequence of items, written in `[]`. It is the workhorse collection: anything you have several of usually goes in a list." },
            { kind: "heading", text: "Creating and indexing" },
            { kind: "prose", text: "Index from 0 for the first item. Negative indexes count from the end, so `-1` is the last item." },
            { kind: "code", lang: "python", code: "nums = [10, 20, 30]\nprint(nums[0])    # 10  (first)\nprint(nums[-1])   # 30  (last)" },
            { kind: "heading", text: "Changing a list" },
            { kind: "prose", text: "Lists are mutable, so you can grow, shrink, and edit them in place." },
            { kind: "code", lang: "python", code: "nums = [10, 20, 30]\nnums.append(40)   # [10, 20, 30, 40]   add to the end\nnums[0] = 99      # [99, 20, 30, 40]   change an item\nnums.pop()        # removes and returns 40\nprint(len(nums))  # 3" },
            { kind: "heading", text: "Slicing" },
            { kind: "prose", text: "A slice `seq[start:stop]` returns a new sub-list. The `stop` index is excluded." },
            { kind: "code", lang: "python", code: 'letters = ["a", "b", "c", "d"]\nprint(letters[1:3])  # [\'b\', \'c\']\nprint(letters[:2])   # [\'a\', \'b\']  (from the start)\nprint(letters[2:])   # [\'c\', \'d\']  (to the end)' },
            { kind: "heading", text: "Looping a list" },
            { kind: "prose", text: "Loop the items directly, or use `enumerate` when you also want each item's index." },
            { kind: "code", lang: "python", code: 'for i, value in enumerate(["a", "b"]):\n    print(i, value)   # 0 a, then 1 b' },
            { kind: "keypoints", points: ["Lists are ordered and mutable: `[1, 2, 3]`", "Index from 0; `-1` is the last item", "`.append()`, `.pop()`, item assignment, `len()`", "Slicing: `seq[start:stop]` (stop excluded)", "`enumerate(seq)` gives index and value together"] },
            { kind: "practice", text: "Try each:", items: ["Make a list of 5 numbers, then print only the last three using a slice.", "Append two items, then remove the last one with `.pop()`.", "Sum a list of numbers with a `for` loop (no built-in `sum`).", "Build a list of the squares of 1 to 5 using a loop and `.append()`."] },
          ],
        },
        {
          id: "py-strings",
          title: "Strings",
          summary: "Work with text.",
          blocks: [
            { kind: "prose", text: "Strings are sequences of characters, and a huge amount of real programming is just shaping text: names, messages, file contents, user input." },
            { kind: "heading", text: "Strings are sequences" },
            { kind: "prose", text: "You can index and slice a string exactly like a list." },
            { kind: "code", lang: "python", code: 's = "Python"\nprint(s[0])    # P\nprint(s[-1])   # n\nprint(s[:3])   # Pyt\nprint(len(s))  # 6' },
            { kind: "heading", text: "Strings are immutable" },
            { kind: "prose", text: "You cannot change a character in place. Instead, string methods return a brand new string and leave the original untouched." },
            { kind: "code", lang: "python", code: 's = "python"\nprint(s.upper())   # PYTHON\nprint(s)           # python   (unchanged)' },
            { kind: "heading", text: "Useful methods" },
            { kind: "prose", text: "A handful of methods cover most everyday text work." },
            { kind: "code", lang: "python", code: 'print("  hi  ".strip())          # "hi"        trim spaces\nprint("a,b,c".split(","))        # [\'a\', \'b\', \'c\']\nprint("-".join(["a", "b"]))      # "a-b"\nprint("cat".replace("c", "b"))   # "bat"' },
            { kind: "callout", tone: "tip", text: "Because methods return new strings, you can chain them: `name.strip().lower()` trims and lowercases in one go." },
            { kind: "keypoints", points: ["Strings are immutable sequences of characters", "Index and slice them like lists", "Methods return a NEW string: `.strip()`, `.lower()`, `.upper()`", "`.split(sep)` makes a list; `sep.join(list)` makes a string", "Chain methods: `text.strip().lower()`"] },
            { kind: "practice", text: "Work with text:", items: ["Take a messy name like '  aDA  ' and print it trimmed and capitalised.", "Count the words in a sentence using `.split()` and `len()`.", "Reverse a string with the slice `s[::-1]`.", "Check whether a word contains the letter 'z' using `in`."] },
          ],
        },
        {
          id: "py-dicts",
          title: "Dictionaries, sets & tuples",
          summary: "Key-value maps, unique sets, and immutable tuples.",
          blocks: [
            { kind: "prose", text: "Lists are great when order matters. But often you want to look data up by a label, keep only unique values, or group a few fixed values together. That is what dicts, sets, and tuples are for." },
            { kind: "heading", text: "Dictionaries: look up by key" },
            { kind: "prose", text: "A dictionary maps keys to values. You read and write by key, not by position." },
            { kind: "code", lang: "python", code: 'user = {"name": "Ada", "age": 36}\nprint(user["name"])                 # Ada\nprint(user.get("city", "unknown"))  # unknown  (safe default)\nuser["age"] = 37                    # update\nuser["city"] = "London"             # add' },
            { kind: "prose", text: "Loop over a dict with `.items()` to get each key and value together." },
            { kind: "code", lang: "python", code: 'for key, value in user.items():\n    print(key, "->", value)' },
            { kind: "callout", tone: "warn", text: "Reading a missing key with `user[\"nope\"]` raises a KeyError. Use `user.get(key, default)` or check `key in user` first." },
            { kind: "heading", text: "Sets: unique items" },
            { kind: "prose", text: "A `set` holds unique items in no particular order. It is perfect for removing duplicates and for fast membership tests." },
            { kind: "code", lang: "python", code: "seen = {1, 2, 2, 3}   # {1, 2, 3}   duplicates dropped\nprint(3 in seen)      # True        fast membership\nprint(set([1, 1, 2]))  # {1, 2}      de-dupe a list" },
            { kind: "heading", text: "Tuples: fixed groups" },
            { kind: "prose", text: "A `tuple` is like a list that cannot change. Use it for a fixed group of values, such as a coordinate." },
            { kind: "code", lang: "python", code: "point = (4, 5)\nprint(point[0])   # 4\nx, y = point      # unpack into two variables\n# point[0] = 9    # error: tuples are immutable" },
            { kind: "keypoints", points: ["`dict`: `{key: value}`, read with `d[key]` or `d.get(key, default)`", "`.items()` loops keys and values together", "Missing key with `d[key]` raises KeyError", "`set`: unique items, fast `in` checks, de-dupes a list", "`tuple`: an immutable list, `(a, b)`, supports unpacking"] },
            { kind: "practice", text: "Try each:", items: ["Build a dict mapping 3 friends to their ages, then print each on its own line.", "Count how many times each letter appears in 'banana' using a dict and `.get()`.", "Remove duplicates from `[1, 1, 2, 3, 3]` using a `set`.", "Make a `(latitude, longitude)` tuple and unpack it into two variables."] },
          ],
        },
        {
          id: "py-compr",
          title: "Comprehensions",
          summary: "Build lists and dicts concisely.",
          blocks: [
            { kind: "prose", text: "A comprehension is a compact, readable way to build a new list (or dict) from an existing sequence. Once it clicks, you will reach for it constantly." },
            { kind: "heading", text: "List comprehension" },
            { kind: "prose", text: "These two snippets do exactly the same thing. The comprehension just says it in one line." },
            { kind: "code", lang: "python", code: "# the long way\nsquares = []\nfor n in range(5):\n    squares.append(n * n)\n\n# the comprehension\nsquares = [n * n for n in range(5)]   # [0, 1, 4, 9, 16]" },
            { kind: "heading", text: "Adding a filter" },
            { kind: "prose", text: "Add an `if` at the end to keep only the items you want." },
            { kind: "code", lang: "python", code: "evens = [n for n in range(10) if n % 2 == 0]   # [0, 2, 4, 6, 8]" },
            { kind: "heading", text: "Dict comprehension" },
            { kind: "prose", text: "The same shape builds a dictionary." },
            { kind: "code", lang: "python", code: 'lengths = {word: len(word) for word in ["hi", "world"]}\nprint(lengths)   # {\'hi\': 2, \'world\': 5}' },
            { kind: "callout", tone: "tip", text: "Comprehensions shine for simple transforms and filters. If one grows long or needs several steps, a normal loop is clearer; readability wins." },
            { kind: "keypoints", points: ["List: `[expr for x in seq]`", "Filter: `[x for x in seq if cond]`", "Dict: `{k: v for ...}`", "A comprehension equals a loop that appends", "Prefer a loop when the logic gets complex"] },
            { kind: "practice", text: "Write a comprehension for each:", items: ["The squares of the even numbers from 1 to 20.", "A list of the lengths of each word in a sentence.", "A dict mapping each word in a list to its length.", "From a list of numbers, keep only those greater than 10."] },
          ],
        },
      ],
    },
    {
      id: "py-robust",
      title: "Writing robust code",
      lessons: [
        {
          id: "py-errors",
          title: "Errors & debugging",
          summary: "Read tracebacks and handle failures gracefully.",
          blocks: [
            { kind: "prose", text: "Errors are not failures, they are feedback. Every programmer hits them constantly; the skill is reading them calmly and knowing what to do." },
            { kind: "heading", text: "Reading a traceback" },
            { kind: "prose", text: "When Python hits a problem it stops and prints a traceback. Read it bottom-up: the very last line names the error type and message, which is the part you act on." },
            { kind: "code", lang: "python", code: "nums = [1, 2, 3]\nprint(nums[5])\n# IndexError: list index out of range" },
            { kind: "heading", text: "Common errors to recognise" },
            { kind: "prose", text: "A few error types cover most early bugs. Learning their names tells you what went wrong at a glance." },
            { kind: "code", lang: "python", code: 'int("hi")          # ValueError: not a valid number\nnums[99]           # IndexError: index out of range\nuser["missing"]    # KeyError: key not in the dict\n"a" + 1            # TypeError: can\'t add str and int\nprint(undefined)   # NameError: name is not defined' },
            { kind: "heading", text: "Handling with try / except" },
            { kind: "prose", text: "Wrap code that might fail in `try`, and put the recovery in `except`. The program keeps running instead of crashing." },
            { kind: "code", lang: "python", code: 'try:\n    age = int(input("Age: "))\n    print(age + 1)\nexcept ValueError:\n    print("Please enter a whole number.")' },
            { kind: "callout", tone: "tip", text: "Stuck on a bug? Print the variable and its `type()` on the line just before the failure. Seeing the actual value usually reveals the problem instantly." },
            { kind: "keypoints", points: ["Read tracebacks bottom-up: the last line is the real error", "Common: `ValueError`, `TypeError`, `IndexError`, `KeyError`, `NameError`", "`try` / `except` handles errors without crashing", "Catch a specific error type, not everything", "Debug by printing values and types before the failing line"] },
            { kind: "practice", text: "Practise handling failure:", items: ["Wrap an `int(input())` in try/except so bad input prints a friendly message.", "Trigger an IndexError on purpose and read the traceback out loud.", "Use `.get()` to avoid a KeyError when a dict key might be missing.", "Add print statements to find why a small buggy function gives the wrong answer."] },
          ],
        },
      ],
    },
  ],
};